project:
  type: book
  output-dir: _book

book:
  title: "Data Science, the SQL"
  reader-mode: true
  page-footer:
    left: |
      Data Science, the SQL
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/tidydata_6.png
  favicon: images/favicon.ico
  site-url: https://sds261-sql.netlify.app/
  repo-url: https://github.com/hardin47/SDS261-SQL
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

    - part: intro-to-sql.qmd
      chapters:
        - 01-sql-hello.qmd

    - part: using-sql.qmd
      chapters:
        - 04-select.qmd
        
    - part: reg-expr.qmd
      chapters:
        - 07-text-data.qmd


bibliography: 
  - book.bib
  - packages.bib

format:
  html:
    theme:
      light: [cosmo, scss/ims-style.scss]
      dark: [cosmo, scss/ims-style-dark.scss]
    code-link: true
    mainfont: Atkinson Hyperlegible
    monofont: Source Code Pro
    #include-in-header: js/mathjax-popover.html
    author-meta: "Jo Hardin"
    lightbox: 
      match: auto
      loop: false 

editor: source

execute:
  freeze: auto
  fig-width: 6
  fig-show: hold
  fig-dpi: 300
  fig-align: center
  echo: false
  cache: false
  warning: false 

knitr:
  opts_chunk: 
    dev: "ragg_png"
    fig-asp: 0.618  # 1 / phi
