--- 
title: "Getting Started with R & RStudio"
author: "Jo Hardin"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
header-includes:  \usepackage{blkarray}
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: hardin47/website/introR/
description: "Some basics to get people started working with R and the tidyverse."
---



```{r eval=FALSE, include = FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")

setwd("~/gitRepos/website/introR")
#bookdown::render_book("index.Rmd", "bookdown::gitbook")

bookdown::render_book("index.Rmd", output_dir = "tutorials")
```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```



```{r include = FALSE, eval=FALSE}
# http://personal.psu.edu/drh20/525/
# http://personal.psu.edu/drh20/525/assignments/

# categorical & poisson: https://newonlinecourses.science.psu.edu/statprogram/stat504
# https://newonlinecourses.science.psu.edu/stat504/

# broadening your statistical horizons (roback & legler) https://bookdown.org/roback/bookdown-bysh/

# modern dive: https://moderndive.com/

```


```{r, eval=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.height=3, fig.width=5, 
                      fig.align = "center")

library(tidyverse)
library(broom)
library(caret)
```
