---
title: "Assignments"
author: "Jo Hardin"
date: "Fall 2018"
output: html_document
---



Some general thoughts on ([writing](../ID1/writing.html))

 

 

## Informal Papers

 

1. Find an example from the readings of a type of chance occurrence or situation that has a randomness component.  Explain why (inherently) it is counterintuitive.  Then explain why it is actually correct. (Due Tuesday 9/7/10)

 

2. Reading with and against the grain (see handout).  Note, these are just fancy talking points.  No formal paper.  (Due Tuesday 9/21/10)

 

3. Find a poll (from a national newspaper, a college newspaper, a website you frequent…) and try to get as much information as you can about the poll (Who they asked, What they asked, Who funded it,…)  Then ask as many questions as you can about the poll (How do they know that? How were the people selected? Who did they miss?...)  I simply want the poll, information about the poll, and the questions you have about it.  This does not need to be written up in a “paper” type manner.  Just lists/bullet points are fine.  If you are having trouble finding a poll, check out USA Today’s Snapshots: http://www.usatoday.com/news/snapshot.htm (Due Thursday 10/14/10)

 

4.  Library Assignment: Find two articles about a particular treatment (drug, etc.) for a given disease or medical condition.  One of the articles must be from a peer-reviewed journal (for example, The Journal of the American Medical Association, The Lancet, or The New England Journal of Medicine).  The other article must be something from the mainstream press.  You can find the second article on-line, but it has to also exist in paper (for example, it’s okay if you get it from the NY Times on-line, but you should be able to tell me the date it appeared in print in the NY Times.)  The articles should discuss the same disease or medical condition, and ideally they’ll also discuss the exact same treatment and study (this will make your life easier in about a month.) 

Your assignment is to simply give me a copy of the articles and summarize the treatment given for the disease or medical condition.  Also, you must give the complete citation (note: good idea to look up how to cite in your Hacker guide) for each of the articles. (due Thursday 10/28/10)

Note 1:  You want your medical article to be a review article.  Think of it as the current state of treatment with respect to that disease.  You want the authors to have looked at many studies and to have summarized them for you.

Note 2:  For many diseases, there will be a leading journal in a particular field.  If you know you are interested in a particular disease, contact Kate or Professor Hardin for ideas of good journals.

Note 3: Some possible diseases are (but feel free to think outside the box!!):

Ascariasis

Leishmaniasis

Aspergillosis

Malaria

Botulism

Onchocerciasis

Cardiovascular disease

Pertussis

Cholera

Plague

Creutzfeldt-Jacob disease

Poliomyelitis

Dengue Fever

Salmonellosis

Diabetes Mellitus

SARS

Dracunculiasis

Schistosomiasis

Ebola

Shigellosis

Giardiasis

Staphylococcal diseases

Hansen Disease

Syphilis

Hepatitis (A, B, or C)

Tuberculosis

Inuenza

Typhoid fever

Legionellosis

Yellow fever

 

5. Paper workshop (more on the assignment later).

 

 

## Moderately formal Papers 
(These papers should be written using formal paper guidelines: argue a succinct idea, no contractions, etc., but they are short and should be a fun way for you to express what you think about the situation at hand.)

 

1. Assume you are on the jury in the movie 12 Angry Men .  At what point are you convinced that there is reasonable doubt [never is an okay answer, as long as you make an argument]? (~2 pages,  due Thursday 12/2/10, 5pm)

2. Assume you are on the jury for people vs. Simpson .  At what point are you convinced that there is reasonable doubt [never is an okay answer, as long as you make an argument]?  (~2 pages,  due Thursday 12/9/10, 5pm)

 

## Formal Papers
(instructions and thoughts on ([writing](../ID1/writing.html)) a paper / giving feedback to introductions)

 

1. Paper assignment (5-6 ish pages, choose one topic from list below):   Note that all your arguments should be based on the readings.  Appropriate references should be given using APA format.

 

* Discuss how the theme of free will plays similar or different roles in Rosencrantz and Guildenstern are Dead and “How Much Shall We Bet?”, Cosmicomics.

 

* In “The Babylon Lottery” Borges suggests ways of decision making in every day life.  How do his suggestions change as the lottery becomes more extreme and integrated into our/their lives?  As the story progresses, does rational decision making become possible or impossible? [you might include your take on what “rational decision making” is]

 

 * To Dostoevsky, what is “fate,” and how does it differ from “chance?”  How do fate and chance affect characters’ decisions throughout the novel? 

 

 * Compare two different gamblers from The Gambler.  In what ways are they similar or different with respect to their motivation and/or destinies?  You may want to consider characteristics such as gender, nationality, age,…  [You may not compare Granny with Alexey.]

 

 * A topic of your choice dealing with the fiction stories we have read in class.  If you choose this option, you must meet with me at least one day before the topic is due so that I can approve your topic.

 

 Dates are:

            Introduction and Main Ideas  (due Monday, 5pm  9/27/10)

            Comments on at least 3 other introductions (due Thursday, 5pm  9/30/10)

            First complete version (due Monday, 10/4/10 )

            Comments back Thursday 10/7/10 

            Revised paper (due Tuesday, 10/12/10)

 

 

2. Paper assignment (4-5 pages).  You should write on one of the following prompts.  Note, again your arguments should be based on the readings from class.  It’s okay to bring in outside sources, but they must be referenced, and the majority of your arguments should be based on readings from class.

 

*  In the movie Magic Town, Rip Smith polls the citizens of Grandview which, apparently, is a good representation of the entire US.  Let’s agree that the movie is accurate when it says that Grandview has the same proportion of men/women, farmers, democrats/republicans, etc. as in the US.  Even before the citizens find out that Grandview is being used as a “mathematical miracle,” Rip should not have been able to obtain the results he did.  Argue the previous statement using at least three of what you think are the most important reasons.  Feel free to use outside readings (from class or that you find elsewhere).

 

 

*  On Nov 3, 1948 the Chicago Tribune printed a front page headline, “Dewey Beats Truman.”  Describe what happened to make the Tribune print such a mistake (use credible sources for your background material, and be sure to cite them).  If you could change only one thing prior to the election (in the hopes of getting the results right), what would it be?  Use the readings from class and/or outside readings to base your argument.

 

*  In the internet age, we think that all information is at our fingertips.  But contrary to common thought, accurate public opinion is very difficult to obtain.  Discuss the problems with past and current survey methods and argue for an ideal information-gathering model.  That is, how can we best improve?  What statistical principles are invoked?  

 

*  A topic of your choice dealing with the readings from this section.  If you choose this option, you must meet with me at least one day before the abstract is due so that I can approve your topic.

 

 

Dates are:

            Abstract  (due Thursday 10/21/10)  (to your drop box, not the forum)

            First complete version (due Monday 10/25/10)

            In class peer editing 10/26/10

            Peer edits back Monday 11/1/10  NOON

            Meet with Professor Hardin Tues 11/2 – Fri 11/5

            Revised paper (due Tuesday 11/9/10), 5pm     

3. Research Paper assignment (7-10 pages).  Your paper will be on a particular treatment (or treatments) of a disease or condition that you choose.  Assignment

 

Prompt: Your roommate (or anyone else) has disease / condition X and is considering treatment Y.  Advise.  [ The idea of the paper is to commit to a suggestion based on what you’ve read about the disease and treatment.  Would you take it?  Would you advise someone else to take it? ]

 

Handout on finding background sources 

 

Dates are:

            Topic & Annotated Bibliography  (due Tuesday 11/16/10)

            First complete version (due Tuesday 11/23/10)

            Revised paper (due Tuesday 12/07/10)         

 

 

 