---
title: "ID1 Schedule"
author: "Jo Hardin"
date: "Fall 2018"
output: html_document
---

# Readings / Discussions / Due dates

### Week 1

9/4   No Class – Convocation

9/6   Introductory stuff, syllabus, webpage info

9/9   Due (Sunday by midnight to Sakai): Micro-essay on chance

 
### Week 2 (Against intuition / sports)

 9/11     Discussion / Context / Summary: Professor Hardin  
 Some general thoughts on [discussions](../ID1/Discussion-Instructions.pdf)

- Tversky, A. and Kahneman, D. (1974). "Judgment under uncertainty: heuristics and biases."  *Science*, vol 185, pgs 1124-1131. (https://library.claremont.edu/)
- Utts, J. (2005/2015). "Psychological influences on personal probability" (chp 16 in 4ed, chp 17 in 3ed).  *Seeing Through Statistics*. 

 
 9/13     Discussion: Jacob  / Context: Jared / Summary:  Lydia

- Utts, J. (2005/2015). "When intuition differs from relative frequency" (chp 17 in 4ed, chp 18 in 3ed).  *Seeing Through Statistics*.  
- Berry, S. (2006) "Statistical fallacies in sports." *Chance*, vol 19, pgs 50-56.  (on Sakai)
- Lewis, M. (2003) *Moneyball*, pgs 66 - 73 and 272 - 275. (on Sakai)
- James, B.,  Albert, J.,  and Stern, H. (2005)  "Answering questions about baseball using statistics." *Anthology of Statistics in Sports.* Chp 15, pgs 111 - 117.  (on Sakai)
- Ross, T. (June 25, 2015) "Welcome to smarter basketball." *The Atlantic*.  https://www.theatlantic.com/entertainment/archive/2015/06/nba-data-analytics/396776/  

<!---
  ### Week 3 (Fiction)
  9/18   Discussion:
  Bernstein, P. The failure of invariance.  Against the Gods. (Sakai)
Maloney, R. Inflexible logic. (Sakai)
Cole, K.C. Calculated risks.  The Universe and the Teacup. (Sakai)
9/20    
Stoppard, T.  Rosencrantz & Guildenstern are Dead (Sakai)
Calvino, I. How much shall we bet?  Cosmicomics. (Sakai) 
--->

9/16    Due (Sunday, midnight to Sakai): Micro-essay on believing/doubting game (based on next Tuesday's reading!)

### Week 3 (Fiction)

9/18      Discussion: Jared  / Context: Keath / Summary: Vanessa

- Borges, J.L.  "The Babylon lottery." *Ficciones*. (on Sakai)      

9/20    Discussion: Cameron  / Context: Ethan  / Summary:  Jacob  
9/20    Due (Thursday, midnight to Sakai): Micro-essay for paper 1

- Dostoevsky, F.  *The Gambler*. (Huntley)  




### Week 4 (Sampling)


9/25    Library Day  
        Due (bring with you on paper): library notes  

9/27      Discussion: Will  / Context: Lydia / Summary:  Cathy

- [nothing to read here, we'll do in class] Sampling applet: http://www.rossmanchance.com/applets/OneProp/OneProp.htm?candy=1  


- Utts, J. (2005/2015) "How to get a good sample" (chp 4).  *Seeing Through Statistics*.   
- Bryson, M. (1976).  "The Literary Digest poll: making of a statistical myth." *The American Statistician*, vol 30 (no 4), pages 184-185. (on Sakai)  
- Radwin, D. (October 5, 2009). "High response rates don’t ensure survey accuracy."  *The Chronicle of Higher Education*. (on Sakai)   
- Ranganathan, M. (November 4, 2014), "Where are the real errors in political polls?", *Scientific American*.  https://blogs.scientificamerican.com/guest-blog/where-are-the-real-errors-in-political-polls/    
- [skim don't read:]  Meng, X.-L. (2018) "Statistical Paradises and Paradoxes in Big Data:  law of large populations, big data paradox, and the 2016 US presidential election."  *The Annals of Applied Statistics*.  https://projecteuclid.org/download/pdfview_1/euclid.aoas/1532743473  [n.b., This article is very technical.  You should **skim **it to get the basic ideas of statistical modeling to address issues of non-random sampling.  **Do not try to understand the technical details**.]


### Week 5 (2016 election)

10/1      Due (Monday at midnight on Sakai): Paper 1  

10/2      Discussion: Franco  / Context: Cathy / Summary: Malvi  

- Final FiveThirtyEight prediction:  https://projects.fivethirtyeight.com/2016-election-forecast/  
- Alexander, J. (2010) "Appendix on the poll of polls." *The Performance of Politics*. (on Sakai)  
- Silver, N. (2014) "How FiveThirtyEight Calculates Pollster Ratings" *FiveThirtyEight* https://fivethirtyeight.com/features/how-fivethirtyeight-calculates-pollster-ratings/ and https://projects.fivethirtyeight.com/pollster-ratings/  
- Cohn, N. (October 12, 2016) "How one 19-Year-Old Illinois man is distorting national polling averages." *The New York Times*. https://www.nytimes.com/2016/10/13/upshot/how-one-19-year-old-illinois-man-is-distorting-national-polling-averages.html  
- Cohn, N. (September 20, 2016), "We gave four good pollsters the same raw data.  They had four different results." *The New York Times*.  https://www.nytimes.com/interactive/2016/09/20/upshot/the-error-the-polling-world-rarely-talks-about.html  
- [AND THE FOLLOW UP] Gelman, A. (September 23, 2016) "Trump +1 in Florida; or, a quick comment on that '5 groups analyze the same poll' exercise."  http://andrewgelman.com/2016/09/23/trump-1-in-florida-or-a-quick-comment-on-that-5-groups-analyze-the-same-poll-exercise/
- [NOTE THE DATE HERE] Silver, N. (October 24, 2016) "Election update: why our model is more bullish than others on Trump." *FiveThirtyEight* http://fivethirtyeight.com/features/election-update-why-our-model-is-more-bullish-than-others-on-trump/
- [NOTE THE DATE HERE] Grim, R. (November 5, 2016)  "Nate Silver is Unskewing Polls - All of Them - In Trump's Direction" HuffPost https://www.huffingtonpost.com/entry/nate-silver-election-forecast_us_581e1c33e4b0d9ce6fbc6f7f  
- Silver, N. (November 8, 2016) "Final election update: There's a wide range of outcomes, and most of them come up Clinton." *FiveThiryEight*. https://fivethirtyeight.com/features/final-election-update-theres-a-wide-range-of-outcomes-and-most-of-them-come-up-clinton/   


<!--
- Rutenberg, J. (November 9, 2016), "A 'Dewey Defeats Truman' lesson for the digital age." *The New York Times*. https://www.nytimes.com/2016/11/09/business/media/media-trump-clinton.html  
- Silver, N. (November 11, 2016) "Why FiveThirtyEight gave Trump a better chance than almost anyone else." *FiveThiryEight*.  https://fivethirtyeight.com/features/why-fivethirtyeight-gave-trump-a-better-chance-than-almost-anyone-else/  
- Gross, J. (November 29, 2016) "How to better communicate election forecasts - in one simple chart." *The Washington Post*. https://www.washingtonpost.com/news/monkey-cage/wp/2016/11/29/how-to-better-communicate-election-forecasts-in-one-simple-chart/
- Bump, P. (August 9, 2018) "New data makes it clear: Non-voters handed Trump the presidency." *The Washington Post.* https://www.washingtonpost.com/news/politics/wp/2018/08/09/new-data-makes-it-clear-nonvoters-handed-trump-the-presidency/  
--> 


10/4      Peer review
10/4      Due (printed in class): completed peer review



### Week 6  (Models for 2018 / Decolonizing Statistics)

10/9      Discussion: Vanessa  / Context: Cameron / Summary: Chris  

- [Toggle at the top to see different genres, scroll down to see individual races]  https://projects.fivethirtyeight.com/2018-midterm-election-forecast/house/   
- [THEIR METHODS!] Silver, N. (August 16, 2018) "How FiveThirtyEight's House Model Works." *FiveThirtyEight*. https://fivethirtyeight.com/features/2018-house-forecast-methodology/  


- Pew Research Center (August 9, 2018) "For most Trump voters, 'Very Warm' feelings for him endured." http://assets.pewresearch.org/wp-content/uploads/sites/5/2018/08/13090439/8-9-2018-Validated-voters-release1.pdf   
- American Association for Public Opinion Research "An evaluation of 2016 election polls in the U.S." https://www.aapor.org/Education-Resources/Reports/An-Evaluation-of-2016-Election-Polls-in-the-U-S.aspx    
- Gelman, A. and Azari, J. (2017) "19 things we learned from the 2016 election." *Statistics and Public Policy*, vol 4, pages 1-10.  https://www.tandfonline.com/doi/full/10.1080/2330443X.2017.1356775   
- Barbaro, M. (August 10, 2018) "The Trump voters we don't talk about" *The Daily*. https://radiopublic.com/TheDaily/ep/s1!3abf8     


<!--- Iraqi death count, cell phones, ...
http://pages.pomona.edu/~jsh04747/courses/id1/iraqi_death_count_npr.mp3
NPR story on Iraqi death count (This American Life, Nov 3, 2006, “What’s in a Number?” Act One: Truth, Damn Truth, and Statistics; Act Three: The War this Time. 23 min long) --->



10/11     Discussion: Lydia  / Context: Vanessa / Summary: Cameron  
10/12     Due (Friday, by midnight to Sakai): Paper 1, after peer review

- Champkin, J. (January 24, 2014) "The timeline of statistics." *Significance*.  https://www.statslife.org.uk/history-of-stats-science/1190-the-timeline-of-statistics
- Iseke-Barnes, J. (2000) "Ethnomathematics and Language in Decolonizing Mathematics." *Race, Gender, & Class*, Vol 7, pgs 133-149.  https://www.jstor.org/stable/41674951   
 

### Week 7 (Decolonizing Statistics / Reproducibility)

<!--- https://research.pomona.edu/janice-hudgings/teaching/bias-and-privilege-in-physics/ --->

10/16       Discussion: Ethan  / Context: Will / Summary: Jared   
10/16       Due (Tuesday, midnight to Sakai): Micro-essay on Paper 2

-  Steele, C. (1997) "A Threat in the Air: How Stereotypes Shape Intellectual Identity and Performance." *American Psyhologist*, vol 52, pgs 613-629.  
- Su, F. (2015) "Mathematical Microaggressions."  *MAA Focus*. http://digitaleditions.walsworthprintgroup.com/publication/?i=278032&p=36  



10/18       Discussion: Brandon  / Context: Jacob / Summary: Franco   

- Peng, R. (June 6, 2014) "The real reason reproducible research is important." *simplystatistis.org* https://simplystatistics.org/2014/06/06/the-real-reason-reproducible-research-is-important/  
- Bialik, C. (May 20, 2015) "As a major retraction shows, we're all vulnerable to faked data." *FiveThirtyEight*.  https://fivethirtyeight.com/features/as-a-major-retraction-shows-were-all-vulnerable-to-faked-data/  
- Baumer, B., Kaplan, D., Horton, N. (2017)  "Professional ethics." *Modern Data Science with R*.  http://mdsr-book.github.io/excerpts/mdsr-ethics.pdf


### Week 8

10/23     Fall Break
10/23     Due (Tuesday, by midnight, to Sakai): Paper 2

10/25      Peer review
10/25      Due (printed in class): completed peer review



### Week 9 (Machine Bias)


10/30     Discussion:  Andriw / Context: Brandon / Summary: Keath  

- O'Neil, C. (2016) *Weapons of Math Destruction*, pages 1-31, 84-104. (on Sakai)   
- Angwin, J., Larson, J., Mattu, S., and Kirchner, L. (May 23, 2016), "Machine bias." *ProPublica*.  https://www.propublica.org/article/machine-bias-risk-assessments-in-criminal-sentencing  
- Angwin, J. and Larson, J. (December 30, 2016) "Bias in criminal risk scores is mathematically inevitable, researchers say." *ProPublica*.  https://www.propublica.org/article/bias-in-criminal-risk-scores-is-mathematically-inevitable-researchers-say  


<!---
Hadley also has a great list!!!
https://github.com/hadley/stats337
--->

11/1     Discussion: Malvi  / Context: Andriw / Summary: Brandon

- Lupi, G. and Posavec, S. (2016) In particular, weeks: 1, 14, 17, 18, 22, 24, 39, & 52. *Dear Data*.  http://www.dear-data.com/by-week/ 
- Tufte, E. (1997).  *Visual and Statistical Thinking: displays of evidence for making decisions*.  You can buy it here, but you can find it elsewhere:  http://www.edwardtufte.com/tufte/books_textb


11/4      Due (Sunday by midnight, to Sakai): Paper 2, after peer review



### Week 10 (Human Perception of Graphs)

11/6       Discussion: Chris  / Context: Franco / Summary:  Andriw  

- Elliott, K. (May 2, 2016) "39 studies about human perception in 30 minutes." *Medium*.  https://medium.com/@kennelliott/39-studies-about-human-perception-in-30-minutes-4728f9e31a73
- Utts, J. (2005/2015). "Plots, graphs, and pictures" (chp 9).  *Seeing Through Statistics*. (Huntley)
- Huff, D. (1982). "The gee-whiz graph & the one dimensional picture."  *How to Lie with Statistics*.  (on Sakai)

11/8      

Some tips are here:   https://fivethirtyeight.com/features/dear-data-and-fivethirtyeight-want-you-to-visualize-your-podcast-habits/

- Dear Data presentations
- What is going on in this graph? https://www.nytimes.com/column/whats-going-on-in-this-graph   



Due:  this week you should be working on your data postcards   
Dear Data postcard (due by Wednesday midnight to Sakai).      
Some tips are here: https://fivethirtyeight.com/features/dear-data-and-fivethirtyeight-want-you-to-visualize-your-podcast-habits/  


### Week 11 (Causation)

11/13     Discussion: Keath  / Context: Samuel / Summary: Ethan   
   
- Utts, J. (2005 /2015) "Experiments and observational studies" (chp 5). *Seeing Through Statistics*.
- O'Neil, C. (2016) *Weapons of Math Destruction*, pages 173-178. (on Sakai)
- Carroll, A. (August 6, 2018) "Workplace wellness programs don't work well.  Why some studies show otherwise." *The New York Times*.  https://www.nytimes.com/2018/08/06/upshot/employer-wellness-programs-randomized-trials.html  


11/15     Discussion: Samuel  / Context: Malvi / Summary:  Will 
11/15     Due (Tuesday, midnight to Sakai): Micro-essay on paper 3

- Meier P. (1989)  The biggest public health experiment ever: the 1954 field trial of the Salk poliomyelitis vaccine.  Statistics: A Guide to the Unknown, 3rd edition.  The Joint Committee on the Curriculum in Statistics and Probability of the American Statistical Association and the National council of Teachers of Mathematics.  Duxbury Press: Belmont, California. (Sakai)
- Altman, D. (1980) "Statistics and ethics in medical research. Misuse of statistics is unethical." *British Medical Journal*.  vol 281, pgs 1182-1184.   https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1714517/pdf/brmedj00045-0026.pdf  



### Week 12 (Medicine)

11/20     Discussion: Cathy  / Context: Chris / Summary: Samuel 

- http://andrewgelman.com/2015/05/29/i-fooled-millions-into-thinking-chocolate-helps-weight-loss-heres-how/  
- http://notstatschat.tumblr.com/post/120095349481/was-the-fake-chocolate-study-unethical  
- https://www.buzzfeednews.com/article/stephaniemlee/brian-wansink-cornell-p-hacking  
- https://www.vox.com/science-and-health/2018/2/28/17061828/joy-of-cooking-brian-wansink-cornell-p-hacking  
- http://www.stat.columbia.edu/~gelman/research/unpublished/p_hacking.pdf  

-  Abramson, J. (2005). False and misleading: the misrepresentation of Celebrex and Vioxx. Overdo$ed America. (Sakai)
- Carroll, A. (August 28, 2018) Study Causes Splach, but Here's Why You Should Stay Calm on Alcohol's Risks. *New York Times*. https://www.nytimes.com/2018/08/28/upshot/alcohol-health-risks-study-worry.html
- Fat Politics  
- Monaghan L., Colls, R., and Evans, B. (2013) "Obesity discourse and fat politics: research, critique and
interventions." *Critical Public Health*.

11/22     Thanksgiving

11/25     Due (Sunday by midnight to Sakai): Annotated Bibliography for paper 3

### Week 13 (Medicine)

11/27     Discussion:   / Context:  / Summary: 

- quality of life, how to measure, Dear Data

- Harmon A.  18 September 2010.  NYT Online.  New Drug Stirs Debate on Rules of Clinical Trials.  
http://www.nytimes.com/2010/09/19/health/research/19trial.html?hp
- Rabine, R.  24 September 2018.  NYT Online  Trial by Fire: Critics Demand that a Huge Sepsis Study Be Stopped.  https://www.nytimes.com/2018/09/24/health/sepsis-trial-treatments.html
- Gawande A.  (2010).  Letting Go.  Annals of Medicine.  The New Yorker.  2 August 2010. http://www.newyorker.com/reporting/2010/08/02/100802fa_fact_gawande
- Gould SJ.  The median isn’t the message.  CancerGuide: Statistics. 


11/29     Discussion:   / Context:  / Summary: 


- 12 Angry Men

12/2      Due (Sunday by midnight to Sakai): Paper 3

<!---
maybe this article on presenting quantitative information to patients

- Trevena, L. et al. (2013) "Presenting quantitative information about decision outcomes: a risk communication primer for patient decision aid developers." *BMC Medical Informatics & Decision Making*. Vol 13, S7.  http://www.biomedcentral.com/1472-6947/13/S2/S7
--->



### Week 14 (Law)

12/4

- 12 Angry Men
- Cobb, G. and Gehlbach, S. (2006). Statistics in the courtroom.  Statistics: a Guide to the Unknown.  
- Utts, J. (2005). Chapters 22, 23, 24.  Seeing Through Statistics. (Huntley)  


12/6      Discussion:   / Context:  / Summary: 

More on law...

### Week 15

12/11     Class presentations  (Wednesday 12/12?)
12/11     Due (Tuesday by midnight to Sakai): Paper 3, after peer review  

<!---
- Evans, J. (2017) *Thinking and Reasoning: A Very Short Introduction*
- Utts, J. (2005). Chapters 22, 23, 24.  Seeing Through Statistics. (Huntley)  
- Lucy, D. (2005). Introduction to Statistics for Forensic Scientists. Selected pages (Sakai)  
- Kaplan, M. and Kaplan, E. (2006). Judging.  Chances Are…Adventures in Probability.  (Sakai)  
- Cobb, G. and Gehlbach, S. (2006). Statistics in the courtroom.  Statistics: a Guide to the Unknown. (Sakai)  
- Weir, B. (2006). DNA Fingerprinting.  Statistics: a Guide to the Unknown. (Sakai)  
--->

12/13     Reading Days

 
 
 
 
