---
title: "On Writing"
author: "Jo Hardin"
date: "Fall 2018"
output: html_document
---


## Writing Center

(Smith Campus Center 148)    The Pomona College Writing Center offers free, one-on-one consultations to all students enrolled in Pomona College courses. Our mission is to provide an inclusive and collaborative space for students to talk about their writing projects and processes. We welcome all kinds of writing, including academic, creative, professional, and personal, in all stages of development, from brainstorming to the final draft. Our aim is to center students’ voices and goals as they navigate varying expectations of writing across genres. The Writing Partners are Pomona students—sophomores, juniors, and seniors—majoring in disciplines as varied as Biology, Spanish, and History. They are trained to work with writers at all levels, and on work in any area. Multilingual Specialist Jenny Thomas is also available at the Writing Center, to work with international and multilingual students on navigating writing and other forms of communication in the US academic context; stop by or make an appointment - look for 'Multilingual Specialist' on the scheduler. Consultations are available by appointment, which students can make online at  [writing.pomona.edu](https://www.pomona.edu/administration/writing-center).  The Writing Center also offers drop-in hours Sundays through Thursdays from 8-10pm.

## Some Specific Details about Turning in Papers


Really annoying requirements that will make it easier to read many papers:  

* Identify your overall thesis (the core argument around which the entire essay is organized)
and **bold-face** it.  
* Identify the topic sentence of each paragraph and _underline_ or *italicize* it.  
* Name the file you upload to Sakai like this: Paper#.LastName.doc, as in Paper2.Gallup.doc.  
* Be sure that your name, title of the paper, and date are on the manuscript itself.  
* Double-spaced with 12 point type and at least 1 inch margins to write comments in.  
* Any reference / citation formatting is fine, but please be consistent.  
* Print a word-count at the end of your paper.  


## Some General Thoughts on Writing


(many of these ideas due to Professor Sarkis)

#### Introduction

Your task is to describe the main topic you plan to tackle in your formal paper.  It should be specific enough to identify your paper (meaning that saying you intend to write about monkeys typing great works of literature is too general), but of course cannot contain all the arguments that your paper will contain.


It is common for (academic) writers to write their introductions last, after they had completed the rest of the text.  The reasoning behind that is quite logical: one should know what is being introduced well if the introduction is to be effective.  You might find it useful to brainstorm and jot down outlines of your entire paper, highlighting the specific topics you'll deal with, the progression of ideas, the conclusion, etc., all before you write the abstract.

 
You might also find it useful to consult the readings.  Naturally, your topic should be selected from the texts we have read so far.  The following is a list of questions you can ask yourself about the introduction / ideas for the essay you are writing.

* Is the basic idea or insight a good one?

* Is it supported by logical reasoning or valid argument?

* Is it supported by evidence and examples?

* Is there a clear point of view (thesis!!)?

* Does the idea answer the question / address the topic?

* Is the idea succinct enough for the audience and purpose?

* Are there mistakes in grammar, usage, spelling, or typing?

* Is the tone or formality appropriate?

 

 
#### Formal Paper Guidelines


* basic structure:  If you've never written such scholarly papers before--and I'm not assuming you have--then you might find the following general guidelines helpful.  If on the other hand you are comfortable with the format, and you are confident of your ability to produce a cohesive, coherent paper while riffing on a theme, you can certainly vary the approach.

 

      >intro-body-conclusion. Try dividing your paper into an introductory paragraph which motivates the topic, and which ends with a very clearly stated thesis; a body which discusses, elaborates on and elucidates the thesis; and a concluding paragraph which, instead of just repeating what was said in the paper, continues the topic in a different-but-related direction, leaving the reader intrigued and thinking.

      >main body. Your paper will probably read more clearly if you restrict your ideas to one per paragraph. (It is easy for the reader to get thrown off if there's a change of subject that happens from one sentence to the next), and if the first sentence of each paragraph gives the reader a good idea of what that paragraph is about, even better.   HOWEVER, each of the ideas in the main body should build on one another (test: if you can rearrange your paragraphs in any order, they aren’t building on one another).

      >tone. With a formal paper, it is a good idea to avoid casual-speak, first person narratives, contractions, and other informalities.

 

 

* guidelines:  Try to think about the essay questions in a new light.  That is, feel free to use/connect some of the ideas we’ve talked about in class, but don’t just rehash one idea that we talked about for an entire hour.  For example, a paper on the difference between chance and fate won’t be particularly interesting given how much we’ve already discussed it.  3 important aspects to a paper:

 

            > thesis: your paper should have a well defined thesis that you can argue using material from the readings.

            > sense of transition between paragraphs: one easy way to make your paper flow is to make ensure that paragraphs flow seamlessly into one another.

            > active citation: for every claim / idea, you should be able to back-up your statement.  Sometimes you’ll need a quote from the text (especially if we’re writing about literature); sometimes you’ll need a reference to a non-fiction source that won’t be quoted.

 

 


#### Internet References

 

The case of internet references requires a special mention.  Google can be a very useful tool if you do not know, say, what a run-batted-in is, or what heuristics means, or what happens in the play Hamlet. However, it is difficult to distinguish between scholarly work (that has been edited and peer-reviewed, verified and error-checked) and the website of an aficionado made up of very liberal borrowing from other uncited sources. Most web references (certainly including Wikipedia) are not appropriate for a formal paper, and I would strongly advise against them.

 

#### On Rewrites

 

As a follow up to the personalized feedback you got (or will get) on your formal paper, below are a few more general thoughts.

 

* thesis: Your thesis statement should be interesting and arguable.  Be very careful not to simply summarize the chronology of the text.  You should be expressing your personal insight.  If you are having trouble, try reading against the grain.

 

* sentence level. When you are writing, and more importantly, when you are reading what you've written, pay attention to run-on, fragmented sentences like this one that are awkward, contain too many ideas and could be chopped up and rearranged, and also to meaningless or repetitive statements like "Tversky and Kahneman discuss psychological aspects of randomness in their paper ‘Judgment under Uncertainty: Heuristics and Biases.’" Also take heed of excessive verbiage lest you insinuate what you do not signify--if you're not sure what a given word means, look it up! Don't choose big words unless there's a good reason to use them.  Finally, avoid using commas to suggest, pauses in the conversation.

 

* paragraph level.  If you stick to one topic per paragraph, you are more likely to end up with a clear paper whose ideas are easily understood by the reader.  While you certainly wish to transmit complex ideas, you do not want complicated ideas to arise because your prose keeps switching trains of thought.

 

* paper level. Paper level problems can also be concerns of focus. Ask yourself what each paragraph is about, and how it relates to your thesis.  Keep in mind that an ambitious thesis can be very specific (in fact, it is nearly impossible to properly address a general thesis topic in anything less than a book-length exposition!).  The writing center can be very helpful in organizing your ideas in a clear and convincing manner.  I also recommend a brainstorming exercise during which you write down very broad-strokes ideas related to your thesis and then schematically connect them; ask me for more details if you're interested.

 

#### General Suggestions

 

*edit your paper.  Try reading your paper out loud to yourself to catch errors.

 

*avoid truisms.  Some statements can be at once hollow and impossible to prove, disprove or even discuss. For instance, I can safely discard the statement "as cultures change, so do the people in those cultures" from my exposition without loss of meaning!

 

*be specific at the sentence level. "Over time, the availability of different types of food has increased."  Reading this, I find myself asking about the time frame, the people who are consuming the food, the types of food, and the quantities.  Sure, if I dig in a bit deeper, I might divine from context.  But why make your reader work for their money? Why not deliver the full impact up front?

 

Maybe you mean, "During the post-war years between 1948 and 1953, middle-class American housewives saw an increase in the variety and quantity of processed staples like cake mixes and powdered mashed potatoes available in supermarkets."

 

*possessive pronouns and apostrophes.  "who's" always means "who is."  "it's" always means "it is."  The possessive forms of the pronouns "who" and "it" are "whose" and "its."  While we're here: "whom" is used instead of "who" when the pronoun is an object (of a verb or preposition).

 

*references.  Very Important: when quoting directly from a text or else summarizing an idea that you read there, you absolutely must cite that reference. Technically, not citing can constitute plagiarism. Pretty please, be careful!  [ Though if you are simply discussing the plot of the book (without a quote), and you've already told me which book it is, you don’t need to cite the action you describe. ]

 

*always use the present tense when writing about literature.  That’s because the characters will continue to perform the same acts throughout time.

 

*one topic per paragraph.  If you change topics in mid-paragraph, you will likely confuse your poor reader.  Don't think of "topic" in very general terms like "statistics" or "randomness." These are themselves problematic and can create problems on the paragraph level.

 

*try very hard to avoid “this/these/those” in formal writing.  Though sometimes the “this” is clear from your text, more often than not, it isn't.  And we’re back to why make your reader work for their money?  After you’ve written your paper, go back and search for “this” in the paper.  Every time you find one, try to replace the word to make its meaning more clear.





 

 

 

 

 

 

 



