<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 6 Diagnostic Measures I | Linear Models</title>
<meta name="author" content="Jo Hardin">
<meta name="description" content="6.1 Model Conditions linear relationship constant variance independent errors normal errors no outliers (that’s part of the normality condition) Notes: There are no required conditions about the...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 6 Diagnostic Measures I | Linear Models">
<meta property="og:type" content="book">
<meta property="og:description" content="6.1 Model Conditions linear relationship constant variance independent errors normal errors no outliers (that’s part of the normality condition) Notes: There are no required conditions about the...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 6 Diagnostic Measures I | Linear Models">
<meta name="twitter:description" content="6.1 Model Conditions linear relationship constant variance independent errors normal errors no outliers (that’s part of the normality condition) Notes: There are no required conditions about the...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script type="text/x-mathjax-config">
    const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
    for (let popover of popovers){
      const div = document.createElement('div');
      div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
      div.innerHTML = popover.getAttribute('data-content');
      
      // Will this work with TeX on its own line?
      var has_math = div.querySelector("span.math");
      if (has_math) {
        document.body.appendChild(div);
      	MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
      	MathJax.Hub.Queue(function(){
          popover.setAttribute('data-content', div.innerHTML);
      	})
      }
    }
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Linear Models</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Class Information</a></li>
<li><a class="" href="intro.html"><span class="header-section-number">1</span> Introduction</a></li>
<li><a class="" href="wrang.html"><span class="header-section-number">2</span> Data Wrangling</a></li>
<li><a class="" href="viz.html"><span class="header-section-number">3</span> Visualization</a></li>
<li><a class="" href="slr.html"><span class="header-section-number">4</span> Simple Linear Regression</a></li>
<li><a class="" href="infslr.html"><span class="header-section-number">5</span> Inference on SLR Parameters</a></li>
<li><a class="active" href="diag1.html"><span class="header-section-number">6</span> Diagnostic Measures I</a></li>
<li><a class="" href="simult.html"><span class="header-section-number">7</span> Simultaneous Inference</a></li>
<li><a class="" href="la.html"><span class="header-section-number">8</span> Regression using Matrices</a></li>
<li><a class="" href="mlr.html"><span class="header-section-number">9</span> Multiple Linear Regression</a></li>
<li><a class="" href="process.html"><span class="header-section-number">10</span> Modeling as a Process6</a></li>
<li><a class="" href="build.html"><span class="header-section-number">11</span> Model Building</a></li>
<li><a class="" href="analysis-of-variance-anova.html"><span class="header-section-number">12</span> Analysis of variance (ANOVA)</a></li>
<li><a class="" href="diag2.html"><span class="header-section-number">13</span> Diagnostics II</a></li>
<li><a class="" href="shrink.html"><span class="header-section-number">14</span> Shrinkage Methods</a></li>
<li><a class="" href="smooth.html"><span class="header-section-number">15</span> Smoothing Methods</a></li>
<li><a class="" href="anova.html"><span class="header-section-number">16</span> ANOVA</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/hardin47/website">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="diag1" class="section level1" number="6">
<h1>
<span class="header-section-number">6</span> Diagnostic Measures I<a class="anchor" aria-label="anchor" href="#diag1"><i class="fas fa-link"></i></a>
</h1>
<div id="model-conditions" class="section level2" number="6.1">
<h2>
<span class="header-section-number">6.1</span> Model Conditions<a class="anchor" aria-label="anchor" href="#model-conditions"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li>linear relationship<br>
</li>
<li>constant variance<br>
</li>
<li>independent errors<br>
</li>
<li>normal errors<br>
</li>
<li>no outliers (that’s part of the normality condition)</li>
</ul>
<div id="notes-3" class="section level4 unnumbered">
<h4>Notes:<a class="anchor" aria-label="anchor" href="#notes-3"><i class="fas fa-link"></i></a>
</h4>
<ol style="list-style-type: decimal">
<li>There are <em>no</em> required conditions about the explanatory / predictor variable.<br>
</li>
<li>If the explanatory variable is binary, SLR becomes the two-sided t-test.<br>
Remember, <span class="math inline">\(x_i\)</span> are constants, so we don’t think of them as having a distribution. Also, we are allowed to construct whatever <span class="math inline">\(x_i\)</span> we want. That said,<br>
</li>
<li>A larger range of <span class="math inline">\(x_i\)</span> will produce less variable predictions.<br>
</li>
<li>However, outliers in the x-direction can be very influential.</li>
</ol>
</div>
<div id="residuals" class="section level3" number="6.1.1">
<h3>
<span class="header-section-number">6.1.1</span> Residuals<a class="anchor" aria-label="anchor" href="#residuals"><i class="fas fa-link"></i></a>
</h3>
<p><span class="math display">\[\begin{eqnarray*}
\mbox{residual: } e_i &amp;=&amp; Y_i -  \hat{Y}_i \ \ \ \mbox{we can measure}\\
\mbox{error term: } \epsilon_i &amp;=&amp; Y_i - E[Y_i] \ \ \ \mbox{we cannot measure}
\end{eqnarray*}\]</span></p>
<p><strong>mean:</strong> <span class="math inline">\(\overline{e} = 0\)</span> (by definition!). Therefore, the average of the residuals provides no information about whether <span class="math inline">\(E[\epsilon]=0\)</span>.<br>
(note: <span class="math inline">\(\sum e_i = \sum(Y_i - b_0 - b_1 x_i) = 0\)</span> because <span class="math inline">\(\frac{\delta Q}{\delta \beta_0} = 0\)</span>.)<br><strong>variance:</strong> <span class="math display">\[s^2 = \frac{1}{(n-2)} \sum (Y_i - \hat{Y}_i)^2 = \frac{1}{(n-2)} \sum (e_i)^2 = \frac{1}{(n-2)} \sum (e_i - \overline{e})^2 = \frac{SSE}{(n-2)} = MSE\]</span>
<strong>non-independent:</strong> because <span class="math inline">\(\sum e_i=0\)</span>, the residuals are not independent. It is the <span class="math inline">\(\epsilon_i\)</span>, errors, we assume to be independent.</p>
<div id="semistudentized-residuals" class="section level4 unnumbered">
<h4>semistudentized residuals<a class="anchor" aria-label="anchor" href="#semistudentized-residuals"><i class="fas fa-link"></i></a>
</h4>
<p><span class="math display">\[e_i^* = \frac{e_i - \overline{e}}{\sqrt{MSE}} = \frac{e_i}{\sqrt{MSE}}\]</span> But MSE isn’t quite the variance of <span class="math inline">\(e_i\)</span>. It is actually an <em>estimate</em> of the variance of <span class="math inline">\(\epsilon_i\)</span>. But good enough for right now.</p>
</div>
</div>
</div>
<div id="diagnostic-plots-of-residuals" class="section level2" number="6.2">
<h2>
<span class="header-section-number">6.2</span> Diagnostic Plots of Residuals<a class="anchor" aria-label="anchor" href="#diagnostic-plots-of-residuals"><i class="fas fa-link"></i></a>
</h2>
<p>[1] Plots of residuals vs. predictor variables / explanatory variables.<br>
[3] Plots of residuals vs. fitted values.<br>
[6] Box plot (histogram) of residuals.</p>
<p>What do I do if the plots show that the conditions don’t hold??<br>
1. Abandon regression model and use something more appropriate. If you are interested in the coefficients: nonparametrics, time series, random forests. If you are only interested in prediction, maybe it is okay that the conditions don’t hold? But maybe not (e.g., independence is key!). Other prediction models include: random forests, support vector machines, neural networks, loess (smoothing).<br>
2. Transform the variables so that the model does hold.</p>
<div id="violating-linearity" class="section level4 unnumbered">
<h4>Violating Linearity<a class="anchor" aria-label="anchor" href="#violating-linearity"><i class="fas fa-link"></i></a>
</h4>
<p><strong>You see:</strong> a pattern to the scatterplot that isn’t linear<br><strong>You do:</strong><br>
- include a <span class="math inline">\(x^2\)</span> term or other function of <span class="math inline">\(x\)</span>.<br>
- you can linearize a non-linear function, but the interpretation can get complicated.</p>
</div>
<div id="violating-constant-errors" class="section level4 unnumbered">
<h4>Violating Constant Errors<a class="anchor" aria-label="anchor" href="#violating-constant-errors"><i class="fas fa-link"></i></a>
</h4>
<p><strong>You see:</strong><br>
- typically we see errors increase as <span class="math inline">\(x\)</span> increases (which is sometimes easier to see with the absolute value of the residuals).<br>
- not a hugely serious problem (we have less efficient estimates, and our variance estimates are not correct)<br><strong>You do:</strong><br>
- direct approach is to use weighted least squares (we won’t talk about this)<br>
- often transformations stabilize variance</p>
</div>
<div id="violating-independent-errors" class="section level4 unnumbered">
<h4>Violating Independent Errors<a class="anchor" aria-label="anchor" href="#violating-independent-errors"><i class="fas fa-link"></i></a>
</h4>
<p><strong>You see:</strong><br>
- typically due to another variable (time, geographic location, etc.)<br>
- residual should be plotted against that variable.<br><strong>You do:</strong><br>
- work with a model that accounts for a correlated error structure (e.g., time series)</p>
</div>
<div id="violating-normal-errors" class="section level4 unnumbered">
<h4>Violating Normal Errors<a class="anchor" aria-label="anchor" href="#violating-normal-errors"><i class="fas fa-link"></i></a>
</h4>
<p><strong>You see:</strong><br>
- residual plots that are not symmetric<br>
- very general empirical rule: <span class="math inline">\(68\% \pm \sqrt{MSE}\)</span>, <span class="math inline">\(95\% \pm 2\sqrt{MSE}\)</span> (only concerned if grossly different)<br>
- we won’t cover normal probability plots (also called q-q plots)<br><strong>You do:</strong><br>
- non-normality and non-constant variance are often related, and transformations will typically fix both.</p>
</div>
<div id="having-outliers" class="section level4 unnumbered">
<h4>Having Outliers<a class="anchor" aria-label="anchor" href="#having-outliers"><i class="fas fa-link"></i></a>
</h4>
<p><strong>You see:</strong><br>
- typically easiest to see with standardized or studentized residuals<br>
- SLR is not resistant to outliers<br>
- we expect about 95% of studentized residuals to be within <span class="math inline">\(\pm 2\)</span>.<br><strong>You do:</strong><br>
- outliers can seriously deform the least squares estimate. If there is a good reason to keep the value(s), we might consider a nonparametric method which places less weight on such a point.</p>
</div>
<div id="why-do-we-plot-resid-vs.-fitted-and-not-vs.-observed" class="section level4 unnumbered">
<h4>Why do we plot resid vs. fitted and not vs. observed?<a class="anchor" aria-label="anchor" href="#why-do-we-plot-resid-vs.-fitted-and-not-vs.-observed"><i class="fas fa-link"></i></a>
</h4>
<p>We know that <span class="math inline">\(e_i\)</span> and <span class="math inline">\(\hat{Y}_i\)</span> are uncorrelated (this can be shown using linear algebra, also note that <span class="math inline">\(\sum e_i \hat{Y}_i = 0\)</span>). So, if we go from the resid vs. fitted scatterplot to the resid vs. observed scatter plot, we shift each point in the x-direction (only) by an amount equal to the residual. If the residual is negative, then the point will shift to the left. If the residual is positive, then the point will shift to the right. We thus create a positively correlated relationship (between resid and observed). The degree of the shift will depend on the relative magnitudes of the residuals and predicted values.</p>
<p><span class="math inline">\(\Rightarrow e_i \mbox{ and } Y_i\)</span> are correlated and therefore <strong>not</strong> independent. Consider the two examples below. In both examples, the residual is correlated with the response variable. However, it is easier to see the correlation when the residual is not also responsible for the relationship between the response variable and the explanatory variable.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-3"></span>
<img src="02b-diag1_files/figure-html/unnamed-chunk-3-1.png" alt="Three scatterplots.  The first is explanatory vs response; the second is fitted vs residual; the third is response vs residual.  The data are correlated, and the fitted vs residual plot shows some correlation due to the mathematical properties which make the error terms correlated to the response variable." width="672"><p class="caption">
Figure 1.3: With correlated data, it is hard to see the dependence between the response variable and the residuals. However, a careful look at the third plot shows that there is a slightly stronger correlating between the response variable and the residuals than there is between the fitted values and the residuals.
</p>
</div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-4"></span>
<img src="02b-diag1_files/figure-html/unnamed-chunk-4-1.png" alt="Three scatterplots.  The first is explanatory vs response; the second is fitted vs residual; the third is response vs residual.  The data are uncorrelated, but the fitted vs residual plot shows a strong correlation due to the mathematical properties which make the error terms correlated to the response variable." width="672"><p class="caption">
Figure 1.4: With uncorrelated data, it is much easier to see the dependence between the response variable and the residuals.
</p>
</div>
</div>
</div>
<div id="transformations" class="section level2" number="6.3">
<h2>
<span class="header-section-number">6.3</span> Transformations<a class="anchor" aria-label="anchor" href="#transformations"><i class="fas fa-link"></i></a>
</h2>
<p><strong>Important note!!</strong> The idea behind transformations is to make the model as appropriate as possible for the data at hand. We want to find the correct <strong>linear</strong> model; we want our conditions to hold. We are not trying to find the most <em>significant</em> model or big <span class="math inline">\(R^2\)</span>.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-5"></span>
<img src="figs/transfor.png" alt="Taken from Applied Linear Statistical Models, 5th ed. by Kutner et al. Figures 3.13 and 3.15." width="500px"><p class="caption">
Figure 6.1: Taken from Applied Linear Statistical Models, 5th ed. by Kutner et al. Figures 3.13 and 3.15.
</p>
</div>
</div>
<div id="correcting-condition-violations" class="section level2" number="6.4">
<h2>
<span class="header-section-number">6.4</span> Correcting Condition Violations<a class="anchor" aria-label="anchor" href="#correcting-condition-violations"><i class="fas fa-link"></i></a>
</h2>
<p>If we noticed a non-linear relationship, we could certainly think to fit a non-linear trend line. At the same time, we might consider fitting an exponential
relationship, or some other functional form. What we do is still called linear regression, but we transform the data so that the we
are fitting a linear model between <span class="math inline">\(f(y)\)</span> and <span class="math inline">\(g(x)\)</span>. This way, our techniques and theory still follow, least squares etc. For
instance, we might think of fitting a linear relationship to the new variables <span class="math inline">\(y^*=\sqrt{y}\)</span> and <span class="math inline">\(x\)</span>, or possibly <span class="math inline">\(y\)</span> and <span class="math inline">\(x^*=x^2\)</span>. Occasionally, we might think of transforming both variables. One general rule is as follows:</p>
<ul>
<li>If your initial fit shows a violation of the linear condition only, then it is best to transform <span class="math inline">\(x\)</span>.<br>
</li>
<li>If your initial fit shows a violation of the linear condition as well as normality issues or heteroscedasticity, then a transform of <span class="math inline">\(y\)</span> should be considered. There will hopefully be a transformation which will correct both problems at once.<br>
</li>
<li>That is, changing <span class="math inline">\(x\)</span> changes the shape of the relationship. Changing <span class="math inline">\(Y\)</span> changes the error structure (and also often the shape).</li>
</ul>
<p>Note: Formal testing for violations of model conditions is usually not a good idea. Why? Multiple testing problems arise (extra type I errors); additional tests are typically very sensitive to their own technical conditions; and we lose power to detect the differences of interest.</p>
<div id="gdp-example" class="section level3" number="6.4.1">
<h3>
<span class="header-section-number">6.4.1</span> GDP Example<a class="anchor" aria-label="anchor" href="#gdp-example"><i class="fas fa-link"></i></a>
</h3>
<p>Consider the following data which was collected by The World Bank in 2020<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;a href="http://data.worldbank.org/" class="uri"&gt;http://data.worldbank.org/&lt;/a&gt;&lt;/p&gt;'><sup>1</sup></a>. The data include GDP and % Urban Population. A description of the variables as defined by The World Bank are provided below.<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;Thank you to Laura Ziegler at Iowa State for providing the data.&lt;/p&gt;"><sup>2</sup></a></p>
<blockquote>
<p>GDP: “GDP per capita is gross domestic product divided by midyear population. GDP is the sum of gross value added by all resident producers in the economy plus any product taxes and minus any subsidies not included in the value of the products. It is calculated without making deductions for depreciation of fabricated assets or for depletion and degradation of natural resources. Data are in current U.S. dollars.”</p>
</blockquote>
<blockquote>
<p>Urban Population (% of total): “Urban population refers to people living in urban areas as defined by national statistical offices. It is calculated using World Bank population estimates and urban ratios from the United Nations World Urbanization Prospects.”</p>
</blockquote>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-7"></span>
<img src="02b-diag1_files/figure-html/unnamed-chunk-7-1.png" alt="It seems as though the original data don't meet the LINE conditions needed for inference in a linear model." width="672"><p class="caption">
Figure 6.2: It seems as though the original data don’t meet the LINE conditions needed for inference in a linear model.
</p>
</div>
<p>Let’s try to transform the variables to get a model which seems to conform to the LINE technical conditions.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-8"></span>
<img src="02b-diag1_files/figure-html/unnamed-chunk-8-1.png" alt="ln(urban) vs gdp:  seems like taking the natural log of urban makes the relationship worse." width="672"><p class="caption">
Figure 6.3: ln(urban) vs gdp: seems like taking the natural log of urban makes the relationship worse.
</p>
</div>
<p>Alas, it really seems like the <code>gdp</code> variable is more of the problem than the <code>urban</code> variable. Let’s transform <code>gdp</code> instead.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-9"></span>
<img src="02b-diag1_files/figure-html/unnamed-chunk-9-1.png" alt="urban vs gdp^2:  squaring gdp also makes the relationship worse." width="672"><p class="caption">
Figure 1.5: urban vs gdp^2: squaring gdp also makes the relationship worse.
</p>
</div>
<p>The needed transformation should spread out the small <code>gdp</code> values and shrink the large <code>gdp</code> values.</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-10"></span>
<img src="02b-diag1_files/figure-html/unnamed-chunk-10-1.png" alt="urban vs sqrt(gdp):  the square root of gdp seems to help!" width="672"><p class="caption">
Figure 1.6: urban vs sqrt(gdp): the square root of gdp seems to help!
</p>
</div>
<p>The natural log is a stronger function than the square root (that is, it will shrink large values even more.).</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-11"></span>
<img src="02b-diag1_files/figure-html/unnamed-chunk-11-1.png" alt="urban vs ln(gdp):  the natural log of gdp creates a residual plot that seems to follow all of the LINE technical conditions." width="672"><p class="caption">
Figure 1.7: urban vs ln(gdp): the natural log of gdp creates a residual plot that seems to follow all of the LINE technical conditions.
</p>
</div>
<p>The Box-Cox transformations are a class of transformations. Generally, <span class="math inline">\(\ln, \exp\)</span>, square root, and polynomial transformations are sufficient to fit a linear model which satisfies the necessary technical conditions. We won’t spend time learning about Box-Cox, but you can read about them to learn more about transforming variables.</p>
</div>
<div id="interpreting-regression-coefficients" class="section level3 unnumbered">
<h3>Interpreting Regression Coefficients<a class="anchor" aria-label="anchor" href="#interpreting-regression-coefficients"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Example 1:</strong> Transforming <span class="math inline">\(x\)</span>: <span class="math inline">\(x' = \ln(x)\)</span> <span class="math display">\[E[Y] = \beta_0  + \beta_1 \ln(x)\]</span> We can interpret <span class="math inline">\(\beta_1\)</span> in the following way: for every increase in 1 unit of <span class="math inline">\(\ln(x)\)</span>, <span class="math inline">\(E[Y]\)</span> increases by <span class="math inline">\(\beta_1\)</span>. Which isn’t a very meaningful statement. Instead, consider <span class="math display">\[E[Y| \ln(2x)] - E[Y|\ln(x)] = \beta_1 \ln(2).\]</span> Which can be interpreted as a doubling of <span class="math inline">\(x\)</span> gives an additive increase of E[Y] of <span class="math inline">\(\beta_1 \ln(2)\)</span> units.</p>
<p><strong>Example 2:</strong> Transforming <span class="math inline">\(Y\)</span>: <span class="math inline">\(Y' = \ln(Y)\)</span> <span class="math display">\[E[\ln(Y)] = \beta_0  + \beta_1 x\]</span> Note also that <span class="math display">\[ E[\ln(Y)] = median(\ln(Y))\]</span> because the distribution of <span class="math inline">\(\ln(Y)\)</span> is symmetric around the regression line.</p>
<p><span class="math display">\[\begin{eqnarray*}
median(\ln(Y)) = \beta_0 + \beta_1 x\\
median(Y) = e^{\beta_0} e^{\beta_1 x}\\
\frac{median(Y| x+1)}{median(Y| x)} = e^{\beta_1}\\
\end{eqnarray*}\]</span>
An increase in 1 unit of x is associated with a multiplicative change of <span class="math inline">\(e^{\beta_1}\)</span> in median(<span class="math inline">\(Y\)</span>). Important to keep in mind that
<span class="math display">\[\begin{eqnarray*}
E[\ln(Y)] \ne \ln(E[Y])\\
median(\ln(Y)) = \ln(median(Y))
\end{eqnarray*}\]</span></p>
<p><strong>Example 3:</strong> Transforming <span class="math inline">\(x\)</span> and <span class="math inline">\(Y\)</span>: <span class="math inline">\(x' = \ln(x)\)</span> and <span class="math inline">\(Y' = \ln(Y)\)</span> <span class="math display">\[E[\ln(Y)] = \beta_0  + \beta_1 \ln(x)\]</span>
<span class="math display">\[\begin{eqnarray*}
\frac{median(Y|2x)}{median(Y|x)} &amp;=&amp; \frac{e^{\beta_0 + \beta_1 \ln(2x)}}{e^{\beta_0 + \beta_1 \ln(x)}}\\
&amp;=&amp; e^{\beta_1 (\ln(2x) - \ln(x))}\\
&amp;=&amp; e^{\beta_1 \ln(2)} = 2^{\beta_1}
\end{eqnarray*}\]</span>
A doubling of <span class="math inline">\(x\)</span> is associated with a multiplicative change of <span class="math inline">\(2^{\beta_1}\)</span> in median of Y.</p>
<p>Note that the model regressing GDP on % urban used a log transformation on GDP (the response, or Y variable). As such we know that:</p>
<p><span class="math display">\[\begin{eqnarray*}
\widehat{\ln(Y)} &amp;=&amp; \mbox{median}(\ln(Y)) = b_0 + b_1 \cdot x\\
\mbox{median}(Y) &amp;=&amp; \exp(b_0 + b_1 \cdot x)
\end{eqnarray*}\]</span></p>
<p>By using the coefficients which are output from the linear model regressing <code>ln_gdp</code> on <code>urban</code>, we can find a model which predicts the <strong>median</strong> <code>gdp</code> (not transformed!) as a function of <code>urban</code>.</p>
<div class="sourceCode" id="cb290"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">GDP</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">ln_gdp</span> <span class="op">~</span> <span class="va">urban</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/generics/man/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)   6.11     0.202        30.3 1.18e-74
## 2 urban         0.0425   0.00308      13.8 2.29e-30</code></pre>
<p><span class="math display">\[\begin{eqnarray*}
\mbox{median}(\verb;gdp;) &amp;=&amp; \exp(6.11 +  0.0425 \cdot \verb;urban;)
\end{eqnarray*}\]</span></p>
<div class="sourceCode" id="cb292"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">GDP</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">urban</span>, y <span class="op">=</span> <span class="va">gdp</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_path.html">geom_line</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">urban</span>, y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">exp</a></span><span class="op">(</span><span class="fl">6.11</span> <span class="op">+</span> <span class="fl">0.0425</span><span class="op">*</span><span class="va">urban</span><span class="op">)</span><span class="op">)</span>, color <span class="op">=</span> <span class="st">"blue"</span><span class="op">)</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-13"></span>
<img src="02b-diag1_files/figure-html/unnamed-chunk-13-1.png" alt="Scatter plot of % urban on the x-axis and GDP on the y-axis, representing a non-linear relationship.  An exponential curve is overlaid to represent the median GDP as a function of % urban." width="672"><p class="caption">
Figure 6.4: The blue exponential line represents the median GDP at a particular value of % urban.
</p>
</div>
</div>
</div>
<div id="reflection-questions-3" class="section level2" number="6.5">
<h2>
<span class="header-section-number">6.5</span> <i class="fas fa-lightbulb" target="_blank"></i> Reflection Questions<a class="anchor" aria-label="anchor" href="#reflection-questions-3"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: decimal">
<li>How do we know if the model conditions hold?</li>
<li>What do we do if the model conditions don’t hold?</li>
<li>With a log transformation, how is the slope coefficient interpreted?</li>
<li>What happens if we want to add lots of explanatory variables to the model?</li>
<li>How would we add a quadratic term?</li>
</ol>
</div>
<div id="ethics-considerations-2" class="section level2" number="6.6">
<h2>
<span class="header-section-number">6.6</span> <i class="fas fa-balance-scale"></i> Ethics Considerations<a class="anchor" aria-label="anchor" href="#ethics-considerations-2"><i class="fas fa-link"></i></a>
</h2>
<ol style="list-style-type: decimal">
<li>The GDP model has country as observational unit (192 countries). A quick Google shows that the UN currently defines 193 countries Leaving aside that we might be one short, do the technical conditions need apply if we have the entire population? Can we think of the country data in 2020 as representative of any other (unknown?) population?<br>
</li>
<li>The <code>mammals</code> dataset was collected in 1976. Are there reasons why a 50 year old dataset might not represent an accurate model of the population today?</li>
</ol>
</div>
<div id="r-slr-inference" class="section level2" number="6.7">
<h2>
<span class="header-section-number">6.7</span> R: SLR Inference<a class="anchor" aria-label="anchor" href="#r-slr-inference"><i class="fas fa-link"></i></a>
</h2>
<p>Consider the <code>mammals</code> dataset in the <strong>MASS</strong> package (be careful with the <strong>MASS</strong>, it will overwrite the <strong>dplyr</strong> functions <code>filter</code> and <code>select</code>) representing the average brain (g) and body (kg) weights for 62 species of land mammals<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;Allison, T. and Cicchetti, D. V. (1976) Sleep in mammals: ecological and constitutional correlates. Science 194, 732–734.&lt;/p&gt;"><sup>3</sup></a>.</p>
<p>From a first glance at the linear model, it doesn’t seem like there is really any linear relationship at all! And certainly the residuals don’t look like what we’d hoped for the LINE technical conditions.</p>
<div class="sourceCode" id="cb293"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.stats.ox.ac.uk/pub/MASS4/">MASS</a></span><span class="op">)</span>  <span class="co"># be careful with MASS, it messes up filter and select</span>
<span class="fu"><a href="https://rdrr.io/r/utils/data.html">data</a></span><span class="op">(</span><span class="va">mammals</span><span class="op">)</span>

<span class="va">mammals</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">body</span>, y <span class="op">=</span> <span class="va">brain</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="02b-diag1_files/figure-html/unnamed-chunk-14-1.png" width="672" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb294"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mammals</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">brain</span> <span class="op">~</span> <span class="va">body</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/generics/man/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="02b-diag1_files/figure-html/unnamed-chunk-14-2.png" width="672" style="display: block; margin: auto;"></div>
<p>Let’s try some log transformations (square root transformations might also make sense).</p>
<div class="sourceCode" id="cb295"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mammals</span> <span class="op">&lt;-</span> <span class="va">mammals</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate.html">mutate</a></span><span class="op">(</span>ln_body <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">body</span><span class="op">)</span>,
         ln_brain <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">brain</span><span class="op">)</span><span class="op">)</span>

<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span>  <span class="co"># to get the plots next to one another</span>

<span class="va">p1</span> <span class="op">&lt;-</span> <span class="va">mammals</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ln_body</span>, y <span class="op">=</span> <span class="va">brain</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="va">p2</span> <span class="op">&lt;-</span> <span class="va">mammals</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">brain</span> <span class="op">~</span> <span class="va">ln_body</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/generics/man/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>

<span class="va">p1</span> <span class="op">+</span> <span class="va">p2</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-15"></span>
<img src="02b-diag1_files/figure-html/unnamed-chunk-15-1.png" alt="Taking the natural log of the body weight doesn't seem to create a model with a linear shape." width="672"><p class="caption">
Figure 6.5: Taking the natural log of the body weight doesn’t seem to create a model with a linear shape.
</p>
</div>
<div class="sourceCode" id="cb296"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p3</span> <span class="op">&lt;-</span> <span class="va">mammals</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">body</span>, y <span class="op">=</span> <span class="va">ln_brain</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="va">p4</span> <span class="op">&lt;-</span> <span class="va">mammals</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">ln_brain</span> <span class="op">~</span> <span class="va">body</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/generics/man/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>

<span class="va">p3</span> <span class="op">+</span> <span class="va">p4</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-16"></span>
<img src="02b-diag1_files/figure-html/unnamed-chunk-16-1.png" alt="Taking the natural log of the brain weight also doesn't seem to create a model with a linear shape." width="672"><p class="caption">
Figure 6.6: Taking the natural log of the brain weight also doesn’t seem to create a model with a linear shape.
</p>
</div>
<div class="sourceCode" id="cb297"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">p5</span> <span class="op">&lt;-</span> <span class="va">mammals</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">ln_body</span>, y <span class="op">=</span> <span class="va">ln_brain</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_smooth.html">geom_smooth</a></span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>

<span class="va">p6</span> <span class="op">&lt;-</span> <span class="va">mammals</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">ln_brain</span> <span class="op">~</span> <span class="va">ln_body</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/generics/man/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu"><a href="https://rdrr.io/pkg/ggplot2/man/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span>

<span class="va">p5</span> <span class="op">+</span> <span class="va">p6</span></code></pre></div>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-17"></span>
<img src="02b-diag1_files/figure-html/unnamed-chunk-17-1.png" alt="Taking the natural log of both the brain and the body weight does seem to create a model with a linear shape!" width="672"><p class="caption">
Figure 6.7: Taking the natural log of both the brain and the body weight does seem to create a model with a linear shape!
</p>
</div>

</div>
</div>

  <div class="chapter-nav">
<div class="prev"><a href="infslr.html"><span class="header-section-number">5</span> Inference on SLR Parameters</a></div>
<div class="next"><a href="simult.html"><span class="header-section-number">7</span> Simultaneous Inference</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#diag1"><span class="header-section-number">6</span> Diagnostic Measures I</a></li>
<li>
<a class="nav-link" href="#model-conditions"><span class="header-section-number">6.1</span> Model Conditions</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#residuals"><span class="header-section-number">6.1.1</span> Residuals</a></li></ul>
</li>
<li><a class="nav-link" href="#diagnostic-plots-of-residuals"><span class="header-section-number">6.2</span> Diagnostic Plots of Residuals</a></li>
<li><a class="nav-link" href="#transformations"><span class="header-section-number">6.3</span> Transformations</a></li>
<li>
<a class="nav-link" href="#correcting-condition-violations"><span class="header-section-number">6.4</span> Correcting Condition Violations</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#gdp-example"><span class="header-section-number">6.4.1</span> GDP Example</a></li>
<li><a class="nav-link" href="#interpreting-regression-coefficients">Interpreting Regression Coefficients</a></li>
</ul>
</li>
<li><a class="nav-link" href="#reflection-questions-3"><span class="header-section-number">6.5</span>  Reflection Questions</a></li>
<li><a class="nav-link" href="#ethics-considerations-2"><span class="header-section-number">6.6</span>  Ethics Considerations</a></li>
<li><a class="nav-link" href="#r-slr-inference"><span class="header-section-number">6.7</span> R: SLR Inference</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/hardin47/website/blob/master/02b-diag1.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/hardin47/website/edit/master/02b-diag1.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Linear Models</strong>" was written by Jo Hardin. It was last built on 2022-02-27.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
