<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 10 Modeling as a Process6 | Linear Models</title>
<meta name="author" content="Jo Hardin">
<meta name="description" content="10.1 Comparing Models So many models, so little time. Understanding how to interpret a multiple linear regression model is only half of the modeling process. In most real-life situations, there...">
<meta name="generator" content="bookdown 0.24 with bs4_book()">
<meta property="og:title" content="Chapter 10 Modeling as a Process6 | Linear Models">
<meta property="og:type" content="book">
<meta property="og:description" content="10.1 Comparing Models So many models, so little time. Understanding how to interpret a multiple linear regression model is only half of the modeling process. In most real-life situations, there...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Chapter 10 Modeling as a Process6 | Linear Models">
<meta name="twitter:description" content="10.1 Comparing Models So many models, so little time. Understanding how to interpret a multiple linear regression model is only half of the modeling process. In most real-life situations, there...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.11/header-attrs.js"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.3.1/transition.js"></script><script src="libs/bs3compat-0.3.1/tabs.js"></script><script src="libs/bs3compat-0.3.1/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script type="text/x-mathjax-config">
    const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
    for (let popover of popovers){
      const div = document.createElement('div');
      div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
      div.innerHTML = popover.getAttribute('data-content');
      
      // Will this work with TeX on its own line?
      var has_math = div.querySelector("span.math");
      if (has_math) {
        document.body.appendChild(div);
      	MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
      	MathJax.Hub.Queue(function(){
          popover.setAttribute('data-content', div.innerHTML);
      	})
      }
    }
    </script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Linear Models</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Class Information</a></li>
<li><a class="" href="intro.html"><span class="header-section-number">1</span> Introduction</a></li>
<li><a class="" href="wrang.html"><span class="header-section-number">2</span> Data Wrangling</a></li>
<li><a class="" href="viz.html"><span class="header-section-number">3</span> Visualization</a></li>
<li><a class="" href="slr.html"><span class="header-section-number">4</span> Simple Linear Regression</a></li>
<li><a class="" href="infslr.html"><span class="header-section-number">5</span> Inference on SLR Parameters</a></li>
<li><a class="" href="diag1.html"><span class="header-section-number">6</span> Diagnostic Measures I</a></li>
<li><a class="" href="simult.html"><span class="header-section-number">7</span> Simultaneous Inference</a></li>
<li><a class="" href="la.html"><span class="header-section-number">8</span> Regression using Matrices</a></li>
<li><a class="" href="mlr.html"><span class="header-section-number">9</span> Multiple Linear Regression</a></li>
<li><a class="active" href="process.html"><span class="header-section-number">10</span> Modeling as a Process6</a></li>
<li><a class="" href="build.html"><span class="header-section-number">11</span> Model Building</a></li>
<li><a class="" href="analysis-of-variance-anova.html"><span class="header-section-number">12</span> Analysis of variance (ANOVA)</a></li>
<li><a class="" href="diag2.html"><span class="header-section-number">13</span> Diagnostics II</a></li>
<li><a class="" href="shrink.html"><span class="header-section-number">14</span> Shrinkage Methods</a></li>
<li><a class="" href="smooth.html"><span class="header-section-number">15</span> Smoothing Methods</a></li>
<li><a class="" href="anova.html"><span class="header-section-number">16</span> ANOVA</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/hardin47/website">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="process" class="section level1" number="10">
<h1>
<span class="header-section-number">10</span> Modeling as a Process<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;Thanks to Mine Centinkaya-Rundel for the majority of the content in this chapter. Mine’s course is at &lt;a href="https://mine-cr.com/teaching/sta210/" class="uri"&gt;https://mine-cr.com/teaching/sta210/&lt;/a&gt;.&lt;/p&gt;'><sup>6</sup></a><a class="anchor" aria-label="anchor" href="#process"><i class="fas fa-link"></i></a>
</h1>
<div id="comparing-models" class="section level2" number="10.1">
<h2>
<span class="header-section-number">10.1</span> Comparing Models<a class="anchor" aria-label="anchor" href="#comparing-models"><i class="fas fa-link"></i></a>
</h2>
<p>So many models, so little time. Understanding how to interpret a multiple linear regression model is only half of the modeling process. In most real-life situations, there are many variables which can be used to predict or describe the response variable at hand. But how to choose which combination or subset of variables is best?</p>
<p>Here, we’ll walk through many of the big ideas surrounding the modeling building process. In the next chapter we will consider the technical ideas behind statistical inference for modeling building. But even when using formal inference, the ideas here should always inform the larger process and analysis conclusions.</p>
<p><a href="https://en.wikipedia.org/wiki/Leo_Breiman">Leo Breiman</a> was among the giants in machine learning who helped to bridge ideas in statistics and computer science. Trained as a statistician, he spent his career at the University of California, Berkeley where he developed Classification and Regression Trees (CART), bagging, and Random Forests.</p>
<p>Among his important insights was an idea that there are <a href="https://projecteuclid.org/journals/statistical-science/volume-16/issue-3/Statistical-Modeling--The-Two-Cultures-with-comments-and-a/10.1214/ss/1009213726.full">two cultures</a> which can motivate (linear) modeling:</p>
<blockquote>
<p>Think of the data as being generated by a black box in which a vector of
input variables x (independent variables) go in one side, and on the other side the response variables y come out. Inside the black box, nature functions to associate the predictor variables with the response variables.</p>
</blockquote>
<blockquote>
<ol style="list-style-type: decimal">
<li>Data Modeling: The analysis in this culture starts with assuming a stochastic data model for the inside of the black box…The values of the parameters are estimated from the data and the model then used for information and/or prediction</li>
</ol>
</blockquote>
<blockquote>
<ol start="2" style="list-style-type: decimal">
<li>Algorithmic Modeling: The analysis in this culture considers the inside of the box complex and unknown. [The] approach is to find a function f(x) — an algorithm that operates on x to predict the responses y.</li>
</ol>
</blockquote>
<p>Here in Chapter <a href="process.html#process">10</a>, the focus will be on algorithmic modeling and developing models which are optimally predictive of the response variable at hand.</p>
<div id="worth-a-comment" class="section level4 unnumbered">
<h4>Worth a comment<a class="anchor" aria-label="anchor" href="#worth-a-comment"><i class="fas fa-link"></i></a>
</h4>
<p>Notice that the R code has gotten more interesting now. How fun!! The R code will help the process! The R package <strong>tidymodels</strong> includes tools to facilitate, in particular, feature engineering and cross validation.</p>
</div>
</div>
<div id="feature-engineering" class="section level2" number="10.2">
<h2>
<span class="header-section-number">10.2</span> Feature Engineering<a class="anchor" aria-label="anchor" href="#feature-engineering"><i class="fas fa-link"></i></a>
</h2>
<p>For the example used to consider feature engineering, the data come from <a href="https://data.world/anujjain7/the-office-imdb-ratings-dataset">data.world</a>, by way of <a href="https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-03-17/readme.md">TidyTuesday</a>. They now exist in the <a href="https://bradlindblad.github.io/schrute/"><strong>schrute</strong> R package</a>.</p>
<blockquote>
<p>Can the IMDB rating (<code>imdb_rating</code>) for The Office be predicted from the other variables in the dataset? Which model is best?</p>
</blockquote>
<p>Instead of jumping into the predictions immediately, let’s look at the data itself. What wrangling can we do to the data in order to take advantage of all the information in the variables? We’d also like to make the model accurate and easy to communicate.</p>
<pre><code>## # A tibble: 188 × 6
##    season episode title             imdb_rating total_votes air_date  
##     &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;                   &lt;dbl&gt;       &lt;dbl&gt; &lt;date&gt;    
##  1      1       1 Pilot                     7.6        3706 2005-03-24
##  2      1       2 Diversity Day             8.3        3566 2005-03-29
##  3      1       3 Health Care               7.9        2983 2005-04-05
##  4      1       4 The Alliance              8.1        2886 2005-04-12
##  5      1       5 Basketball                8.4        3179 2005-04-19
##  6      1       6 Hot Girl                  7.8        2852 2005-04-26
##  7      2       1 The Dundies               8.7        3213 2005-09-20
##  8      2       2 Sexual Harassment         8.2        2736 2005-09-27
##  9      2       3 Office Olympics           8.4        2742 2005-10-04
## 10      2       4 The Fire                  8.4        2713 2005-10-11
## # … with 178 more rows</code></pre>
<div id="imdb-ratings" class="section level4 unnumbered">
<h4>IMDB ratings<a class="anchor" aria-label="anchor" href="#imdb-ratings"><i class="fas fa-link"></i></a>
</h4>
<div class="inline-figure"><img src="04a-process_files/figure-html/unnamed-chunk-3-1.png" width="480" style="display: block; margin: auto;"></div>
</div>
<div id="imdb-ratings-vs.-number-of-votes" class="section level4 unnumbered">
<h4>IMDB ratings vs. number of votes<a class="anchor" aria-label="anchor" href="#imdb-ratings-vs.-number-of-votes"><i class="fas fa-link"></i></a>
</h4>
<div class="inline-figure"><img src="04a-process_files/figure-html/unnamed-chunk-4-1.png" width="480" style="display: block; margin: auto;"></div>
</div>
<div id="outliers" class="section level4 unnumbered">
<h4>Outliers?<a class="anchor" aria-label="anchor" href="#outliers"><i class="fas fa-link"></i></a>
</h4>
<div class="inline-figure"><img src="04a-process_files/figure-html/unnamed-chunk-5-1.png" width="480" style="display: block; margin: auto;"></div>
</div>
<div id="aside" class="section level4 unnumbered">
<h4>Aside…<a class="anchor" aria-label="anchor" href="#aside"><i class="fas fa-link"></i></a>
</h4>
<p>If you like the <a href="https://www.imdb.com/title/tt1031477/">Dinner Party</a> episode, I highly recommend this <a href="https://www.rollingstone.com/tv/tv-features/that-one-night-the-oral-history-of-the-greatest-office-episode-ever-629472/">“oral history” of the episode</a> published on Rolling Stone magazine.</p>
</div>
<div id="rating-vs.-air-date" class="section level4 unnumbered">
<h4>Rating vs. air date<a class="anchor" aria-label="anchor" href="#rating-vs.-air-date"><i class="fas fa-link"></i></a>
</h4>
<div class="inline-figure"><img src="04a-process_files/figure-html/unnamed-chunk-6-1.png" width="480" style="display: block; margin: auto;"></div>
</div>
<div id="imdb-ratings-vs.-seasons" class="section level4 unnumbered">
<h4>IMDB ratings vs. seasons<a class="anchor" aria-label="anchor" href="#imdb-ratings-vs.-seasons"><i class="fas fa-link"></i></a>
</h4>
<div class="inline-figure"><img src="04a-process_files/figure-html/unnamed-chunk-7-1.png" width="480" style="display: block; margin: auto;"></div>
</div>
<div id="building-a-model" class="section level3" number="10.2.1">
<h3>
<span class="header-section-number">10.2.1</span> Building a Model<a class="anchor" aria-label="anchor" href="#building-a-model"><i class="fas fa-link"></i></a>
</h3>
<p>If the idea is to build a model which can predict IMDB ratings, we need to have a way to see how we did (at the end). Indeed, it is important for us to put some data in our pocket (it will be called the “test” data) which doesn’t see any of the modeling process. We’ll use the test data at the end to assess whether or not our predictions are any good.</p>
<div id="train-test" class="section level4 unnumbered">
<h4>Train / test<a class="anchor" aria-label="anchor" href="#train-test"><i class="fas fa-link"></i></a>
</h4>
<p><strong>Step 1:</strong> Create an initial split:</p>
<div class="sourceCode" id="cb378"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">123</span><span class="op">)</span>
<span class="va">office_split</span> <span class="op">&lt;-</span> <span class="fu">initial_split</span><span class="op">(</span><span class="va">office_ratings</span><span class="op">)</span> <span class="co"># prop = 3/4 by default</span></code></pre></div>
<p><strong>Step 2:</strong> Save training data</p>
<div class="sourceCode" id="cb379"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_train</span> <span class="op">&lt;-</span> <span class="fu">training</span><span class="op">(</span><span class="va">office_split</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">office_train</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 141   6</code></pre>
<p><strong>Step 3:</strong> Save testing data</p>
<div class="sourceCode" id="cb381"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_test</span>  <span class="op">&lt;-</span> <span class="fu">testing</span><span class="op">(</span><span class="va">office_split</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">office_test</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 47  6</code></pre>
</div>
<div id="using-the-training-data" class="section level4 unnumbered">
<h4>Using the training data<a class="anchor" aria-label="anchor" href="#using-the-training-data"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb383"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_train</span></code></pre></div>
<pre><code>## # A tibble: 141 × 6
##    season episode title               imdb_rating total_votes air_date  
##     &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;                     &lt;dbl&gt;       &lt;dbl&gt; &lt;date&gt;    
##  1      8      18 Last Day in Florida         7.8        1429 2012-03-08
##  2      9      14 Vandalism                   7.6        1402 2013-01-31
##  3      2       8 Performance Review          8.2        2416 2005-11-15
##  4      9       5 Here Comes Treble           7.1        1515 2012-10-25
##  5      3      22 Beach Games                 9.1        2783 2007-05-10
##  6      7       1 Nepotism                    8.4        1897 2010-09-23
##  7      3      15 Phyllis' Wedding            8.3        2283 2007-02-08
##  8      9      21 Livin' the Dream            8.9        2041 2013-05-02
##  9      9      18 Promos                      8          1445 2013-04-04
## 10      8      12 Pool Party                  8          1612 2012-01-19
## # … with 131 more rows</code></pre>
</div>
</div>
<div id="feature-engineering-1" class="section level3" number="10.2.2">
<h3>
<span class="header-section-number">10.2.2</span> Feature engineering<a class="anchor" aria-label="anchor" href="#feature-engineering-1"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li><p>We prefer simple models when possible, but <strong>parsimony</strong> does not mean sacrificing accuracy (or predictive performance) in the interest of simplicity.</p></li>
<li><p>Variables that go into the model and how they are represented are just as critical to success of the model.</p></li>
<li><p><strong>Feature engineering</strong> allows us to get creative with our predictors in an effort to make them more useful for our model (to increase its predictive performance).</p></li>
</ul>
<div id="feature-engineering-with-dplyr" class="section level4 unnumbered">
<h4>Feature engineering with dplyr<a class="anchor" aria-label="anchor" href="#feature-engineering-with-dplyr"><i class="fas fa-link"></i></a>
</h4>
<p>We can use the <strong>dplyr</strong> (in <strong>tidyverse</strong>) and, for example, the <code><a href="https://rdrr.io/pkg/dplyr/man/mutate.html">mutate()</a></code> function to create new variables to use in the models.</p>
<div class="sourceCode" id="cb385"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_train</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/mutate.html">mutate</a></span><span class="op">(</span>
    season <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/forcats/man/as_factor.html">as_factor</a></span><span class="op">(</span><span class="va">season</span><span class="op">)</span>,
    month <span class="op">=</span> <span class="fu">lubridate</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lubridate/man/month.html">month</a></span><span class="op">(</span><span class="va">air_date</span><span class="op">)</span>,
    wday <span class="op">=</span> <span class="fu">lubridate</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/lubridate/man/day.html">wday</a></span><span class="op">(</span><span class="va">air_date</span><span class="op">)</span>
  <span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 141 × 8
##   season episode title            imdb_rating total_votes air_date   month  wday
##   &lt;fct&gt;    &lt;dbl&gt; &lt;chr&gt;                  &lt;dbl&gt;       &lt;dbl&gt; &lt;date&gt;     &lt;dbl&gt; &lt;dbl&gt;
## 1 8           18 Last Day in Flo…         7.8        1429 2012-03-08     3     5
## 2 9           14 Vandalism                7.6        1402 2013-01-31     1     5
## 3 2            8 Performance Rev…         8.2        2416 2005-11-15    11     3
## 4 9            5 Here Comes Treb…         7.1        1515 2012-10-25    10     5
## 5 3           22 Beach Games              9.1        2783 2007-05-10     5     5
## 6 7            1 Nepotism                 8.4        1897 2010-09-23     9     5
## # … with 135 more rows</code></pre>
<blockquote>
<p>Can you identify any potential problems with this approach?</p>
</blockquote>
<p>One of the problems is that with the <code><a href="https://rdrr.io/pkg/dplyr/man/mutate.html">mutate()</a></code> approach the test and training data get formatted separately so there might be inconsistencies when the test data are predicted at the end.</p>
</div>
</div>
<div id="modeling-workflow" class="section level3 unnumbered">
<h3>Modeling workflow<a class="anchor" aria-label="anchor" href="#modeling-workflow"><i class="fas fa-link"></i></a>
</h3>
<p>Ideally, the feature engineering happens as part of the workflow. That is, part of the modeling process. That way, when the training data is used to fit the model, feature engineering happens. When the test data is used to come up with predictions, feature engineering also happens.</p>
<ul>
<li><p>Create a <strong>recipe</strong> for feature engineering steps to be applied to the training data</p></li>
<li><p>Fit the model to the training data after these steps have been applied</p></li>
<li><p>Using the model estimates from the training data, predict outcomes for the test data</p></li>
<li><p>Evaluate the performance of the model on the test data</p></li>
</ul>
</div>
<div id="specifying-a-model" class="section level3" number="10.2.3">
<h3>
<span class="header-section-number">10.2.3</span> Specifying a model<a class="anchor" aria-label="anchor" href="#specifying-a-model"><i class="fas fa-link"></i></a>
</h3>
<p>Instead of using the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> command, we’re going to use the <strong>tidymodels</strong> framework to specify a model. In Math 158 we will <em>always</em> use “lm,” but if you take other applied statistics classes, you’ll use different model specifications with the same feature engineering and modeling fitting steps.</p>
<div class="sourceCode" id="cb387"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_spec</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">set_engine</span><span class="op">(</span><span class="st">"lm"</span><span class="op">)</span>

<span class="va">office_spec</span></code></pre></div>
<pre><code>## Linear Regression Model Specification (regression)
## 
## Computational engine: lm</code></pre>
</div>
<div id="building-a-recipe" class="section level3" number="10.2.4">
<h3>
<span class="header-section-number">10.2.4</span> Building a recipe<a class="anchor" aria-label="anchor" href="#building-a-recipe"><i class="fas fa-link"></i></a>
</h3>
<p>The steps in building a recipe are done sequentially so that the format of each variable is as desired for the model. As seen in Section (@ref{sec:wflow}), the recipe steps can happen in sequence using the pipe (<code>%&gt;%</code>) function.</p>
<p>However, when you work with a single pipeline, the recipe effects on the data aren’t seen, which can be unsettling. You can look at what will happen when you ultimately apply the recipe to your data by using the functions <code>prep()</code> and <code>bake()</code>.</p>
<p><strong>Note:</strong> Using <code>prep()</code> and <code>bake()</code> are shown here for demonstrative purposes. They do not need to be a part of your pipeline. I do find them assuring, however, so that I can see the effects of the recipe steps as the recipe is built.</p>
<div id="initiate-a-recipe" class="section level4 unnumbered">
<h4>Initiate a recipe<a class="anchor" aria-label="anchor" href="#initiate-a-recipe"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb389"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec</span> <span class="op">&lt;-</span> <span class="fu">recipe</span><span class="op">(</span>
  <span class="va">imdb_rating</span> <span class="op">~</span> <span class="va">.</span>,    <span class="co"># formula</span>
  data <span class="op">=</span> <span class="va">office_train</span> <span class="co"># data for cataloging names and types of variables</span>
  <span class="op">)</span>

<span class="va">office_rec</span></code></pre></div>
<pre><code>## Data Recipe
## 
## Inputs:
## 
##       role #variables
##    outcome          1
##  predictor          5</code></pre>
</div>
<div id="step-1-alter-roles" class="section level4 unnumbered">
<h4>Step 1: Alter roles<a class="anchor" aria-label="anchor" href="#step-1-alter-roles"><i class="fas fa-link"></i></a>
</h4>
<p><code>title</code> isn’t a predictor, but we might want to keep it around as an ID.</p>
<blockquote>
<p><code>update_role()</code> alters an existing role in the recipe or assigns an initial role to variables that do not yet have a declared role.</p>
</blockquote>
<div class="sourceCode" id="cb391"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec</span> <span class="op">&lt;-</span> <span class="va">office_rec</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">update_role</span><span class="op">(</span><span class="va">title</span>, new_role <span class="op">=</span> <span class="st">"ID"</span><span class="op">)</span>

<span class="va">office_rec</span></code></pre></div>
<pre><code>## Data Recipe
## 
## Inputs:
## 
##       role #variables
##         ID          1
##    outcome          1
##  predictor          4</code></pre>
<div class="sourceCode" id="cb393"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec_trained</span> <span class="op">&lt;-</span> <span class="fu">prep</span><span class="op">(</span><span class="va">office_rec</span><span class="op">)</span>

<span class="fu">bake</span><span class="op">(</span><span class="va">office_rec_trained</span>, <span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="va">glimpse</span></code></pre></div>
<pre><code>## Rows: 141
## Columns: 6
## $ season      &lt;dbl&gt; 8, 9, 2, 9, 3, 7, 3, 9, 9, 8, 5, 5, 9, 6, 7, 6, 5, 2, 2, 9…
## $ episode     &lt;dbl&gt; 18, 14, 8, 5, 22, 1, 15, 21, 18, 12, 25, 26, 12, 1, 20, 8,…
## $ title       &lt;fct&gt; "Last Day in Florida", "Vandalism", "Performance Review", …
## $ total_votes &lt;dbl&gt; 1429, 1402, 2416, 1515, 2783, 1897, 2283, 2041, 1445, 1612…
## $ air_date    &lt;date&gt; 2012-03-08, 2013-01-31, 2005-11-15, 2012-10-25, 2007-05-1…
## $ imdb_rating &lt;dbl&gt; 7.8, 7.6, 8.2, 7.1, 9.1, 8.4, 8.3, 8.9, 8.0, 8.0, 8.7, 8.9…</code></pre>
</div>
<div id="step-2-add-features" class="section level4 unnumbered">
<h4>Step 2: Add features<a class="anchor" aria-label="anchor" href="#step-2-add-features"><i class="fas fa-link"></i></a>
</h4>
<p>New features for day of week and month. Here, the <code>air_date</code> variable is being specified to keep separate information on both the day of week and the month information.</p>
<blockquote>
<p><code>step_date()</code> creates a specification of a recipe step that will convert date data into one or more factor or numeric variables.</p>
</blockquote>
<div class="sourceCode" id="cb395"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec</span> <span class="op">&lt;-</span> <span class="va">office_rec</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_date</span><span class="op">(</span><span class="va">air_date</span>, features <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"dow"</span>, <span class="st">"month"</span><span class="op">)</span><span class="op">)</span>

<span class="va">office_rec</span></code></pre></div>
<pre><code>## Data Recipe
## 
## Inputs:
## 
##       role #variables
##         ID          1
##    outcome          1
##  predictor          4
## 
## Operations:
## 
## Date features from air_date</code></pre>
<div class="sourceCode" id="cb397"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec_trained</span> <span class="op">&lt;-</span> <span class="fu">prep</span><span class="op">(</span><span class="va">office_rec</span><span class="op">)</span>

<span class="fu">bake</span><span class="op">(</span><span class="va">office_rec_trained</span>, <span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="va">glimpse</span></code></pre></div>
<pre><code>## Rows: 141
## Columns: 8
## $ season         &lt;dbl&gt; 8, 9, 2, 9, 3, 7, 3, 9, 9, 8, 5, 5, 9, 6, 7, 6, 5, 2, 2…
## $ episode        &lt;dbl&gt; 18, 14, 8, 5, 22, 1, 15, 21, 18, 12, 25, 26, 12, 1, 20,…
## $ title          &lt;fct&gt; "Last Day in Florida", "Vandalism", "Performance Review…
## $ total_votes    &lt;dbl&gt; 1429, 1402, 2416, 1515, 2783, 1897, 2283, 2041, 1445, 1…
## $ air_date       &lt;date&gt; 2012-03-08, 2013-01-31, 2005-11-15, 2012-10-25, 2007-0…
## $ imdb_rating    &lt;dbl&gt; 7.8, 7.6, 8.2, 7.1, 9.1, 8.4, 8.3, 8.9, 8.0, 8.0, 8.7, …
## $ air_date_dow   &lt;fct&gt; Thu, Thu, Tue, Thu, Thu, Thu, Thu, Thu, Thu, Thu, Thu, …
## $ air_date_month &lt;fct&gt; Mar, Jan, Nov, Oct, May, Sep, Feb, May, Apr, Jan, May, …</code></pre>
</div>
<div id="step-3-add-more-features" class="section level4 unnumbered">
<h4>Step 3: Add more features<a class="anchor" aria-label="anchor" href="#step-3-add-more-features"><i class="fas fa-link"></i></a>
</h4>
<p>Identify holidays in <code>air_date</code>, then remove <code>air_date</code>.</p>
<blockquote>
<p><code>step_holiday()</code> creates a specification of a recipe step that will convert date data into one or more binary indicator variables for common holidays.</p>
</blockquote>
<div class="sourceCode" id="cb399"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec</span> <span class="op">&lt;-</span> <span class="va">office_rec</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_holiday</span><span class="op">(</span>
    <span class="va">air_date</span>, 
    holidays <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"USThanksgivingDay"</span>, <span class="st">"USChristmasDay"</span>, <span class="st">"USNewYearsDay"</span>, <span class="st">"USIndependenceDay"</span><span class="op">)</span>, 
    keep_original_cols <span class="op">=</span> <span class="cn">FALSE</span>
  <span class="op">)</span>

<span class="va">office_rec</span></code></pre></div>
<pre><code>## Data Recipe
## 
## Inputs:
## 
##       role #variables
##         ID          1
##    outcome          1
##  predictor          4
## 
## Operations:
## 
## Date features from air_date
## Holiday features from air_date</code></pre>
<div class="sourceCode" id="cb401"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec_trained</span> <span class="op">&lt;-</span> <span class="fu">prep</span><span class="op">(</span><span class="va">office_rec</span><span class="op">)</span>

<span class="fu">bake</span><span class="op">(</span><span class="va">office_rec_trained</span>, <span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="va">glimpse</span></code></pre></div>
<pre><code>## Rows: 141
## Columns: 11
## $ season                     &lt;dbl&gt; 8, 9, 2, 9, 3, 7, 3, 9, 9, 8, 5, 5, 9, 6, 7…
## $ episode                    &lt;dbl&gt; 18, 14, 8, 5, 22, 1, 15, 21, 18, 12, 25, 26…
## $ title                      &lt;fct&gt; "Last Day in Florida", "Vandalism", "Perfor…
## $ total_votes                &lt;dbl&gt; 1429, 1402, 2416, 1515, 2783, 1897, 2283, 2…
## $ imdb_rating                &lt;dbl&gt; 7.8, 7.6, 8.2, 7.1, 9.1, 8.4, 8.3, 8.9, 8.0…
## $ air_date_dow               &lt;fct&gt; Thu, Thu, Tue, Thu, Thu, Thu, Thu, Thu, Thu…
## $ air_date_month             &lt;fct&gt; Mar, Jan, Nov, Oct, May, Sep, Feb, May, Apr…
## $ air_date_USThanksgivingDay &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_USChristmasDay    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_USNewYearsDay     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_USIndependenceDay &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…</code></pre>
</div>
<div id="step-4-convert-numbers-to-factors" class="section level4 unnumbered">
<h4>Step 4: Convert numbers to factors<a class="anchor" aria-label="anchor" href="#step-4-convert-numbers-to-factors"><i class="fas fa-link"></i></a>
</h4>
<p>Convert <code>season</code> to factor.</p>
<blockquote>
<p><code>step_num2factor()</code> will convert one or more numeric vectors to factors (ordered or unordered). This can be useful when categories are encoded as integers.</p>
</blockquote>
<div class="sourceCode" id="cb403"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec</span> <span class="op">&lt;-</span> <span class="va">office_rec</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_num2factor</span><span class="op">(</span><span class="va">season</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">9</span><span class="op">)</span><span class="op">)</span>

<span class="va">office_rec</span></code></pre></div>
<pre><code>## Data Recipe
## 
## Inputs:
## 
##       role #variables
##         ID          1
##    outcome          1
##  predictor          4
## 
## Operations:
## 
## Date features from air_date
## Holiday features from air_date
## Factor variables from season</code></pre>
<div class="sourceCode" id="cb405"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec_trained</span> <span class="op">&lt;-</span> <span class="fu">prep</span><span class="op">(</span><span class="va">office_rec</span><span class="op">)</span>

<span class="fu">bake</span><span class="op">(</span><span class="va">office_rec_trained</span>, <span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="va">glimpse</span></code></pre></div>
<pre><code>## Rows: 141
## Columns: 11
## $ season                     &lt;fct&gt; 8, 9, 2, 9, 3, 7, 3, 9, 9, 8, 5, 5, 9, 6, 7…
## $ episode                    &lt;dbl&gt; 18, 14, 8, 5, 22, 1, 15, 21, 18, 12, 25, 26…
## $ title                      &lt;fct&gt; "Last Day in Florida", "Vandalism", "Perfor…
## $ total_votes                &lt;dbl&gt; 1429, 1402, 2416, 1515, 2783, 1897, 2283, 2…
## $ imdb_rating                &lt;dbl&gt; 7.8, 7.6, 8.2, 7.1, 9.1, 8.4, 8.3, 8.9, 8.0…
## $ air_date_dow               &lt;fct&gt; Thu, Thu, Tue, Thu, Thu, Thu, Thu, Thu, Thu…
## $ air_date_month             &lt;fct&gt; Mar, Jan, Nov, Oct, May, Sep, Feb, May, Apr…
## $ air_date_USThanksgivingDay &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_USChristmasDay    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_USNewYearsDay     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_USIndependenceDay &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…</code></pre>
</div>
<div id="step-5-make-dummy-variables" class="section level4 unnumbered">
<h4>Step 5: Make dummy variables<a class="anchor" aria-label="anchor" href="#step-5-make-dummy-variables"><i class="fas fa-link"></i></a>
</h4>
<p>Convert all nominal (categorical) predictors to factors.</p>
<blockquote>
<p><code>step_dummy()</code> creates a specification of a recipe step that will convert nominal data (e.g. character or factors) into one or more numeric binary model terms for the levels of the original data.</p>
</blockquote>
<div class="sourceCode" id="cb407"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec</span> <span class="op">&lt;-</span> <span class="va">office_rec</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_dummy</span><span class="op">(</span><span class="fu">all_nominal_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span>

<span class="va">office_rec</span></code></pre></div>
<pre><code>## Data Recipe
## 
## Inputs:
## 
##       role #variables
##         ID          1
##    outcome          1
##  predictor          4
## 
## Operations:
## 
## Date features from air_date
## Holiday features from air_date
## Factor variables from season
## Dummy variables from all_nominal_predictors()</code></pre>
<div class="sourceCode" id="cb409"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec_trained</span> <span class="op">&lt;-</span> <span class="fu">prep</span><span class="op">(</span><span class="va">office_rec</span><span class="op">)</span>

<span class="fu">bake</span><span class="op">(</span><span class="va">office_rec_trained</span>, <span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="va">glimpse</span></code></pre></div>
<pre><code>## Rows: 141
## Columns: 33
## $ episode                    &lt;dbl&gt; 18, 14, 8, 5, 22, 1, 15, 21, 18, 12, 25, 26…
## $ title                      &lt;fct&gt; "Last Day in Florida", "Vandalism", "Perfor…
## $ total_votes                &lt;dbl&gt; 1429, 1402, 2416, 1515, 2783, 1897, 2283, 2…
## $ imdb_rating                &lt;dbl&gt; 7.8, 7.6, 8.2, 7.1, 9.1, 8.4, 8.3, 8.9, 8.0…
## $ air_date_USThanksgivingDay &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_USChristmasDay    &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_USNewYearsDay     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_USIndependenceDay &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ season_X2                  &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ season_X3                  &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0…
## $ season_X4                  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ season_X5                  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0…
## $ season_X6                  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0…
## $ season_X7                  &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1…
## $ season_X8                  &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0…
## $ season_X9                  &lt;dbl&gt; 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0…
## $ air_date_dow_Mon           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_dow_Tue           &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_dow_Wed           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_dow_Thu           &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
## $ air_date_dow_Fri           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_dow_Sat           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_month_Feb         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_month_Mar         &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_month_Apr         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1…
## $ air_date_month_May         &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0…
## $ air_date_month_Jun         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_month_Jul         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_month_Aug         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_month_Sep         &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0…
## $ air_date_month_Oct         &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_month_Nov         &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
## $ air_date_month_Dec         &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…</code></pre>
</div>
<div id="step-6-remove-zero-variance-predictors" class="section level4 unnumbered">
<h4>Step 6: Remove zero variance predictors<a class="anchor" aria-label="anchor" href="#step-6-remove-zero-variance-predictors"><i class="fas fa-link"></i></a>
</h4>
<p>Remove all predictors that contain only a single value. “zero variance” means that there is no variability in the entire column, literally every value is the same. Those variables won’t ever help with prediction.</p>
<blockquote>
<p><code>step_zv()</code> creates a specification of a recipe step that will remove variables that contain only a single value.</p>
</blockquote>
<div class="sourceCode" id="cb411"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec</span> <span class="op">&lt;-</span> <span class="va">office_rec</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_zv</span><span class="op">(</span><span class="fu">all_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span>

<span class="va">office_rec</span></code></pre></div>
<pre><code>## Data Recipe
## 
## Inputs:
## 
##       role #variables
##         ID          1
##    outcome          1
##  predictor          4
## 
## Operations:
## 
## Date features from air_date
## Holiday features from air_date
## Factor variables from season
## Dummy variables from all_nominal_predictors()
## Zero variance filter on all_predictors()</code></pre>
<div class="sourceCode" id="cb413"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec_trained</span> <span class="op">&lt;-</span> <span class="fu">prep</span><span class="op">(</span><span class="va">office_rec</span><span class="op">)</span>

<span class="fu">bake</span><span class="op">(</span><span class="va">office_rec_trained</span>, <span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="va">glimpse</span></code></pre></div>
<pre><code>## Rows: 141
## Columns: 22
## $ episode            &lt;dbl&gt; 18, 14, 8, 5, 22, 1, 15, 21, 18, 12, 25, 26, 12, 1,…
## $ title              &lt;fct&gt; "Last Day in Florida", "Vandalism", "Performance Re…
## $ total_votes        &lt;dbl&gt; 1429, 1402, 2416, 1515, 2783, 1897, 2283, 2041, 144…
## $ imdb_rating        &lt;dbl&gt; 7.8, 7.6, 8.2, 7.1, 9.1, 8.4, 8.3, 8.9, 8.0, 8.0, 8…
## $ season_X2          &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ season_X3          &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ season_X4          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ season_X5          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, …
## $ season_X6          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, …
## $ season_X7          &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, …
## $ season_X8          &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, …
## $ season_X9          &lt;dbl&gt; 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, …
## $ air_date_dow_Tue   &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ air_date_dow_Thu   &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
## $ air_date_month_Feb &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ air_date_month_Mar &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ air_date_month_Apr &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, …
## $ air_date_month_May &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, …
## $ air_date_month_Sep &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, …
## $ air_date_month_Oct &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, …
## $ air_date_month_Nov &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, …
## $ air_date_month_Dec &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</code></pre>
</div>
<div id="putting-it-altogether" class="section level4 unnumbered">
<h4>Putting it altogether<a class="anchor" aria-label="anchor" href="#putting-it-altogether"><i class="fas fa-link"></i></a>
</h4>
<p>Turns out that all of the feature engineering steps can do using the pipe function (<code>%&gt;%</code>) to concatenate the functions.</p>
<div class="sourceCode" id="cb415"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec</span> <span class="op">&lt;-</span> <span class="fu">recipe</span><span class="op">(</span><span class="va">imdb_rating</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="co"># make title's role ID</span>
  <span class="fu">update_role</span><span class="op">(</span><span class="va">title</span>, new_role <span class="op">=</span> <span class="st">"ID"</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="co"># extract day of week and month of air_date</span>
  <span class="fu">step_date</span><span class="op">(</span><span class="va">air_date</span>, features <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"dow"</span>, <span class="st">"month"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="co"># identify holidays and add indicators</span>
  <span class="fu">step_holiday</span><span class="op">(</span>
    <span class="va">air_date</span>, 
    holidays <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"USThanksgivingDay"</span>, <span class="st">"USChristmasDay"</span>, <span class="st">"USNewYearsDay"</span>, <span class="st">"USIndependenceDay"</span><span class="op">)</span>, 
    keep_original_cols <span class="op">=</span> <span class="cn">FALSE</span>
  <span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="co"># turn season into factor</span>
  <span class="fu">step_num2factor</span><span class="op">(</span><span class="va">season</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">9</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="co"># make dummy variables</span>
  <span class="fu">step_dummy</span><span class="op">(</span><span class="fu">all_nominal_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="co"># remove zero variance predictors</span>
  <span class="fu">step_zv</span><span class="op">(</span><span class="fu">all_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb416"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec</span></code></pre></div>
<pre><code>## Data Recipe
## 
## Inputs:
## 
##       role #variables
##         ID          1
##    outcome          1
##  predictor          4
## 
## Operations:
## 
## Date features from air_date
## Holiday features from air_date
## Factor variables from season
## Dummy variables from all_nominal_predictors()
## Zero variance filter on all_predictors()</code></pre>
</div>
</div>
<div id="building-workflows" class="section level3" number="10.2.5">
<h3>
<span class="header-section-number">10.2.5</span> Building workflows<a class="anchor" aria-label="anchor" href="#building-workflows"><i class="fas fa-link"></i></a>
</h3>
<p><strong>Workflows</strong> bring together models and recipes so that they can be easily applied to both the training and test data.</p>
<div id="specify-model" class="section level4 unnumbered">
<h4>Specify model<a class="anchor" aria-label="anchor" href="#specify-model"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb418"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_spec</span> <span class="op">&lt;-</span> <span class="fu">linear_reg</span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">set_engine</span><span class="op">(</span><span class="st">"lm"</span><span class="op">)</span>

<span class="va">office_spec</span></code></pre></div>
<pre><code>## Linear Regression Model Specification (regression)
## 
## Computational engine: lm</code></pre>
<p><strong>The workflow:</strong> Notice that the two important parts to the workflows are the model specification and the feature engineering recipe information.</p>
<div class="sourceCode" id="cb420"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_wflow</span> <span class="op">&lt;-</span> <span class="fu">workflow</span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">add_model</span><span class="op">(</span><span class="va">office_spec</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">add_recipe</span><span class="op">(</span><span class="va">office_rec</span><span class="op">)</span>

<span class="va">office_wflow</span></code></pre></div>
<pre><code>## ══ Workflow ════════════════════════════════════════════════════════════════════
## Preprocessor: Recipe
## Model: linear_reg()
## 
## ── Preprocessor ────────────────────────────────────────────────────────────────
## 5 Recipe Steps
## 
## • step_date()
## • step_holiday()
## • step_num2factor()
## • step_dummy()
## • step_zv()
## 
## ── Model ───────────────────────────────────────────────────────────────────────
## Linear Regression Model Specification (regression)
## 
## Computational engine: lm</code></pre>
</div>
<div id="fit-model-to-training-data" class="section level4 unnumbered">
<h4>Fit model to training data<a class="anchor" aria-label="anchor" href="#fit-model-to-training-data"><i class="fas fa-link"></i></a>
</h4>
<p>With the workflow in hand, the model can now be fit to the training data. Although, wow… there are <em>so many predictors</em>!</p>
<div class="sourceCode" id="cb422"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_fit</span> <span class="op">&lt;-</span> <span class="va">office_wflow</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">fit</span><span class="op">(</span>data <span class="op">=</span> <span class="va">office_train</span><span class="op">)</span>

<span class="va">office_fit</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/pkg/generics/man/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fl">21</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 21 × 5
##    term                estimate std.error statistic  p.value
##    &lt;chr&gt;                  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
##  1 (Intercept)         6.40     0.510        12.5   1.51e-23
##  2 episode            -0.00393  0.0171       -0.230 8.18e- 1
##  3 total_votes         0.000375 0.0000414     9.07  2.75e-15
##  4 season_X2           0.811    0.327         2.48  1.44e- 2
##  5 season_X3           1.04     0.343         3.04  2.91e- 3
##  6 season_X4           1.09     0.295         3.70  3.32e- 4
##  7 season_X5           1.08     0.348         3.11  2.34e- 3
##  8 season_X6           1.00     0.367         2.74  7.18e- 3
##  9 season_X7           1.02     0.352         2.89  4.52e- 3
## 10 season_X8           0.497    0.348         1.43  1.55e- 1
## 11 season_X9           0.621    0.345         1.80  7.41e- 2
## 12 air_date_dow_Tue    0.382    0.422         0.904 3.68e- 1
## 13 air_date_dow_Thu    0.284    0.389         0.731 4.66e- 1
## 14 air_date_month_Feb -0.0597   0.132        -0.452 6.52e- 1
## 15 air_date_month_Mar -0.0752   0.156        -0.481 6.31e- 1
## 16 air_date_month_Apr  0.0954   0.177         0.539 5.91e- 1
## 17 air_date_month_May  0.156    0.213         0.734 4.64e- 1
## 18 air_date_month_Sep -0.0776   0.223        -0.348 7.28e- 1
## 19 air_date_month_Oct -0.176    0.174        -1.01  3.13e- 1
## 20 air_date_month_Nov -0.156    0.149        -1.05  2.98e- 1
## 21 air_date_month_Dec  0.170    0.149         1.14  2.55e- 1</code></pre>
</div>
</div>
<div id="evaluate-the-model" class="section level3" number="10.2.6">
<h3>
<span class="header-section-number">10.2.6</span> Evaluate the model<a class="anchor" aria-label="anchor" href="#evaluate-the-model"><i class="fas fa-link"></i></a>
</h3>
<div id="predictions-for-training-data" class="section level4 unnumbered">
<h4>Predictions for training data<a class="anchor" aria-label="anchor" href="#predictions-for-training-data"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb424"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_train_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">office_fit</span>, <span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/bind.html">bind_cols</a></span><span class="op">(</span><span class="va">office_train</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/lm.ridge.html">select</a></span><span class="op">(</span><span class="va">imdb_rating</span>, <span class="va">title</span><span class="op">)</span><span class="op">)</span>

<span class="va">office_train_pred</span></code></pre></div>
<pre><code>## # A tibble: 141 × 3
##    .pred imdb_rating title              
##    &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;              
##  1  7.57         7.8 Last Day in Florida
##  2  7.77         7.6 Vandalism          
##  3  8.31         8.2 Performance Review 
##  4  7.67         7.1 Here Comes Treble  
##  5  8.84         9.1 Beach Games        
##  6  8.33         8.4 Nepotism           
##  7  8.46         8.3 Phyllis' Wedding   
##  8  8.14         8.9 Livin' the Dream   
##  9  7.87         8   Promos             
## 10  7.74         8   Pool Party         
## # … with 131 more rows</code></pre>
</div>
</div>
<div id="r-squared" class="section level3 unnumbered">
<h3>R-squared<a class="anchor" aria-label="anchor" href="#r-squared"><i class="fas fa-link"></i></a>
</h3>
<p>Percentage of variability in the IMDB ratings explained by the model.</p>
<div class="sourceCode" id="cb426"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">rsq</span><span class="op">(</span><span class="va">office_train_pred</span>, truth <span class="op">=</span> <span class="va">imdb_rating</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rsq     standard       0.670</code></pre>
<p>Are models with high or low <span class="math inline">\(R^2\)</span> more preferable?</p>
<div id="rmse" class="section level4 unnumbered">
<h4>RMSE<a class="anchor" aria-label="anchor" href="#rmse"><i class="fas fa-link"></i></a>
</h4>
<p>An alternative model performance statistic: <strong>root mean square error</strong>.</p>
<p><span class="math display">\[RMSE = \sqrt{\frac{\sum_{i = 1}^n (y_i - \hat{y}_i)^2}{n}}\]</span></p>
<ul>
<li>Are models with high or low RMSE are more preferable?</li>
<li>Is this RMSE considered low or high?</li>
</ul>
<div class="sourceCode" id="cb428"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">rmse</span><span class="op">(</span><span class="va">office_train_pred</span>, truth <span class="op">=</span> <span class="va">imdb_rating</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard       0.302</code></pre>
<p>Depends…</p>
<div class="sourceCode" id="cb430"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_train</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">min</a></span><span class="op">(</span><span class="va">imdb_rating</span><span class="op">)</span>, 
            max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">max</a></span><span class="op">(</span><span class="va">imdb_rating</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##     min   max
##   &lt;dbl&gt; &lt;dbl&gt;
## 1   6.7   9.7</code></pre>
<p>But, really…</p>
<p><em>who cares about predictions on <strong>training</strong> data?</em></p>
</div>
</div>
<div id="predictions-for-testing-data" class="section level3 unnumbered">
<h3>Predictions for testing data<a class="anchor" aria-label="anchor" href="#predictions-for-testing-data"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb432"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_test_pred</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">office_fit</span>, <span class="va">office_test</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/bind.html">bind_cols</a></span><span class="op">(</span><span class="va">office_test</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/lm.ridge.html">select</a></span><span class="op">(</span><span class="va">imdb_rating</span>, <span class="va">title</span><span class="op">)</span><span class="op">)</span>

<span class="va">office_test_pred</span></code></pre></div>
<pre><code>## # A tibble: 47 × 3
##    .pred imdb_rating title              
##    &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;              
##  1  8.03         8.3 Diversity Day      
##  2  7.98         7.9 Health Care        
##  3  8.41         8.4 The Fire           
##  4  8.35         8.2 Halloween          
##  5  8.35         8.4 E-Mail Surveillance
##  6  8.68         9   The Injury         
##  7  8.32         7.9 The Carpet         
##  8  8.93         9.3 Casino Night       
##  9  8.80         8.9 Gay Witch Hunt     
## 10  8.37         8.2 Initiation         
## # … with 37 more rows</code></pre>
<div id="evaluate-performance-for-testing-data" class="section level4 unnumbered">
<h4>Evaluate performance for testing data<a class="anchor" aria-label="anchor" href="#evaluate-performance-for-testing-data"><i class="fas fa-link"></i></a>
</h4>
<p><span class="math inline">\(R^2\)</span> of model fit to <strong>testing</strong> data</p>
<div class="sourceCode" id="cb434"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">rsq</span><span class="op">(</span><span class="va">office_test_pred</span>, truth <span class="op">=</span> <span class="va">imdb_rating</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rsq     standard       0.468</code></pre>
<p>RMSE of model fit to <strong>testing</strong> data</p>
<div class="sourceCode" id="cb436"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">rmse</span><span class="op">(</span><span class="va">office_test_pred</span>, truth <span class="op">=</span> <span class="va">imdb_rating</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard       0.411</code></pre>
</div>
<div id="training-vs.-testing" class="section level4 unnumbered">
<h4>Training vs. testing<a class="anchor" aria-label="anchor" href="#training-vs.-testing"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb438"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">rmse_train</span> <span class="op">&lt;-</span> <span class="fu">rmse</span><span class="op">(</span><span class="va">office_train_pred</span>, truth <span class="op">=</span> <span class="va">imdb_rating</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/pull.html">pull</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span>

<span class="va">rsq_train</span> <span class="op">&lt;-</span> <span class="fu">rsq</span><span class="op">(</span><span class="va">office_train_pred</span>, truth <span class="op">=</span> <span class="va">imdb_rating</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/pull.html">pull</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span>

<span class="va">rmse_test</span> <span class="op">&lt;-</span> <span class="fu">rmse</span><span class="op">(</span><span class="va">office_test_pred</span>, truth <span class="op">=</span> <span class="va">imdb_rating</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/pull.html">pull</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span>

<span class="va">rsq_test</span> <span class="op">&lt;-</span> <span class="fu">rsq</span><span class="op">(</span><span class="va">office_test_pred</span>, truth <span class="op">=</span> <span class="va">imdb_rating</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/pull.html">pull</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span></code></pre></div>
<div class="inline-table"><table class="table table-sm">
<thead><tr class="header">
<th align="left">metric</th>
<th align="right">train</th>
<th align="right">test</th>
<th align="left">comparison</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">RMSE</td>
<td align="right">0.302</td>
<td align="right">0.411</td>
<td align="left">RMSE lower for training</td>
</tr>
<tr class="even">
<td align="left">R-squared</td>
<td align="right">0.67</td>
<td align="right">0.468</td>
<td align="left">R-squared higher for training</td>
</tr>
</tbody>
</table></div>
</div>
<div id="evaluating-performance-on-training-data" class="section level4 unnumbered">
<h4>Evaluating performance on training data<a class="anchor" aria-label="anchor" href="#evaluating-performance-on-training-data"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li><p>The training set does not have the capacity to be a good arbiter of performance.</p></li>
<li><p>It is not an independent piece of information; predicting the training set can only reflect what the model already knows.</p></li>
<li><p>Suppose you give a class a test, then give them the answers, then provide the same test.
The student scores on the second test do not accurately reflect what they know about the subject; these scores would probably be higher than their results on the first test.</p></li>
</ul>
</div>
</div>
</div>
<div id="cross-validation" class="section level2" number="10.3">
<h2>
<span class="header-section-number">10.3</span> Cross Validation<a class="anchor" aria-label="anchor" href="#cross-validation"><i class="fas fa-link"></i></a>
</h2>
<p>Before we get into the details of cross validation, let’s set up the scenario for when we need cross validation. Recall that we use the test data to assess how the model does. But we haven’t yet thought about how to use the data to <strong>build</strong> a particular model.</p>
<p>For example, let’s set up a scenario to compare two different models. The first model is the same one built with the recipe above. The second model does not use <code>air_date</code> as a variable at all.</p>
<p><strong>Model 1:</strong></p>
<div class="sourceCode" id="cb439"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec1</span> <span class="op">&lt;-</span> <span class="fu">recipe</span><span class="op">(</span><span class="va">imdb_rating</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">update_role</span><span class="op">(</span><span class="va">title</span>, new_role <span class="op">=</span> <span class="st">"ID"</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_date</span><span class="op">(</span><span class="va">air_date</span>, features <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"dow"</span>, <span class="st">"month"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_holiday</span><span class="op">(</span>
    <span class="va">air_date</span>, 
    holidays <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"USThanksgivingDay"</span>, <span class="st">"USChristmasDay"</span>, <span class="st">"USNewYearsDay"</span>, <span class="st">"USIndependenceDay"</span><span class="op">)</span>, 
    keep_original_cols <span class="op">=</span> <span class="cn">FALSE</span>
  <span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_num2factor</span><span class="op">(</span><span class="va">season</span>, levels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/character.html">as.character</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">9</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_dummy</span><span class="op">(</span><span class="fu">all_nominal_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_zv</span><span class="op">(</span><span class="fu">all_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb440"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">prep</span><span class="op">(</span><span class="va">office_rec1</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
<span class="fu">bake</span><span class="op">(</span><span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/pillar/man/glimpse.html">glimpse</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 141
## Columns: 22
## $ episode            &lt;dbl&gt; 18, 14, 8, 5, 22, 1, 15, 21, 18, 12, 25, 26, 12, 1,…
## $ title              &lt;fct&gt; "Last Day in Florida", "Vandalism", "Performance Re…
## $ total_votes        &lt;dbl&gt; 1429, 1402, 2416, 1515, 2783, 1897, 2283, 2041, 144…
## $ imdb_rating        &lt;dbl&gt; 7.8, 7.6, 8.2, 7.1, 9.1, 8.4, 8.3, 8.9, 8.0, 8.0, 8…
## $ season_X2          &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ season_X3          &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ season_X4          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ season_X5          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, …
## $ season_X6          &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, …
## $ season_X7          &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, …
## $ season_X8          &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, …
## $ season_X9          &lt;dbl&gt; 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, …
## $ air_date_dow_Tue   &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ air_date_dow_Thu   &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, …
## $ air_date_month_Feb &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ air_date_month_Mar &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
## $ air_date_month_Apr &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, …
## $ air_date_month_May &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, …
## $ air_date_month_Sep &lt;dbl&gt; 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, …
## $ air_date_month_Oct &lt;dbl&gt; 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, …
## $ air_date_month_Nov &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, …
## $ air_date_month_Dec &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …</code></pre>
<p><strong>Model 2:</strong></p>
<div class="sourceCode" id="cb442"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_rec2</span> <span class="op">&lt;-</span> <span class="fu">recipe</span><span class="op">(</span><span class="va">imdb_rating</span> <span class="op">~</span> <span class="va">.</span>, data <span class="op">=</span> <span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">update_role</span><span class="op">(</span><span class="va">title</span>, new_role <span class="op">=</span> <span class="st">"id"</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="co"># delete the air_date variable</span>
  <span class="fu">step_rm</span><span class="op">(</span><span class="va">air_date</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_dummy</span><span class="op">(</span><span class="fu">all_nominal_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">step_zv</span><span class="op">(</span><span class="fu">all_predictors</span><span class="op">(</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb443"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">prep</span><span class="op">(</span><span class="va">office_rec2</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
<span class="fu">bake</span><span class="op">(</span><span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/pillar/man/glimpse.html">glimpse</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## Rows: 141
## Columns: 5
## $ season      &lt;dbl&gt; 8, 9, 2, 9, 3, 7, 3, 9, 9, 8, 5, 5, 9, 6, 7, 6, 5, 2, 2, 9…
## $ episode     &lt;dbl&gt; 18, 14, 8, 5, 22, 1, 15, 21, 18, 12, 25, 26, 12, 1, 20, 8,…
## $ title       &lt;fct&gt; "Last Day in Florida", "Vandalism", "Performance Review", …
## $ total_votes &lt;dbl&gt; 1429, 1402, 2416, 1515, 2783, 1897, 2283, 2041, 1445, 1612…
## $ imdb_rating &lt;dbl&gt; 7.8, 7.6, 8.2, 7.1, 9.1, 8.4, 8.3, 8.9, 8.0, 8.0, 8.7, 8.9…</code></pre>
<div id="creating-workflows" class="section level4 unnumbered">
<h4>Creating workflows<a class="anchor" aria-label="anchor" href="#creating-workflows"><i class="fas fa-link"></i></a>
</h4>
<p>Using each of the separate recipes, different workflows are set up:</p>
<p><strong>Model 1:</strong></p>
<div class="sourceCode" id="cb445"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_wflow1</span> <span class="op">&lt;-</span> <span class="fu">workflow</span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">add_model</span><span class="op">(</span><span class="va">office_spec</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">add_recipe</span><span class="op">(</span><span class="va">office_rec1</span><span class="op">)</span>

<span class="va">office_wflow1</span></code></pre></div>
<pre><code>## ══ Workflow ════════════════════════════════════════════════════════════════════
## Preprocessor: Recipe
## Model: linear_reg()
## 
## ── Preprocessor ────────────────────────────────────────────────────────────────
## 5 Recipe Steps
## 
## • step_date()
## • step_holiday()
## • step_num2factor()
## • step_dummy()
## • step_zv()
## 
## ── Model ───────────────────────────────────────────────────────────────────────
## Linear Regression Model Specification (regression)
## 
## Computational engine: lm</code></pre>
<p><strong>Model 2:</strong></p>
<div class="sourceCode" id="cb447"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_wflow2</span> <span class="op">&lt;-</span> <span class="fu">workflow</span><span class="op">(</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">add_model</span><span class="op">(</span><span class="va">office_spec</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">add_recipe</span><span class="op">(</span><span class="va">office_rec2</span><span class="op">)</span>

<span class="va">office_wflow2</span></code></pre></div>
<pre><code>## ══ Workflow ════════════════════════════════════════════════════════════════════
## Preprocessor: Recipe
## Model: linear_reg()
## 
## ── Preprocessor ────────────────────────────────────────────────────────────────
## 3 Recipe Steps
## 
## • step_rm()
## • step_dummy()
## • step_zv()
## 
## ── Model ───────────────────────────────────────────────────────────────────────
## Linear Regression Model Specification (regression)
## 
## Computational engine: lm</code></pre>
</div>
<div id="fit-the-models-to-the-training-data" class="section level4 unnumbered">
<h4>Fit the models to the training data<a class="anchor" aria-label="anchor" href="#fit-the-models-to-the-training-data"><i class="fas fa-link"></i></a>
</h4>
<p><strong>WAIT</strong>, not so fast!</p>
</div>
<div id="fit-the-models-using-cross-validation" class="section level3" number="10.3.1">
<h3>
<span class="header-section-number">10.3.1</span> Fit the models using cross validation<a class="anchor" aria-label="anchor" href="#fit-the-models-using-cross-validation"><i class="fas fa-link"></i></a>
</h3>
<div id="spending-the-data" class="section level4 unnumbered">
<h4>“Spending” the data<a class="anchor" aria-label="anchor" href="#spending-the-data"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>We have already established that the idea of data spending where the test set was recommended for obtaining an unbiased estimate of performance.</li>
<li>However, we usually need to understand the effectiveness of the model <em>before using the test set</em>.</li>
<li>Typically we can’t decide on <em>which</em> final model to take to the test set without making model assessments.</li>
<li>Remedy: Resampling to make model assessments on training data in a way that can generalize to new data.</li>
</ul>
</div>
<div id="resampling-for-model-assessment" class="section level4 unnumbered">
<h4>Resampling for model assessment<a class="anchor" aria-label="anchor" href="#resampling-for-model-assessment"><i class="fas fa-link"></i></a>
</h4>
<p><strong>Resampling is only conducted on the training set</strong>.
The test set is not involved.
For each iteration of resampling, the data are partitioned into two subsamples:</p>
<ul>
<li>The model is fit with the <strong>analysis set</strong>.</li>
<li>The model is evaluated with the <strong>assessment set</strong>.</li>
</ul>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-50"></span>
<img src="figs/resampling.svg" alt="Repeated samples are taken from the training data, and with each resample some of the observations are used to build a model and some observations are used to estimate the performance. Source: [@tidymodelingR]" width="100%"><p class="caption">
Figure 10.1: Repeated samples are taken from the training data, and with each resample some of the observations are used to build a model and some observations are used to estimate the performance. Source: <span class="citation">(<a href="references.html#ref-tidymodelingR" role="doc-biblioref">Kuhn and Silge 2022</a>)</span>
</p>
</div>
<p>Aside: the “re” in “resamples” is for repeated samples. Not to be confused where repeated samples are taken in bootstrapping with replacement. In cross validation, the repeated samples are taken <strong>without</strong> replacement.</p>
</div>
<div id="analysis-and-assessment-sets" class="section level4 unnumbered">
<h4>Analysis and assessment sets<a class="anchor" aria-label="anchor" href="#analysis-and-assessment-sets"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>Analysis set is analogous to training set.</li>
<li>Assessment set is analogous to test set.</li>
<li>The terms <em>analysis</em> and <em>assessment</em> avoids confusion with initial split of the data.</li>
<li>These data sets are mutually exclusive.</li>
</ul>
</div>
<div id="cross-validation-1" class="section level4 unnumbered">
<h4>Cross validation<a class="anchor" aria-label="anchor" href="#cross-validation-1"><i class="fas fa-link"></i></a>
</h4>
<p>More specifically, <strong>v-fold cross validation</strong> – commonly used resampling technique:</p>
<ul>
<li>Randomly split your <strong>training</strong> <strong>data</strong> into v partitions</li>
<li>Use 1 partition for assessment, and the remaining v-1 partitions for analysis</li>
<li>Repeat v times, updating which partition is used for assessment each time</li>
</ul>
<p>Let’s give an example where <code>v = 3</code>…</p>
</div>
<div id="cross-validation-step-1" class="section level4 unnumbered">
<h4>Cross validation, step 1<a class="anchor" aria-label="anchor" href="#cross-validation-step-1"><i class="fas fa-link"></i></a>
</h4>
<p>Consider the example below where the <strong>training</strong> <strong>data</strong> are randomly split into 3 partitions:</p>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-51"></span>
<img src="figs/three-CV.svg" alt="Thirty observations are seen where three colors are used to demonstrate that the observations can be partitioned into three groups." width="100%"><p class="caption">
Figure 10.2: Splitting the data into a partition of v=3 groups. Source: <span class="citation">(<a href="references.html#ref-tidymodelingR" role="doc-biblioref">Kuhn and Silge 2022</a>)</span>
</p>
</div>
<div class="sourceCode" id="cb449"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">345</span><span class="op">)</span>
<span class="va">folds</span> <span class="op">&lt;-</span> <span class="fu">vfold_cv</span><span class="op">(</span><span class="va">office_train</span>, v <span class="op">=</span> <span class="fl">3</span><span class="op">)</span>
<span class="va">folds</span></code></pre></div>
<pre><code>## #  3-fold cross-validation 
## # A tibble: 3 × 2
##   splits          id   
##   &lt;list&gt;          &lt;chr&gt;
## 1 &lt;split [94/47]&gt; Fold1
## 2 &lt;split [94/47]&gt; Fold2
## 3 &lt;split [94/47]&gt; Fold3</code></pre>
<p>Note that the three repeated samples (“resamples”) are taken without replacement from the original dataset.</p>
</div>
<div id="cross-validation-steps-2-and-3" class="section level4 unnumbered">
<h4>Cross validation, steps 2 and 3<a class="anchor" aria-label="anchor" href="#cross-validation-steps-2-and-3"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>Use 1 partition for assessment, and the remaining v-1 partitions for analysis</li>
<li>Repeat v times, updating which partition is used for assessment each time</li>
</ul>
<div class="figure" style="text-align: center">
<span style="display:block;" id="fig:unnamed-chunk-53"></span>
<img src="figs/three-CV-iter.svg" alt="Three iterations of model fitting are shown, each time using only 2/3 of the observations.  The remaining 1/3 of the observations are used to estimate the performance of the model." width="100%"><p class="caption">
Figure 10.3: With the data split into three groups, we can see how 2/3 of the observations are used to fit the model and 1/3 of the observations are used to estimate the performance of the model. Source: <span class="citation">(<a href="references.html#ref-tidymodelingR" role="doc-biblioref">Kuhn and Silge 2022</a>)</span>
</p>
</div>
</div>
<div id="fit-resamples" class="section level4 unnumbered">
<h4>Fit resamples<a class="anchor" aria-label="anchor" href="#fit-resamples"><i class="fas fa-link"></i></a>
</h4>
<p>After the data have been split into v (here 3) resamples, they can each be fit to the two models of interest.</p>
<p><strong>Model 1:</strong></p>
<div class="sourceCode" id="cb451"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">456</span><span class="op">)</span>

<span class="va">office_fit_rs1</span> <span class="op">&lt;-</span> <span class="va">office_wflow1</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">fit_resamples</span><span class="op">(</span><span class="va">folds</span><span class="op">)</span>

<span class="va">office_fit_rs1</span></code></pre></div>
<pre><code>## # Resampling results
## # 3-fold cross-validation 
## # A tibble: 3 × 4
##   splits          id    .metrics         .notes          
##   &lt;list&gt;          &lt;chr&gt; &lt;list&gt;           &lt;list&gt;          
## 1 &lt;split [94/47]&gt; Fold1 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 1]&gt;
## 2 &lt;split [94/47]&gt; Fold2 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 1]&gt;
## 3 &lt;split [94/47]&gt; Fold3 &lt;tibble [2 × 4]&gt; &lt;tibble [1 × 1]&gt;</code></pre>
<p><strong>Model 2:</strong></p>
<div class="sourceCode" id="cb453"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">456</span><span class="op">)</span>

<span class="va">office_fit_rs2</span> <span class="op">&lt;-</span> <span class="va">office_wflow2</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">fit_resamples</span><span class="op">(</span><span class="va">folds</span><span class="op">)</span>

<span class="va">office_fit_rs2</span></code></pre></div>
<pre><code>## # Resampling results
## # 3-fold cross-validation 
## # A tibble: 3 × 4
##   splits          id    .metrics         .notes          
##   &lt;list&gt;          &lt;chr&gt; &lt;list&gt;           &lt;list&gt;          
## 1 &lt;split [94/47]&gt; Fold1 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 1]&gt;
## 2 &lt;split [94/47]&gt; Fold2 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 1]&gt;
## 3 &lt;split [94/47]&gt; Fold3 &lt;tibble [2 × 4]&gt; &lt;tibble [0 × 1]&gt;</code></pre>
</div>
<div id="cross-validation-now-what" class="section level4 unnumbered">
<h4>Cross validation, now what?<a class="anchor" aria-label="anchor" href="#cross-validation-now-what"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>We’ve fit a bunch of models</li>
<li>Now it’s time to use them to collect metrics (e.g., R-squared, RMSE) on each model and use them to evaluate model fit and how it varies across folds</li>
</ul>
</div>
<div id="collect-cv-metrics" class="section level4 unnumbered">
<h4>Collect CV metrics<a class="anchor" aria-label="anchor" href="#collect-cv-metrics"><i class="fas fa-link"></i></a>
</h4>
<p><strong>Model 1:</strong></p>
<div class="sourceCode" id="cb455"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">collect_metrics</span><span class="op">(</span><span class="va">office_fit_rs1</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 6
##   .metric .estimator  mean     n std_err .config             
##   &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
## 1 rmse    standard   0.402     3  0.0329 Preprocessor1_Model1
## 2 rsq     standard   0.524     3  0.0410 Preprocessor1_Model1</code></pre>
<p><strong>Model 2:</strong></p>
<div class="sourceCode" id="cb457"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">collect_metrics</span><span class="op">(</span><span class="va">office_fit_rs1</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 × 6
##   .metric .estimator  mean     n std_err .config             
##   &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;               
## 1 rmse    standard   0.402     3  0.0329 Preprocessor1_Model1
## 2 rsq     standard   0.524     3  0.0410 Preprocessor1_Model1</code></pre>
</div>
<div id="deeper-look-into-cv-metrics" class="section level4 unnumbered">
<h4>Deeper look into CV metrics<a class="anchor" aria-label="anchor" href="#deeper-look-into-cv-metrics"><i class="fas fa-link"></i></a>
</h4>
<p><strong>Model 1:</strong></p>
<div class="sourceCode" id="cb459"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cv_metrics1</span> <span class="op">&lt;-</span> <span class="fu">collect_metrics</span><span class="op">(</span><span class="va">office_fit_rs1</span>, summarize <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> 

<span class="va">cv_metrics1</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   id    .metric .estimator .estimate .config             
##   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;               
## 1 Fold1 rmse    standard       0.364 Preprocessor1_Model1
## 2 Fold1 rsq     standard       0.590 Preprocessor1_Model1
## 3 Fold2 rmse    standard       0.376 Preprocessor1_Model1
## 4 Fold2 rsq     standard       0.449 Preprocessor1_Model1
## 5 Fold3 rmse    standard       0.468 Preprocessor1_Model1
## 6 Fold3 rsq     standard       0.534 Preprocessor1_Model1</code></pre>
<p><strong>Model 2:</strong></p>
<div class="sourceCode" id="cb461"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cv_metrics2</span> <span class="op">&lt;-</span> <span class="fu">collect_metrics</span><span class="op">(</span><span class="va">office_fit_rs2</span>, summarize <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span> 

<span class="va">cv_metrics2</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   id    .metric .estimator .estimate .config             
##   &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt; &lt;chr&gt;               
## 1 Fold1 rmse    standard       0.388 Preprocessor1_Model1
## 2 Fold1 rsq     standard       0.529 Preprocessor1_Model1
## 3 Fold2 rmse    standard       0.421 Preprocessor1_Model1
## 4 Fold2 rsq     standard       0.266 Preprocessor1_Model1
## 5 Fold3 rmse    standard       0.411 Preprocessor1_Model1
## 6 Fold3 rsq     standard       0.518 Preprocessor1_Model1</code></pre>
</div>
<div id="better-tabulation-of-cv-metrics" class="section level4 unnumbered">
<h4>Better tabulation of CV metrics<a class="anchor" aria-label="anchor" href="#better-tabulation-of-cv-metrics"><i class="fas fa-link"></i></a>
</h4>
<strong>Model 1:</strong>
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
Fold
</th>
<th style="text-align:right;">
RMSE
</th>
<th style="text-align:right;">
R-squared
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Fold1
</td>
<td style="text-align:right;">
0.364
</td>
<td style="text-align:right;">
0.590
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold2
</td>
<td style="text-align:right;">
0.376
</td>
<td style="text-align:right;">
0.449
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold3
</td>
<td style="text-align:right;">
0.468
</td>
<td style="text-align:right;">
0.534
</td>
</tr>
</tbody>
</table></div>
<strong>Model 2:</strong>
<div class="inline-table"><table class="table table-sm">
<thead><tr>
<th style="text-align:left;">
Fold
</th>
<th style="text-align:right;">
RMSE
</th>
<th style="text-align:right;">
R-squared
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Fold1
</td>
<td style="text-align:right;">
0.388
</td>
<td style="text-align:right;">
0.529
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold2
</td>
<td style="text-align:right;">
0.421
</td>
<td style="text-align:right;">
0.266
</td>
</tr>
<tr>
<td style="text-align:left;">
Fold3
</td>
<td style="text-align:right;">
0.411
</td>
<td style="text-align:right;">
0.518
</td>
</tr>
</tbody>
</table></div>
</div>
<div id="how-does-rmse-compare-to-y" class="section level4 unnumbered">
<h4>How does RMSE compare to y?<a class="anchor" aria-label="anchor" href="#how-does-rmse-compare-to-y"><i class="fas fa-link"></i></a>
</h4>
<p>Recall that RMSE is calculated in the original units of the response variable.</p>
<p><span class="math display">\[RMSE_{\mbox{training}} = \sqrt{\frac{\sum_{i = 1}^n (y_i - \hat{y}_i)^2}{n}}\]</span></p>
<p>The CV RMSE uses 2/3 of the observations to build the model (<span class="math inline">\(\hat{y}_i\)</span>) and 1/3 of the observations to test against. In the equation below “i” is in the 1/3. Note that <span class="math inline">\(\hat{y}_{\tiny\mbox{2/3 of fold 1}, \normalsize i}\)</span> indicates the <span class="math inline">\(i^{th}\)</span> row has been predicted using the model built on 2/3^{rds} of the observations.</p>
<p><span class="math display">\[RMSE_{\mbox{fold 1}} = \sqrt{\frac{\sum_{i \in \tiny \mbox{1/3 fold 1}} \normalsize (y_i - \hat{y}_{\tiny\mbox{2/3 of fold 1}, \normalsize i})^2}{n/3}}\]</span></p>
<p>In comparing which model is better, the CV RMSE provides information on how well the model did predicting each 1/3 hold out sample. Indeed, the RMSE is the error (read: variability) that continues to exist even after the model is built.</p>
<p>We can compare the model RMSE to the original variability seen in the <code>imbd_rating</code> variable.</p>
<p><strong>Model 1:</strong></p>
<div class="sourceCode" id="cb463"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cv_metrics1</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">.metric</span> <span class="op">==</span> <span class="st">"rmse"</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>
    min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">min</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span>,
    max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">max</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span>,
    mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">mean</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span>,
    sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span>
  <span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##     min   max  mean     sd
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1 0.364 0.468 0.402 0.0569</code></pre>
<p><strong>Model 2:</strong></p>
<div class="sourceCode" id="cb465"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cv_metrics2</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">.metric</span> <span class="op">==</span> <span class="st">"rmse"</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>
    min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">min</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span>,
    max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">max</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span>,
    mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">mean</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span>,
    sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">.estimate</span><span class="op">)</span>
  <span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##     min   max  mean     sd
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1 0.388 0.421 0.407 0.0168</code></pre>
<p>Training data IMDB score stats:</p>
<div class="sourceCode" id="cb467"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_ratings</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/summarise.html">summarise</a></span><span class="op">(</span>
    min <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">min</a></span><span class="op">(</span><span class="va">imdb_rating</span><span class="op">)</span>,
    max <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">max</a></span><span class="op">(</span><span class="va">imdb_rating</span><span class="op">)</span>,
    mean <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/mosaic/man/aggregating.html">mean</a></span><span class="op">(</span><span class="va">imdb_rating</span><span class="op">)</span>,
    sd <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/sd.html">sd</a></span><span class="op">(</span><span class="va">imdb_rating</span><span class="op">)</span>
  <span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 4
##     min   max  mean    sd
##   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1   6.7   9.7  8.26 0.538</code></pre>
<p>The original variability (measured by standard deviation) of the ratings was 0.538. After running Model 1, the remaining variability (measured by RMSE averaged over the folds) is 0.482; after running Model 2, the remaining variability (measured by RMSE averaged over the folds) is 0.52.</p>
<p><strong>Conclusions:</strong></p>
<ul>
<li>It seems as though the linear model does reduce the variability in the response variable (though not by much).</li>
<li>It seems as though the linear model which includes the <code>air_date</code> variable (and has 21 coefficients!) is a (slightly) better model than the variable which does not include <code>air_date</code> (and has only 4 coefficients).</li>
</ul>
</div>
<div id="cross-validation-jargon" class="section level4 unnumbered">
<h4>Cross validation jargon<a class="anchor" aria-label="anchor" href="#cross-validation-jargon"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li>Referred to as v-fold or k-fold cross validation</li>
<li>Also commonly abbreviated as CV</li>
</ul>
</div>
<div id="cross-validation-redux" class="section level4 unnumbered">
<h4>Cross validation, redux<a class="anchor" aria-label="anchor" href="#cross-validation-redux"><i class="fas fa-link"></i></a>
</h4>
<ul>
<li><p>To illustrate how CV works, we used <code>v = 3</code>:</p></li>
<li><p>Analysis sets are 2/3 of the training set</p></li>
<li><p>Each assessment set is a distinct 1/3</p></li>
<li><p>The final resampling estimate of performance averages each of the 3 replicates</p></li>
<li><p>It was useful for illustrative purposes, but <code>v = 3</code> is a poor choice in practice</p></li>
<li><p>Values of <code>v</code> are most often 5 or 10; we generally prefer 10-fold cross-validation as a default</p></li>
</ul>
</div>
</div>
</div>
<div id="final-model-assessment" class="section level2" number="10.4">
<h2>
<span class="header-section-number">10.4</span> Final model assessment<a class="anchor" aria-label="anchor" href="#final-model-assessment"><i class="fas fa-link"></i></a>
</h2>
<p>Now that Model 1 has been chosen as the better model, the test data is <strong>finally</strong> brought in to measure how well Model 1 will predict data in the wild (not that there are any additional wild episodes of The Office, but…).</p>
<p><strong>Model 1:</strong></p>
<div class="sourceCode" id="cb469"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_preds1</span> <span class="op">&lt;-</span> <span class="va">office_wflow1</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">fit</span><span class="op">(</span>data <span class="op">=</span> <span class="va">office_train</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">office_test</span><span class="op">)</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu"><a href="https://rdrr.io/pkg/dplyr/man/bind.html">bind_cols</a></span><span class="op">(</span><span class="va">office_test</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/pkg/MASS/man/lm.ridge.html">select</a></span><span class="op">(</span><span class="va">imdb_rating</span>, <span class="va">title</span><span class="op">)</span><span class="op">)</span> 

<span class="va">office_preds1</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">rsq</span><span class="op">(</span>truth <span class="op">=</span> <span class="va">imdb_rating</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rsq     standard       0.468</code></pre>
<div class="sourceCode" id="cb471"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">office_preds1</span> <span class="op"><a href="https://rdrr.io/pkg/magrittr/man/pipe.html">%&gt;%</a></span>
  <span class="fu">rmse</span><span class="op">(</span>truth <span class="op">=</span> <span class="va">imdb_rating</span>, estimate <span class="op">=</span> <span class="va">.pred</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   .metric .estimator .estimate
##   &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
## 1 rmse    standard       0.411</code></pre>
<p>As seen before, the test <span class="math inline">\(R^2\)</span> on the test data is 0.468 (46.8% of the variability in the <code>imdb_rating</code> of the test data is explained by the model from the training data). Additionally, the test RMSE is 0.411. As expected, the RMSE is lower for training than test; the <span class="math inline">\(R^2\)</span> is higher for training than test.</p>

</div>
</div>

  <div class="chapter-nav">
<div class="prev"><a href="mlr.html"><span class="header-section-number">9</span> Multiple Linear Regression</a></div>
<div class="next"><a href="build.html"><span class="header-section-number">11</span> Model Building</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#process"><span class="header-section-number">10</span> Modeling as a Process6</a></li>
<li><a class="nav-link" href="#comparing-models"><span class="header-section-number">10.1</span> Comparing Models</a></li>
<li>
<a class="nav-link" href="#feature-engineering"><span class="header-section-number">10.2</span> Feature Engineering</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#building-a-model"><span class="header-section-number">10.2.1</span> Building a Model</a></li>
<li><a class="nav-link" href="#feature-engineering-1"><span class="header-section-number">10.2.2</span> Feature engineering</a></li>
<li><a class="nav-link" href="#modeling-workflow">Modeling workflow</a></li>
<li><a class="nav-link" href="#specifying-a-model"><span class="header-section-number">10.2.3</span> Specifying a model</a></li>
<li><a class="nav-link" href="#building-a-recipe"><span class="header-section-number">10.2.4</span> Building a recipe</a></li>
<li><a class="nav-link" href="#building-workflows"><span class="header-section-number">10.2.5</span> Building workflows</a></li>
<li><a class="nav-link" href="#evaluate-the-model"><span class="header-section-number">10.2.6</span> Evaluate the model</a></li>
<li><a class="nav-link" href="#r-squared">R-squared</a></li>
<li><a class="nav-link" href="#predictions-for-testing-data">Predictions for testing data</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#cross-validation"><span class="header-section-number">10.3</span> Cross Validation</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#fit-the-models-using-cross-validation"><span class="header-section-number">10.3.1</span> Fit the models using cross validation</a></li></ul>
</li>
<li><a class="nav-link" href="#final-model-assessment"><span class="header-section-number">10.4</span> Final model assessment</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/hardin47/website/blob/master/04a-process.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/hardin47/website/edit/master/04a-process.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Linear Models</strong>" was written by Jo Hardin. It was last built on 2022-02-26.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
