<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>cat</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="04-cat_files/libs/clipboard/clipboard.min.js"></script>
<script src="04-cat_files/libs/quarto-html/quarto.js"></script>
<script src="04-cat_files/libs/quarto-html/popper.min.js"></script>
<script src="04-cat_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="04-cat_files/libs/quarto-html/anchor.min.js"></script>
<link href="04-cat_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="04-cat_files/libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="04-cat_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="04-cat_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="04-cat_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="analysis-of-categorical-data" class="level1">
<h1>Analysis of Categorical Data</h1>
<p>(Section 6.3 in <span class="citation" data-cites="KuiperSklar">@KuiperSklar</span>.)</p>
<section id="cat" class="level2">
<h2 class="anchored" data-anchor-id="cat">Categorical Inference</h2>
<p>In either an observational study or a randomized experiment, we are often interested in assessing the statistical significance of the differences we see: Is the observed difference too big to have reasonably occurred just due to chance? To answer the question, we will use</p>
<ul>
<li>simulation</li>
<li>mathematical probability models.</li>
</ul>
<div class="example">
<p><strong>Back Pain &amp; Botox</strong>, <span class="citation" data-cites="iscam">@iscam</span>, <span class="citation" data-cites="botox">@botox</span><br>
The randomized clinical trial examined whether the drug botulinum toxin A (Botox) is helpful for reducing pain among patients who suffer from chronic low back pain. The 31 subjects who participated in the study were randomly assigned to one of two treatment groups: 16 received a placebo of normal saline and the other 15 received the drug itself. The subjects’ pain levels were evaluated at the beginning of the study and again after eight weeks. The researchers found that 2 of the 16 subjects who received the saline experienced a substantial reduction in pain, compared to 9 of the 15 subjects who received the actual drug.</p>
<ol type="1">
<li>Is this an experiment or an observational study?<br>
</li>
<li>Explain the importance of using the “placebo” treatment of saline.<br>
</li>
<li>Create the two-way table for summarizing the data, putting the explanatory variable as the rows and the response variable as the columns<br>
</li>
<li>Calculate the conditional proportions of pain reduction in the two groups. Display the results as a segmented bar graph. Comment on the preliminary analysis.</li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>pain reduction</th>
<th>no pain reduction</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Botox</td>
<td>9</td>
<td>6</td>
<td>15</td>
</tr>
<tr class="even">
<td>placebo</td>
<td>2</td>
<td>14</td>
<td>16</td>
</tr>
<tr class="odd">
<td></td>
<td>11</td>
<td>20</td>
<td>31</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\begin{eqnarray*}
\mbox{risk}_{\mbox{placebo}} = \frac{2}{16} &amp;=&amp; 0.125\\
\mbox{risk}_{\mbox{Botox}} = \frac{9}{15} &amp;=&amp; 0.6\\
RR &amp;=&amp; 4.8
\end{eqnarray*}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>backpain <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">treatment =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"placebo"</span>, <span class="dv">16</span>), <span class="fu">rep</span>(<span class="st">"Botox"</span>, <span class="dv">15</span>)),</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">outcome =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"reduction"</span>, <span class="dv">2</span>), <span class="fu">rep</span>(<span class="st">"no_reduction"</span>, <span class="dv">14</span>), </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="fu">rep</span>(<span class="st">"reduction"</span>, <span class="dv">9</span>), <span class="fu">rep</span>(<span class="st">"no_reduction"</span>, <span class="dv">6</span>)))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>backpain <span class="sc">|&gt;</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         outcome
treatment no_reduction reduction
  Botox              6         9
  placebo           14         2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>backpain <span class="sc">|&gt;</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 31
Columns: 2
$ treatment &lt;chr&gt; "placebo", "placebo", "placebo", "placebo", "placebo", "plac…
$ outcome   &lt;chr&gt; "reduction", "reduction", "no_reduction", "no_reduction", "n…</code></pre>
</div>
</div>
<p>Note that sometimes it makes sense for the y-axis to be count and sometimes it makes sense for the y-axis to be percent. Probably doesn’t matter much here, you should choose the bar plot that seems most informative to you.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>backpain <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> treatment)) <span class="sc">+</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> outcome), <span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"percentage"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>backpain <span class="sc">|&gt;</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> treatment)) <span class="sc">+</span> </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> outcome))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-cat_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<ol start="5" type="1">
<li><p>If there was no association between the treatment and the back pain relief, about how many of the 11 “successes” would you expect to see in each group? Did the researchers observe more successes in the saline group than expected (if the drug had no effect) or fewer successes than expected? Is this in the direction conjectured by the researchers?</p></li>
<li><p>Is is <em>possible</em> that the drug has absolutely no effect on back pain? That the differences were simply due to chance or random variability? How likely is that?</p></li>
</ol>
</div>
<section id="simulation" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="simulation">Simulation</h4>
<ul>
<li><p>11 red “success” cards (pain reduction); 20 black “failure” cards (no pain reduction)</p></li>
<li><p>randomly deal out (i.e.&nbsp;shuffle) 15 cards to the treatment group and 16 cards to the placebo group.</p></li>
<li><p>count how many people in the treatment group were successes? Repeat 5 times.</p></li>
<li><p>process</p>
<ul>
<li>what do the cards represent?</li>
<li>what does shuffling the cards represent?</li>
<li>what implicit assumption about the two groups did the shuffling of cards represent?</li>
<li>what observational units would be represented by the dots on the dotplot?</li>
<li>why would we count the number of repetitions with 9 or more “successes”?</li>
</ul></li>
<li><p>Repeat simulation using the two-way table applet: [http://www.rossmanchance.com/applets/2021/chisqshuffle/ChiSqShuffle.htm]</p></li>
<li><p>summary</p>
<ul>
<li>How many reps?</li>
<li>How many as extreme as the true data?</li>
<li>What proportion are at least as extreme as the true data?</li>
<li>Do our data support the researchers conjecture?</li>
<li>What if the actual data had been 7 successes in the treatment group (and 4 in the placebo group)?</li>
</ul></li>
</ul>
<div class="definition">
<p><strong>p-value</strong> The p-value is the probability of seeing our results or more extreme if there is nothing interesting going on with the data. (This is the same definition of p-value that you will always use in this class and in your own research.)</p>
</div>
<p>Notice that regardless of whether or not the drug has an effect, the data will be different each time (think: new 31 people). The small p-value allows us to draw cause-and-effect conclusions, but doesn’t necessarily allow us to infer to a larger population. Why not?</p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 30%">
<col style="width: 12%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">low cutoff</th>
<th style="text-align: center;">p-value</th>
<th style="text-align: center;">high cutoff</th>
<th style="text-align: left;">evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"></td>
<td style="text-align: center;">p-value <span class="math inline">\(\leq\)</span></td>
<td style="text-align: center;">0.001</td>
<td style="text-align: left;">very strong evidence</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.001</td>
<td style="text-align: center;"><span class="math inline">\(&lt;\)</span> p-value <span class="math inline">\(\leq\)</span></td>
<td style="text-align: center;">0.01</td>
<td style="text-align: left;">strong evidence</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.01</td>
<td style="text-align: center;"><span class="math inline">\(&lt;\)</span> p-value <span class="math inline">\(\leq\)</span></td>
<td style="text-align: center;">0.05</td>
<td style="text-align: left;">moderate evidence</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.05</td>
<td style="text-align: center;"><span class="math inline">\(&lt;\)</span> p-value <span class="math inline">\(\leq\)</span></td>
<td style="text-align: center;">0.10</td>
<td style="text-align: left;">weak but suggestive evidence</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.10</td>
<td style="text-align: center;"><span class="math inline">\(&lt;\)</span> p-value</td>
<td style="text-align: center;"></td>
<td style="text-align: left;">little or no evidence</td>
</tr>
</tbody>
</table>
</section>
<section id="inferFET" class="level3">
<h3 class="anchored" data-anchor-id="inferFET">Simulation using R</h3>
<p>The simulation from the applet can be recreated using the <strong>infer</strong> package in R. Note the different pieces of the simulation using functions like <code>specify()</code>, <code>hypothesize()</code>, <code>generate()</code>, and <code>calculate()</code>. Also notice that this particular function works best using the difference in proportions (which we discussed in class is equivalent to recording the single count of Botox patients who had reduced back pain).</p>
<p>Step 1. Calculate the observed difference in proportion of patients with reduced back pain. Note that as with linear regression we continue to use the syntax: <code>response variable ~ explanatory variable</code>.</p>
<p>Step 2. Go through the simulation steps, just like the applet.</p>
<ul>
<li><code>specify()</code> the variables<br>
</li>
<li><code>hypothesize()</code> about the null claim<br>
</li>
<li><code>generate()</code> many permutations of the data<br>
</li>
<li><code>calculate()</code> the statistic of interest for all the different permutations</li>
</ul>
<p>Step 3. Plot a histogram representing the differences in proportions for all the many permuted tables. The plot represents the distribution of the differences in proportion under the null hypothesis.</p>
<p>Step 4. Calculate the p-value from the sampling distribution generated in Step 3.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1.</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>diff_props <span class="ot">&lt;-</span> backpain <span class="sc">|&gt;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(outcome <span class="sc">~</span> treatment, <span class="at">success =</span> <span class="st">"reduction"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"diff in props"</span>, <span class="at">order =</span> <span class="fu">c</span>(<span class="st">"Botox"</span>, <span class="st">"placebo"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>()</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>diff_props  <span class="co"># print to screen to see the observed difference</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.475</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2.</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>nulldist <span class="ot">&lt;-</span> backpain <span class="sc">|&gt;</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(outcome <span class="sc">~</span> treatment, <span class="at">success =</span> <span class="st">"reduction"</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">"independence"</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"permute"</span>) <span class="sc">|&gt;</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"diff in props"</span>, <span class="at">order =</span> <span class="fu">c</span>(<span class="st">"Botox"</span>, <span class="st">"placebo"</span>))</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3.</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>nulldist <span class="sc">|&gt;</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> stat)) <span class="sc">+</span> </span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> diff_props, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-cat_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4.</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># note that the average (mean) of TRUE and FALSE is a proportion</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>nulldist <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(stat <span class="sc">&gt;=</span> diff_props))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `mean(stat &gt;= diff_props)`
                       &lt;dbl&gt;
1                      0.005</code></pre>
</div>
</div>
</section>
</section>
<section id="fisher" class="level2">
<h2 class="anchored" data-anchor-id="fisher">Fisher’s Exact Test</h2>
<p>(Section 6.4 in <span class="citation" data-cites="KuiperSklar">@KuiperSklar</span>, great detailed explanation!)</p>
<p>Because we have a fixed sample, we use the hypergeometric distribution to enumerate the possible ways of choosing our data or more extreme given fixed row and column totals.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>pain reduction</th>
<th>no pain reduction</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Botox</td>
<td>9 = x</td>
<td>6</td>
<td>15 = n</td>
</tr>
<tr class="even">
<td>placebo</td>
<td>2</td>
<td>14</td>
<td>16</td>
</tr>
<tr class="odd">
<td></td>
<td>11 = M</td>
<td>20 = N - M</td>
<td>31 = N</td>
</tr>
</tbody>
</table>
<p>To make it simpler, let’s say I have 5 items (N=5), and I want to choose 3 of them (n=3). How many ways can I do that?</p>
<blockquote class="blockquote">
<p>SSSNN, SSNSN, SSNNS, SNSSN, SNSNS, SNNSS, NSSSN, NSSNS, NSNSS, NNSSS [5!/ 3! 2!] (S = select, N = not selected)</p>
</blockquote>
<p>So, how many different ways can I select 11 people (out of 31) to be my “pain reduction” group? That is the total number of different groups of size 11 from 31. But really, we want our groups to be of a certain breakdown. We need 2 (of 16) to have gotten the placebo and 9 (of 15) to have gotten the Botox treatment.</p>
<div class="definition">
<p><strong>Hypergeometric Probability</strong> For any <span class="math inline">\(2 \times 2\)</span> table when there are N observations with M total successes , the probability of observing x successes in a sample of size n is:</p>
</div>
<p><span class="math display">\[\begin{eqnarray*}
P(X=x) = \frac{\# \mbox{ of ways to select x successes and n-x failures}}{\# \mbox{ of ways to select n subjects}} = \frac{ { M \choose x} {N-M \choose n-x}}{{N \choose n}}\\
\end{eqnarray*}\]</span></p>
<p>Find the P(X=2)</p>
<p>We can now find EXACT probabilities associated with the following hypotheses. <span class="math display">\[\begin{eqnarray*}
&amp;&amp;H_0: p_{pl} = p_{btx}\\
&amp;&amp;H_a: p_{pl} &lt; p_{btx}\\
&amp;&amp;p = \mbox{true probability of no pain}\\
\end{eqnarray*}\]</span></p>
<p>Is this a one- or two-sided test? Why? [Note: the conditions here include that the row and column totals are fixed – a <strong>conditional test of independence</strong>. However, the research project in the back of chapter 6 extends the permutation test to demonstrated that the probabilities hold even under alternative technical conditions.</p>
<p>Note also that we get an exact probability with no conditions needed about the sample size being big enough (we can use Fisher’s Exact Test even when true probabilities are close to 0 or 1.]</p>
</section>
<section id="chisq" class="level2">
<h2 class="anchored" data-anchor-id="chisq">Testing independence of two categorical variables</h2>
<p>(Sections 6.5, 6.6, 6.7 in <span class="citation" data-cites="KuiperSklar">@KuiperSklar</span>.)</p>
<section id="chi2-tests" class="level3">
<h3 class="anchored" data-anchor-id="chi2-tests"><span class="math inline">\(\chi^2\)</span> tests</h3>
<p>(Section 6.6 in <span class="citation" data-cites="KuiperSklar">@KuiperSklar</span>.)</p>
<p>2x2… but also rxc <span class="math inline">\((p_a = p_b = p_c)\)</span></p>
<p>We can also use <span class="math inline">\(\chi^2\)</span> tests to evaluate <span class="math inline">\(r \times c\)</span> contingency tables. Our main question now will be whether there is an association between two categorical variables of interest. Note that we are now generalizing what we did with the Botox and back pain example. Are the two variables independent? If the two variables are independent, then the state of one variable is not related to the probability of the different outcomes of the other variable.</p>
<p>If the data were sampled in such a way that we have random samples of both the explanatory and response variables (e.g., cross classification study), then we typically do a test of association:</p>
<p><span class="math display">\[\begin{eqnarray*}
H_0: &amp;&amp; \mbox{ the two variables are independent}\\
H_a: &amp;&amp; \mbox{ the two variables are not independent}
\end{eqnarray*}\]</span></p>
<p>If the data are sampled in such a way that the response is measured across specified populations (as in the example below), we typically do a test of homogeneity of proportions. For example,</p>
<p><span class="math display">\[\begin{eqnarray*}
H_0: &amp;&amp; p_1 = p_2 = p_3\\
H_a: &amp;&amp; \mbox{not } H_0
\end{eqnarray*}\]</span> where <span class="math inline">\(p=P(\mbox{success})\)</span> for each of groups 1,2,3.</p>
<p>How do we get expected frequencies? The same mathematics hold regardless of the type of test (i.e., sampling mechanism used to collect the data). If, in fact,the variables are independent, then we should be able to multiply their probabilities. If the probabilities are the same, we expect the overall proportion of each response variable to be the same as the proportion of the response variable in each explanatory group. And the math in the example below follows directly.</p>
<div class="example">
<p>The table below show the observed distributions of ABO blood type in three random samples of African Americans living in different locations. The three datasets, collected in the 1950s by three different investigators, are reproduced in <span class="citation" data-cites="bloodtype">[@bloodtype]</span>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th></th>
<th></th>
<th>Blood</th>
<th>Type</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>A</td>
<td>B</td>
<td>AB</td>
<td>O</td>
<td>Total</td>
</tr>
<tr class="even">
<td>Location</td>
<td>(Florida)</td>
<td>122</td>
<td>117</td>
<td>19</td>
<td>244</td>
<td>502</td>
</tr>
<tr class="odd">
<td></td>
<td>(Iowa)</td>
<td>1781</td>
<td>1351</td>
<td>289</td>
<td>3301</td>
<td>6722</td>
</tr>
<tr class="even">
<td></td>
<td>(Missouri)</td>
<td>353</td>
<td>269</td>
<td>60</td>
<td>713</td>
<td>1395</td>
</tr>
<tr class="odd">
<td></td>
<td>Total</td>
<td>2256</td>
<td>1737</td>
<td>368</td>
<td>4258</td>
<td>8619</td>
</tr>
</tbody>
</table>
</div>
<section id="test-of-homogeneity-of-proportions-equivalent-mathematically-to-independence" class="level4">
<h4 class="anchored" data-anchor-id="test-of-homogeneity-of-proportions-equivalent-mathematically-to-independence">Test of Homogeneity of Proportions (equivalent mathematically to independence)</h4>
<p>If there is no difference in blood type proportions across the groups, then:</p>
<p><span class="math display">\[\begin{eqnarray*}
P(AB | FL) = P(AB | IA) = P(AB | MO) = P(AB)
\end{eqnarray*}\]</span></p>
<p>We will use <span class="math inline">\(\widehat{P}(AB) = \frac{368}{8619}\)</span> as baseline for expectation (under <span class="math inline">\(H_0)\)</span> for all the groups. That is, we would expect,</p>
<p><span class="math display">\[\begin{eqnarray*}
\# \mbox{expected for AB blood and Iowa} &amp;=&amp;  \frac{368}{8619} \cdot 6722\\
\end{eqnarray*}\]</span></p>
</section>
<section id="test-of-independence-equivalent-mathematically-to-homogeneity-of-proporitions" class="level4">
<h4 class="anchored" data-anchor-id="test-of-independence-equivalent-mathematically-to-homogeneity-of-proporitions">Test of Independence (equivalent mathematically to homogeneity of proporitions)</h4>
<p><span class="math display">\[\begin{eqnarray*}
P(\mbox{ cond1 &amp; cond2}) &amp;=&amp; P(\mbox{cond1}) P(\mbox{cond2})  \mbox{ if variables 1 and 2 are independent}\\
&amp;&amp;\\
P(AB \mbox{ blood &amp; Iowa}) &amp;=&amp; P(AB \mbox{ blood}) P(\mbox{Iowa}) \\
&amp;=&amp; \bigg( \frac{368}{8619}\bigg) \bigg( \frac{6722}{8619} \bigg)\\
&amp;=&amp; 0.0333\\
&amp;&amp;\\
\# \mbox{expected for AB blood and Iowa} &amp;=&amp; 0.033 \cdot 8619\\
&amp;=&amp; \frac{368 \cdot 6722}{8619}\\
&amp;&amp;\\
E_{i,j} &amp;=&amp; \frac{(i \mbox{ row total})(j \mbox{ col total})}{\mbox{grand total}}\\
\end{eqnarray*}\]</span></p>
<p>And the expected values under the null hypothesis…</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th></th>
<th></th>
<th>Blood</th>
<th>Type</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>A</td>
<td>B</td>
<td>AB</td>
<td>O</td>
<td>Total</td>
</tr>
<tr class="even">
<td>Location</td>
<td>(Florida)</td>
<td>131.4</td>
<td>101.17</td>
<td>21.43</td>
<td>248.00</td>
<td>502</td>
</tr>
<tr class="odd">
<td></td>
<td>(Iowa)</td>
<td>1759.47</td>
<td>1354.69</td>
<td>287.00</td>
<td>3320.83</td>
<td>6722</td>
</tr>
<tr class="even">
<td></td>
<td>(Missouri)</td>
<td>365.14</td>
<td>281.14</td>
<td>59.56</td>
<td>689.16</td>
<td>1395</td>
</tr>
<tr class="odd">
<td></td>
<td>Total</td>
<td>2256</td>
<td>1737</td>
<td>368</td>
<td>4258</td>
<td>8619</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\begin{eqnarray*}
X^2 &amp;=&amp; \sum_{all cells} \frac{( O - E)^2}{E}\\
&amp;=&amp; 5.65\\
\mbox{p-value} &amp;=&amp; P(\chi^2_6 \geq 5.65) \\
&amp;=&amp; 1 - pchisq(5.65, 6)\\
&amp;=&amp; 0.464
\end{eqnarray*}\]</span></p>
<p>We cannot reject the null hypothesis. Again, we have no evidence against the null hypothesis that blood types are independently distributed in the various regions.</p>
<p>How do we know if our test statistic is a big number or not? Well, it turns out that the test statistic <span class="math inline">\((X^2)\)</span> will have an approximate <span class="math inline">\(\chi^2\)</span> distribution with degrees of freedom = <span class="math inline">\((r- 1)\cdot (c-1).\)</span> As long as:</p>
<ul>
<li>We have a random sample from the population.<br>
</li>
<li>We expect at least 1 observation in every cell <span class="math inline">\((E_i \geq 1 \forall i)\)</span><br>
</li>
<li>We expect at least 5 observations in 80% of the cells <span class="math inline">\((E_i \geq 5\)</span> for 80% of <span class="math inline">\(i)\)</span></li>
</ul>
<p>When there are only two populations, the <span class="math inline">\(\chi^2\)</span> procedure is equivalent to the two-sided z-test for proportions. The chi-squared test statistic is the square of the z-test statistic. That is, the chi-squared test is exactly the same as the two-sided alternative for the z-test.</p>
<p>use chi-squared test if you have multiple populations</p>
<p>use z-test if you want one-sided tests or confidence intervals.</p>
</section>
</section>
</section>
<section id="catest" class="level2">
<h2 class="anchored" data-anchor-id="catest">Parameter Estimation</h2>
<p>(Section 6.8 in <span class="citation" data-cites="KuiperSklar">@KuiperSklar</span>.)</p>
<div class="definition">
<p><strong>Data Types</strong> Data are often classified as</p>
</div>
<ul>
<li>Categorical - each unit is assigned to a category<br>
</li>
<li>Quantitative - each observational unit is assigned a numerical value<br>
</li>
<li>(Binary - a special case of categorical with 2 categories, e.g.&nbsp;male/female)</li>
</ul>
<blockquote class="blockquote">
<p>Table 6.6 on page 193 of <span class="citation" data-cites="KuiperSklar">@KuiperSklar</span> is excellent and worth looking at.</p>
</blockquote>
<div class="example">
<p><strong>Popcorn &amp; Lung Disease</strong> <span class="citation" data-cites="iscam">@iscam</span></p>
<p>In May 2000, eight people who had worked at the same microwave-popcorn production plant reported to the Missouri Department of Health with fixed obstructive lung disease. These workers had become ill between 1993 and 2000 while employed at the plant. On the basis of these cases, in November 2000 researchers began conducting medical examinations and environmental surveys of workers employed at the plant to assess their occupational exposures to certain compounds (Kreiss, et al., 2002). As part of the study, current employees at the plant underwent spirometric testing. This measures FVC – forced viral capacity – the volume of air that can be maximally, forcefully exhaled. On this test, 31 employees had abnormal results, including 21 with airway obstruction. A total of 116 employees were tested.</p>
<p>Researchers were curious as to whether the baseline risk was high among microwave-popcorn workers. The plant itself was broken into several areas, some of which were separate from the popcorn production area. Air and dust samples in each job area were measured to determine the exposure to diacetyl, and marker of organic chemical exposure. Employees were classified into two groups: a “low-exposure group” and a “high-exposure group,” determined by how long an employee spent at different jobs within the plant and the average exposure in that job area. Of the 21 participants with airway obstruction, 6 were from the low-exposure group and 15 were from the high-exposure group. Both exposure groups contained 58 total employees.</p>
<p>How can we tell if popcorn production is related to lung disease? Consider High / Low exposure:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Airway obstructed</th>
<th>Airway not obstructed</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>low exposure</td>
<td>6</td>
<td>52</td>
<td>58</td>
</tr>
<tr class="even">
<td>high exposure</td>
<td>15</td>
<td>43</td>
<td>58</td>
</tr>
<tr class="odd">
<td></td>
<td>21</td>
<td>95</td>
<td>116</td>
</tr>
</tbody>
</table>
<p>Is 21 a lot of people? Can we compare 6 vs.&nbsp;15? What should we look at? <em>proportions</em> (always a number between 0 and 1). Look at your data (graphically and numerically). Segmented bar graph (mosaic plot):</p>
<p>Is there a difference in the two groups? Look at the difference in proportions or risk:</p>
<p><span class="math display">\[\begin{eqnarray*}
6/58 = 0.103 &amp; 15/58=0.2586 &amp; \Delta = 0.156\\
p_1 = 0.65 &amp; p_2 = 0.494 &amp; \Delta = 0.156\\
p_1 = 0.001 &amp; p_2 = 0.157 &amp; \Delta = 0.156\\
\end{eqnarray*}\]</span></p>
</div>
<section id="differences-in-proportions" class="level3">
<h3 class="anchored" data-anchor-id="differences-in-proportions">Differences in Proportions</h3>
<p>It turns out that the sampling distribution of the difference in the sample proportions (of success) across two <em>independent</em> groups can be modeled by the normal distribution if we have reasonably large sample sizes (CLT).</p>
<p>To ensure the accuracy of the test, check whether np and n(1-p) is bigger than 5 in both samples is usually adequate. A more precise check is <span class="math inline">\(n_s \hat{p}_c\)</span> and <span class="math inline">\(n_s(1-\hat{p}_c)\)</span> are both greater than 5; <span class="math inline">\(n_s\)</span> is the smaller of the two sample sizes and <span class="math inline">\(\hat{p}_c\)</span>is the sample proportion when the two samples are combined into one.</p>
<p>Note: <span class="math display">\[\begin{eqnarray*}
\hat{p}_1 - \hat{p}_2 \sim N\Bigg(p_1 - p_2, \sqrt{\frac{p_1(1-p_1)}{n_1} + \frac{p_2(1-p_2)}{n_2}}\Bigg)
\end{eqnarray*}\]</span></p>
<p>When testing independence, we assume that <span class="math inline">\(p_1=p_2,\)</span> so we use the pooled estimate of the proportion to calculate the SE: <span class="math display">\[\begin{eqnarray*}
SE(\hat{p}_1 - \hat{p}_2) = \sqrt{ \hat{p}_c(1-\hat{p}_c) \bigg(\frac{1}{n_1} + \frac{1}{n_2}\bigg)}
\end{eqnarray*}\]</span></p>
<p>So, when testing, the appropriate test statistic is: <span class="math display">\[\begin{eqnarray*}
Z = \frac{\hat{p}_1 - \hat{p}_2 - 0}{ \sqrt{ \hat{p}_c(1-\hat{p}_c) (\frac{1}{n_1} + \frac{1}{n_2})}}
\end{eqnarray*}\]</span></p>
<section id="confidence-interval-for-p_1---p_2" class="level4">
<h4 class="anchored" data-anchor-id="confidence-interval-for-p_1---p_2">Confidence interval for <span class="math inline">\(p_1 - p_2\)</span></h4>
<p>We can’t pool our estimate for the SE, but everything else stays the same…</p>
<p><span class="math display">\[\begin{eqnarray*}
SE(\hat{p}_1 - \hat{p}_2) = \sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1} + \frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}
\end{eqnarray*}\]</span></p>
<p>The main idea here is to determine whether two categorical variables are independent. That is, does knowledge of the value of one variable tell me something about the probability of the other variable (gender and pregnancy). We’re going to talk about two different ways to approach this problem.</p>
</section>
</section>
<section id="rr" class="level3">
<h3 class="anchored" data-anchor-id="rr">Relative Risk</h3>
<div class="definition">
<p><strong>Relative Risk</strong> The relative risk (RR) is the ratio of risks for each group. We say, “The risk of success is <strong>RR</strong> times higher for those in group 1 compared to those in group 2.”</p>
</div>
<p><span class="math display">\[\begin{eqnarray*}
\mbox{relative risk} &amp;=&amp; \frac{\mbox{risk group 1}}{\mbox{risk group 2}}\\
&amp;=&amp;  \frac{\mbox{proportion of successes in group 1}}{\mbox{proportion of successes in group 2}}\\
\mbox{RR} &amp;=&amp; \frac{p_1}{p_2} = \frac{p_1}{p_2}\\
\widehat{\mbox{RR}} &amp;=&amp; \frac{\hat{p}_1}{\hat{p}_2}
\end{eqnarray*}\]</span></p>
<p><span class="math inline">\(\widehat{RR}\)</span> in the popcorn example is <span class="math inline">\(\frac{15/58}{6/58} = 2.5.\)</span> We say, “The risk of airway obstruction is 2.5 times higher for those in high exposure group compared to those in the low exposure group.” What about</p>
<ul>
<li>sample size?<br>
</li>
<li>baseline risk?</li>
</ul>
<section id="ciRR" class="level4">
<h4 class="anchored" data-anchor-id="ciRR">Confidence Interval for RR</h4>
<p>Due to some theory that we won’t cover, we use the fact that:</p>
<p><span class="math display">\[SE(\ln (\widehat{RR})) \approx \sqrt{\frac{(1 - \hat{p}_1)}{n_1 \hat{p}_1} + \frac{(1-\hat{p}_2)}{n_2 \hat{p}_2}}\]</span></p>
<p>And more theory we won’t cover that tells us:</p>
<p><span class="math display">\[
\ln(\widehat{RR}) \stackrel{\mbox{approx}}{\sim} N\Bigg( \ln(RR), \sqrt{\frac{(1 - \hat{p}_1)}{n_1 \hat{p}_1} + \frac{(1-\hat{p}_2)}{n_2 \hat{p}_2}} \Bigg)
\]</span></p>
<p>A <span class="math inline">\((1-\alpha)100\%\)</span> CI for the <span class="math inline">\(\ln(RR)\)</span> is: <span class="math display">\[\begin{eqnarray*}
\ln(\widehat{RR}) \pm z_{1-\alpha/2} SE(\ln(\widehat{RR}))
\end{eqnarray*}\]</span></p>
<p>Which gives a <span class="math inline">\((1-\alpha)100\%\)</span> CI for the <span class="math inline">\(RR\)</span>: <span class="math display">\[\begin{eqnarray*}
(e^{\ln(\widehat{RR}) - z_{1-\alpha/2} SE(\ln(\widehat{RR}))}, e^{\ln(\widehat{RR}) + z_{1-\alpha/2} SE(\ln(\widehat{RR}))})
\end{eqnarray*}\]</span></p>
</section>
</section>
<section id="or" class="level3">
<h3 class="anchored" data-anchor-id="or">Odds Ratios</h3>
<p>A related concept to risk is odds. It is often used in horse racing, where “success” is typically defined as losing. So, if the odds are 3 to 1 we would expect to lose 3/4 of the time.</p>
<div class="definition">
<p><strong>Odds Ratio</strong> A related concept to risk is odds. It is often used in horse racing, where “success” is typically defined as losing. So, if the odds are 3 to 1 we would expect to lose 3/4 of the time. The odds ratio (OR) is the ratio of odds for each group. We say, “The odds of success is <strong>OR</strong> times higher for those in group 1 compared to those group 2.”</p>
</div>
<p><span class="math inline">\(\mbox{ }\)</span></p>
<p><span class="math display">\[\begin{align}
\mbox{odds} &amp;= \frac{\mbox{proportion of successes}}{\mbox{proportion of failures}}\\
&amp;= \frac{\mbox{number of successes}}{\mbox{number of failures}} = \theta\\
\widehat{\mbox{odds}} &amp;= \hat{\theta}\\
\mbox{odds ratio} &amp;= \frac{\mbox{odds group 1}}{\mbox{odds group 2}} \\
\mbox{OR} &amp;= \frac{\theta_1}{\theta_2} = \frac{p_1/(1-p_1)}{p_2/(1-p_2)}= \frac{p_1/(1-p_1)}{p_2/(1-p_2)}\\
\widehat{\mbox{OR}} &amp;= \frac{\hat{\theta}_1}{\hat{\theta}_2} = \frac{\hat{p}_1/(1-\hat{p}_1)}{\hat{p}_2/(1-\hat{p}_2)}\\
\end{align}\]</span></p>
<p><span class="math inline">\(\widehat{OR}\)</span> in the popcorn example is <span class="math inline">\(\frac{15/43}{6/52} = 3.02.\)</span> We say, “The odds of airway obstruction are 3 times higher for those in the high exposure group compared to those in the low exposure group.”</p>
<section id="or-is-more-extreme-than-rr" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="or-is-more-extreme-than-rr">OR is more extreme than RR</h4>
<p>Without loss of generality, assume the true <span class="math inline">\(RR &gt; 1,\)</span> implying <span class="math inline">\(p_1 / p_2 &gt; 1\)</span> and <span class="math inline">\(p_1 &gt; p_2.\)</span></p>
<p>Note the following sequence of consequences:</p>
<p><span class="math display">\[\begin{eqnarray*}
RR = \frac{p_1}{p_2} &amp;&gt;&amp; 1\\
\frac{1 - p_1}{1 - p_2} &amp;&lt;&amp; 1\\
\frac{ 1 / (1 - p_1)}{1 / (1 - p_2)} &amp;&gt;&amp; 1\\
\frac{p_1}{p_2} \cdot \frac{ 1 / (1 - p_1)}{1 / (1 - p_2)} &amp;&gt;&amp; \frac{p_1}{p_2}\\
OR &amp;&gt;&amp; RR
\end{eqnarray*}\]</span></p>
</section>
<section id="other-considerations" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="other-considerations">Other considerations:</h4>
<ul>
<li>Observational study (who worked in each place?)<br>
</li>
<li>Cross sectional (only one point in time)<br>
</li>
<li>Healthy worker effect (who stayed home sick?)<br>
</li>
<li><strong>Explanatory variable</strong> is one that is a potential explanation for any changes (here exposure level).<br>
</li>
<li><strong>Response variable</strong> is the measured outcome of interest (here airway obstruction).</li>
</ul>
<div class="example">
<p><strong>Smoking &amp; Lung Cancer</strong> <span class="citation" data-cites="iscam">@iscam</span></p>
<p>After World War II, evidence began mounting that there was a link between cigarette smoking and pulmonary carcinoma (lung cancer). In the 1950s, two now classic articles were published on the subject. One of these studies was conducted in the United States by <span class="citation" data-cites="wynder">@wynder</span>. They found records from a large number (684) of patients with proven bronchiogenic carcinoma (a specific form of lung cancer) in hospitals in California, Colorado, Missouri, New Jersey, New York, Ohio, Pennsylvania, and Utah. They personally interviewed 634 of the subjects to identify their smoking habits, occupation, exposure to dust and fumes, alcohol intake, education, and cause of death of parents and siblings. Thirty-three subjects completed mailed questionnaires, and information for the other 17 was obtained from family members or close acquaintances. Of those in the study, the researchers focused on 605 male patients with the same form of lung cancer. Another 1332 hospital patients with similar age and economic distribution (including 780 males) without lung cancer were interviewed by these researchers in St.&nbsp;Louis and by other researchers in Boston, Cleveland, and Hines, Illinois.</p>
<p>The following two-way table replicates the counts for the 605 male patients with the same form of cancer and for the “control-group” of 780 males.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th></th>
<th>patients</th>
<th>controls</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>none</td>
<td><span class="math inline">\(&lt;\)</span> 1/day</td>
<td>8</td>
<td>114</td>
</tr>
<tr class="even">
<td>light</td>
<td>1-9/day</td>
<td>14</td>
<td>90</td>
</tr>
<tr class="odd">
<td>mod heavy</td>
<td>10-15/day</td>
<td>61</td>
<td>148</td>
</tr>
<tr class="even">
<td>heavy</td>
<td>16-20/day</td>
<td>213</td>
<td>278</td>
</tr>
<tr class="odd">
<td>excessive</td>
<td>21-34/day</td>
<td>187</td>
<td>90</td>
</tr>
<tr class="even">
<td>chain</td>
<td>35<span class="math inline">\(+\)</span>/day</td>
<td>122</td>
<td>60</td>
</tr>
</tbody>
</table>
<p>Given the results of the study, do you think we can generalize from the sample to the population? Explain and make it clear that you know the difference between a sample and a population.</p>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>cancer</th>
<th>healthy</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>chain smoking</td>
<td>122</td>
<td>60</td>
<td>182</td>
</tr>
<tr class="even">
<td>no smoking</td>
<td>8</td>
<td>114</td>
<td>122</td>
</tr>
<tr class="odd">
<td></td>
<td>130</td>
<td>174</td>
<td>304</td>
</tr>
</tbody>
</table>
<ul>
<li>Causation?<br>
</li>
<li>Case-control study (605 with lung cancer, 780 without… baseline rate?)</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group A</th>
<th>Group B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>expl = smoking status</td>
<td>expl = lung cancer</td>
</tr>
<tr class="even">
<td>resp = lung cancer</td>
<td>resp = smoking status</td>
</tr>
</tbody>
</table>
<ul>
<li>If lung cancer is considered a success and no smoking is baseline:</li>
</ul>
<p><span class="math display">\[\begin{eqnarray*}
\widehat{RR} &amp;=&amp; \frac{122/182}{8/122} = 10.22\\
\widehat{OR} &amp;=&amp; \frac{122/60}{8/114} = 28.9\\
\end{eqnarray*}\]</span> <del>The risk of lung cancer is 10.22 times higher for those who smoke than for those who don’t smoke.</del></p>
<p>The odds of lung cancer is 28.9 times higher for those who smoke than for those who don’t smoke.</p>
<ul>
<li>If chain smoking is considered a success and healthy is baseline:</li>
</ul>
<p><span class="math display">\[\begin{eqnarray*}
\widehat{RR} &amp;=&amp; \frac{122/130}{60/174} = 2.7\\
\widehat{OR} &amp;=&amp; \frac{122/8}{60/114} = 28.9\\
\end{eqnarray*}\]</span> The risk of smoking is 2.7 times higher for those who have lung cancer than for those who don’t have lung cancer.</p>
<p>The odds of smoking is 28.9 times higher for those who have lung cancer than for those who don’t have lung cancer.</p>
</section>
<section id="important-take-away" class="level4">
<h4 class="anchored" data-anchor-id="important-take-away">Important Take-Away</h4>
<p>We <strong>want</strong> to interpret as the probability of cancer if smoker. But those individual proportions and individual odds are not estimable. Therefore the relative risk is also not estimable.</p>
<p>BUT because the odds ratio is invariant to which is the response variable and which is the explanatory variable, the odds ratio is estimable!</p>
<p>AND the interpretation for the study will be:</p>
<blockquote class="blockquote">
<p>The odds of lung cancer is 28.9 times higher for those who smoke than for those who don’t smoke.</p>
</blockquote>
<p> We know the risk of being a light smoker if you have lung cancer but we do <em>not</em> know the risk of lung cancer if you are a light smoker. Let’s say we have a <em>population</em> of 1,000,000 people:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>cancer</th>
<th>healthy</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>light smoking</td>
<td>49,000</td>
<td>51,000</td>
<td>100,000</td>
</tr>
<tr class="even">
<td>no smoking</td>
<td>1,000</td>
<td>899,000</td>
<td>900,000</td>
</tr>
<tr class="odd">
<td></td>
<td>50,000</td>
<td>950,000</td>
<td>1,000,000</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\begin{eqnarray*}
P(\mbox{light} | \mbox{lung cancer}) &amp;=&amp; \frac{49,000}{50,000} = 0.98\\
P(\mbox{lung cancer} | \mbox{light}) &amp;=&amp; \frac{49,000}{100,000} = 0.49\\
\end{eqnarray*}\]</span></p>
<ul>
<li>What is the explanatory variable?</li>
<li>What is the response variable?</li>
<li>relative risk?</li>
<li>odds ratio?</li>
</ul>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group A</th>
<th>Group B</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>expl = smoking status</td>
<td>expl = lung cancer</td>
</tr>
<tr class="even">
<td>resp = lung cancer</td>
<td>resp = smoking status</td>
</tr>
</tbody>
</table>
<ul>
<li>If lung cancer is considered a success and no smoking is baseline:</li>
</ul>
<p><span class="math display">\[\begin{eqnarray*}
RR &amp;=&amp; \frac{49/100}{1/900} = 441\\
OR &amp;=&amp; \frac{49/51}{1/899} = 863.75\\
\end{eqnarray*}\]</span></p>
<ul>
<li>If light smoking is considered a success and healthy is baseline:</li>
</ul>
<p><span class="math display">\[\begin{eqnarray*}
RR &amp;=&amp; \frac{49/50}{51/950} = 18.25\\
OR &amp;=&amp; \frac{49/1}{51/899} = 863.75\\
\end{eqnarray*}\]</span></p>
<p>OR is the same no matter which variable you choose as explanatory versus response! Though, in general, we still prefer to know baseline odds or baseline risk (which we can’t know with a case-control study).</p>
<div class="example">
<p><strong>More on Smoking &amp; Lung Cancer</strong>, <span class="citation" data-cites="iscam">@iscam</span><br>
Now we have a cohort prospective study. (Previously we had a case-control retrospective study). Now do we have baseline risk estimates? Yes! But be careful, we can’t conclude causation, because the study is still observational.</p>
</div>
</section>
<section id="ciOR" class="level4">
<h4 class="anchored" data-anchor-id="ciOR">Confidence Interval for OR</h4>
<p>Due to some theory that we won’t cover:</p>
<p><span class="math display">\[\begin{eqnarray*}
SE(\ln (\widehat{OR})) &amp;\approx&amp; \sqrt{\frac{1}{n_1 \hat{p}_1 (1-\hat{p}_1)} + \frac{1}{n_2 \hat{p}_2 (1-\hat{p}_2)}}
\end{eqnarray*}\]</span></p>
<p>And more theory we won’t cover that tells us:</p>
<p><span class="math display">\[
\ln(\widehat{OR}) \stackrel{\mbox{approx}}{\sim} N\Bigg( \ln(OR), \sqrt{\frac{1}{n_1 \hat{p}_1 (1-\hat{p}_1)} + \frac{1}{n_2 \hat{p}_2 (1-\hat{p}_2)}} \Bigg)
\]</span></p>
<p>Note that your book introduces <span class="math inline">\(SE(\ln(\widehat{OR}))\)</span> in the context of hypothesis testing where the null, <span class="math inline">\(H_0: p_1 = p_2,\)</span> is assumed to be true. If the null is true, you’d prefer an estimate for the proportion of success to be based on the entire sample:</p>
<p><span class="math display">\[\begin{eqnarray*}
SE(\ln (\widehat{OR})) &amp;\approx&amp; \sqrt{\frac{1}{n_1 \hat{p} (1-\hat{p})} + \frac{1}{n_2 \hat{p}(1-\hat{p})}}
\end{eqnarray*}\]</span></p>
<p>So, a <span class="math inline">\((1-\alpha)100\%\)</span> CI for the <span class="math inline">\(\ln(OR)\)</span> is: <span class="math display">\[\begin{eqnarray*}
\ln(\widehat{OR}) \pm z_{1-\alpha/2} SE(\ln(\widehat{OR}))
\end{eqnarray*}\]</span></p>
<p>Which gives a <span class="math inline">\((1-\alpha)100\%\)</span> CI for the <span class="math inline">\(OR\)</span>: <span class="math display">\[\begin{eqnarray*}
(e^{\ln(\widehat{OR}) - z_{1-\alpha/2} SE(\ln(\widehat{OR}))}, e^{\ln(\widehat{OR}) + z_{1-\alpha/2} SE(\ln(\widehat{OR}))})
\end{eqnarray*}\]</span></p>
<p>Back to the example… <span class="math inline">\(OR = 28.9.\)</span> <span class="math display">\[\begin{eqnarray*}
SE(\ln(\widehat{OR})) &amp;=&amp; \sqrt{\frac{1}{182*0.67*(1-0.67)} + \frac{1}{122*0.0656*(1-0.0656)}}\\
&amp;=&amp; 0.398\\
90\% \mbox{ CI for } \ln(OR) &amp;&amp; \ln(28.9) \pm 1.645 \cdot 0.398\\
&amp;&amp; 3.366 \pm 1.645 \cdot 0.398\\
&amp;&amp; (2.71, 4.02)\\
90\% \mbox{ CI for } OR &amp;&amp; (e^{2.71}, e^{4.02})\\
&amp;&amp; (15.04, 55.47)\\
\end{eqnarray*}\]</span></p>
<p>We are 90% confident that the true <span class="math inline">\(\ln(OR)\)</span> is between 2.71 and 4.02. We are 90% confident that the true <span class="math inline">\(OR\)</span> is between 15.04 and 55.47. That is, the true odds of getting lung cancer if you smoke are somewhere between 15.04 and 55.47 times higher than if you don’t smoke, with 90% confidence.</p>
<p>Note 1: we use the theory which allows us to understand the sampling distribution for the <span class="math inline">\(\ln(\widehat{OR}).\)</span> We use the <em>process</em> for creating CIs to transform back to <span class="math inline">\(OR.\)</span></p>
<p>Note 2: We do not use the t-distribution here because we are not estimating the population standard deviation.</p>
<p>Note 3: There are not good general guidelines for checking whether the sample sizes are large enough for the normal approximation. Most authorities agree that one can get away with smaller sample sizes here than for the differences of two proportions. If the sample sizes pass the rough check discussed for <span class="math inline">\(\chi^2,\)</span> they should be large enough to support inferences based on the approximate normality of the log of the estimated odds ratio, too. <span class="citation" data-cites="sleuth">[@sleuth, page 541]</span></p>
<p>For the normal approximation to hold, we need the expected counts in each cell to be at least 5. <span class="citation" data-cites="pagano">[@pagano, page 355]</span></p>
<p>Note 4: If any of the cells are zero, many people will add 0.5 to that cell’s observed value.</p>
<p>Note 5: The OR will always be more extreme than the RR (one more reason to be careful…)</p>
<p><span class="math display">\[\begin{eqnarray*}
\mbox{assume } &amp;&amp; \frac{X_1 / n_1}{X_2 / n_2} = RR &gt; 1\\
&amp; &amp; \\
\frac{X_1}{n_1} &amp;=&amp; RR \ \ \frac{X_2}{n_2}\\
\frac{X_1}{n_1 - X_1} &amp;=&amp; RR \ \ \bigg( \frac{n_1}{n_2}  \frac{n_2 - X_2}{n_1 - X_1} \bigg) \frac{X_2}{n_2-X_2}\\
OR &amp;=&amp; RR \ \ \bigg(\frac{n_1}{n_2} \bigg) \frac{n_2 - X_2}{n_1 - X_1}\\
&amp;=&amp; RR \ \ \bigg(\frac{1/n_2}{1/n_1} \bigg) \frac{n_2 - X_2}{n_1 - X_1}\\
&amp;=&amp; RR  \ \ \frac{1 - X_2/n_2}{1 - X_1/n_1}\\
&amp; &gt; &amp; RR
\end{eqnarray*}\]</span> [<span class="math inline">\(1 - \frac{X_2}{n_2} &gt; 1 - \frac{X_1}{n_1} \rightarrow \frac{1 - \frac{X_2}{n_2}}{1 - \frac{X_1}{n_1}} &gt; 1\)</span>]</p>
<p>Note 6: <span class="math inline">\(RR \approx OR\)</span> if the risk is small (the denominator of the OR will be very similar to the denominator of the RR).</p>
</section>
</section>
</section>
<section id="studies" class="level2">
<h2 class="anchored" data-anchor-id="studies">Types of Studies</h2>
<p>(Section 6.9 of <span class="citation" data-cites="KuiperSklar">@KuiperSklar</span>.)</p>
<div class="definition">
<p><strong>Explanatory variable</strong> is one that is a potential explanation for any changes in the response variable.</p>
</div>
<div class="definition">
<p><strong>Response variable</strong> is the measured outcome of interest.</p>
</div>
<div class="definition">
<p><strong>Case-control study:</strong> identify observational units by response</p>
</div>
<div class="definition">
<p><strong>Cohort study:</strong> identify observational units by explanatory variable</p>
</div>
<div class="definition">
<p><strong>Cross-classification study:</strong> identify observational units regardless of levels of the variable.</p>
</div>
<section id="retrospective-versus-prospective-studies" class="level3">
<h3 class="anchored" data-anchor-id="retrospective-versus-prospective-studies">Retrospective versus Prospective Studies</h3>
<p>After much research (and asking many people who do not all agree!), I finally came across a definition of retrospective that I like. Note, however, that many many books <em>define</em> retrospective as synonymous with case-control. That is, they define a retrospective study to be one in which the observational units were chosen based on their status of the response variable. I disagree with that definition. As you see below, retrospective studies are defined based on the when the variables were <em>measured</em>. I’ve also given a quote from the Kuiper text where retrospective is defined as any study where historic data are collected (I like this definition less).</p>
<div class="definition">
<p>A <strong>prospective</strong> study watches for outcomes, such as the development of a disease, during the study period. The explanatory variables are <em>measured</em> before the response variable occurs.</p>
</div>
<div class="definition">
<p>A <strong>retrospective</strong> study looks backwards and examines exposures to suspected risk or protection factors in relation to an outcome that is established at the start of the study. The explanatory variables are <em>measured</em> after the response has happened.</p>
</div>
<blockquote class="blockquote">
<p>Studies can be classified further as either prospective or retrospective. We define a prospective study as one in which exposure and covariate measurements are made before the cases of illness occur. In a retrospective study these measurements are made after the cases have already occurred… Early writers referred to cohort studies as prospective studies and to case-control studies as retrospective studies because cohort studies usually begin with identification of the exposure status and then measure disease occurrence, whereas case-control studies usually begin by identifying cases and controls and then measure exposure status. The terms prospective and retrospective, however, are more usefully employed to describe the <strong>timing of disease occurrence with respect to exposure measurement</strong>. For example, case-control studies can be either prospective or retrospective. A prospective case-control study uses exposure measurements taken before disease, whereas a retrospective case-control study uses measurements taken after disease. <span class="citation" data-cites="modepi">[@modepi, page 74]</span></p>
</blockquote>
<blockquote class="blockquote">
<p>Retrospective cohort studies also exist. In these designs past (medical) records are often used to collect data. As with prospective cohort studies, the objective is still to first establish groups based on an explanatory variable. However since these are past records the response variable can be collected at the same time. <span class="citation" data-cites="KuiperSklar">[@KuiperSklar, chapter 6, page 24]</span></p>
</blockquote>
<p>Understanding if a study is retrospective or prospective leads to having a sense of the biases within a study.</p>
<ul>
<li>The retrospective aspect may introduce selection bias and misclassification or information bias. With retrospective studies, the temporal relationship is frequently difficult to assess.</li>
</ul>
<section id="disadvantages-of-prospective-cohort-studies" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="disadvantages-of-prospective-cohort-studies">Disadvantages of Prospective Cohort Studies</h4>
<ul>
<li>You may have to follow large numbers of subjects for a long time.<br>
</li>
<li>They can be very expensive and time consuming.<br>
</li>
<li>They are not good for rare diseases.<br>
</li>
<li>They are not good for diseases with a long latency.<br>
</li>
<li>Differential loss to follow up can introduce bias.</li>
</ul>
</section>
<section id="disadvantages-of-retrospective-cohort-studies" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="disadvantages-of-retrospective-cohort-studies">Disadvantages of Retrospective Cohort Studies</h4>
<ul>
<li>As with prospective cohort studies, they are not good for very rare diseases.</li>
<li>If one uses records that were not designed for the study, the available data may be of poor quality.</li>
<li>There is frequently an absence of data on potential confounding factors if the data was recorded in the past.</li>
<li>It may be difficult to identify an appropriate exposed cohort and an appropriate comparison group.</li>
<li>Differential losses to follow up can also bias retrospective cohort studies.</li>
</ul>
<p>Disadvantages from: http://sphweb.bumc.bu.edu/otlt/MPH-Modules/EP/EP713_CohortStudies/EP713_CohortStudies5.html</p>
<section id="examples-of-studies" class="level5 unnumbered">
<h5 class="unnumbered anchored" data-anchor-id="examples-of-studies">Examples of studies:</h5>
<ul>
<li>cross-classification, prospective: NHANES<br>
</li>
<li>cross-classification, retrospective: death records (if exposure is measured post-hoc)<br>
</li>
<li>case-control, prospective: the investigator still <em>enrolls</em> based on outcome status, but the measurements for the outcome variable happened after the measurements for the explanatory variable (e.g., medical records on BMI or smoking status)<br>
</li>
<li>case-control, retrospective: at the start of the study, all cases have already occurred and the investigator goes back to measure the exposure (explanatory) variable<br>
</li>
<li>cohort, prospective: follows the selected participants to assess the proportion who develop the disease of interest<br>
</li>
<li>cohort, retrospective: the exposure and outcomes have already happened (i.e., death records)</li>
</ul>
</section>
</section>
<section id="which-test" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="which-test">Which test?</h4>
<p>(Section 6.1 of <span class="citation" data-cites="KuiperSklar">@KuiperSklar</span>.)</p>
<p>It turns out that the tests above (independence, homogeneity of proportions, homogeneity of odds) are typically equivalent with respect to their conclusions. However, they each have particular conditions related to what they are testing, but that we can generally use any of them for our hypotheses of interest. However, we need to be very careful about our <strong>interpretations</strong>!</p>
<p>(No goodness of fit, section 6.11 of <span class="citation" data-cites="KuiperSklar">@KuiperSklar</span>.)</p>
</section>
</section>
</section>
<section id="r-example-categorical-data-botox-and-back-pain" class="level2">
<h2 class="anchored" data-anchor-id="r-example-categorical-data-botox-and-back-pain">R Example (categorical data): Botox and back pain</h2>
<section id="entering-and-visualizing-the-data" class="level3">
<h3 class="anchored" data-anchor-id="entering-and-visualizing-the-data">Entering and visualizing the data</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>backpain <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">treatment =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"placebo"</span>, <span class="dv">16</span>), <span class="fu">rep</span>(<span class="st">"Botox"</span>, <span class="dv">15</span>)),</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">outcome =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"reduction"</span>, <span class="dv">2</span>), <span class="fu">rep</span>(<span class="st">"no reduction"</span>, <span class="dv">14</span>), </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>                                 <span class="fu">rep</span>(<span class="st">"reduction"</span>, <span class="dv">9</span>), <span class="fu">rep</span>(<span class="st">"no reduction"</span>, <span class="dv">6</span>)))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>backpain <span class="sc">|&gt;</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         outcome
treatment no reduction reduction
  Botox              6         9
  placebo           14         2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>backpain <span class="sc">|&gt;</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> treatment)) <span class="sc">+</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> outcome))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-cat_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>backpain <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> treatment)) <span class="sc">+</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">fill =</span> outcome), <span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"percentage"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-cat_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="simulation-of-fishers-exact-test" class="level3">
<h3 class="anchored" data-anchor-id="simulation-of-fishers-exact-test">Simulation of Fisher’s Exact Test</h3>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1.</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>odds_ratio <span class="ot">&lt;-</span> backpain <span class="sc">|&gt;</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(outcome <span class="sc">~</span> treatment, <span class="at">success =</span> <span class="st">"reduction"</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"odds ratio"</span>, <span class="at">order =</span> <span class="fu">c</span>(<span class="st">"Botox"</span>, <span class="st">"placebo"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>()</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>odds_ratio  <span class="co"># print to screen to see the observed difference</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2.</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>nulldist <span class="ot">&lt;-</span> backpain <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(outcome <span class="sc">~</span> treatment, <span class="at">success =</span> <span class="st">"reduction"</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">"independence"</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"permute"</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"odds ratio"</span>, <span class="at">order =</span> <span class="fu">c</span>(<span class="st">"Botox"</span>, <span class="st">"placebo"</span>))</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3.</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>nulldist <span class="sc">|&gt;</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> stat)) <span class="sc">+</span> </span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span> </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> odds_ratio, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="04-cat_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4.</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># note that the average (mean) of TRUE and FALSE is a proportion</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>nulldist <span class="sc">|&gt;</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="fu">mean</span>(stat <span class="sc">&gt;=</span> odds_ratio))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  `mean(stat &gt;= odds_ratio)`
                       &lt;dbl&gt;
1                      0.003</code></pre>
</div>
</div>
</section>
<section id="fishers-exact-test" class="level3">
<h3 class="anchored" data-anchor-id="fishers-exact-test">Fisher’s Exact Test</h3>
<p>Note that the <a href="https://stats.stackexchange.com/questions/409219/how-does-fisher-test-calculate-the-confidence-interval-for-the-odds-ratio-in-r" target="_blank">method used</a> in <code>fisher.test()</code> to compute the CI is outside the scope of this class.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>backpain <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fisher.test</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  table(backpain)
p-value = 0.009147
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.008475855 0.710710371
sample estimates:
odds ratio 
 0.1040127 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># an approximate SE for the ln(OR) is given by:</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>se.lnOR <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span>(<span class="dv">16</span><span class="sc">*</span>(<span class="dv">2</span><span class="sc">/</span><span class="dv">16</span>)<span class="sc">*</span>(<span class="dv">14</span><span class="sc">/</span><span class="dv">16</span>)) <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>(<span class="dv">15</span><span class="sc">*</span>(<span class="dv">9</span><span class="sc">/</span><span class="dv">15</span>)<span class="sc">*</span>(<span class="dv">6</span><span class="sc">/</span><span class="dv">15</span>)))</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>se.lnOR</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9215239</code></pre>
</div>
</div>
</section>
<section id="chi-squared-analysis" class="level3">
<h3 class="anchored" data-anchor-id="chi-squared-analysis">Chi-squared Analysis</h3>
<p>Note that we can <code>tidy()</code> the Chi-square</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>backpain <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">chisq.test</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  table(backpain)
X-squared = 5.6964, df = 1, p-value = 0.017</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>backpain <span class="sc">|&gt;</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">table</span>() <span class="sc">|&gt;</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">chisq.test</span>() <span class="sc">|&gt;</span> </span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  statistic p.value parameter method                                            
      &lt;dbl&gt;   &lt;dbl&gt;     &lt;int&gt; &lt;chr&gt;                                             
1      5.70  0.0170         1 Pearson's Chi-squared test with Yates' continuity…</code></pre>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>