project:
  type: book
  output-dir: Notes

book:
  title: "Foundations of Data Science in R"
  reader-mode: true
  page-footer:
    left: |
      Foundations of Data Science in R, by Jo Hardin.
    right: |
      Built with 💚 and <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/tidydata_6.jpg
  favicon: images/favicon.ico
  site-url: https://ds002r-fds.netlify.app/
  repo-url: https://github.com/hardin47/ds002r-fds
  repo-branch: main
  repo-actions: [issue]
  chapters:
    - index.qmd

    - part: p0-data-intro.qmd
      chapters:
        - 01-intro.qmd
        - 02-github.qmd

    - part: p1-data-acquire.qmd
      chapters:
        - 03-rvest.qmd
        - 04-sql-in-R.qmd
        - 05-sql-verbs.qmd
        - 06-sql-joins.qmd

    - part: p2-data-explore.qmd
      chapters:
        - 07-wrangling.qmd
        - 08-text-analysis.qmd
        - 09-reg-expr.qmd
        
    - part: p3-data-viz.qmd
      chapters: 
        - 10-grammar-graphics.qmd
        - 11-ggplot.qmd
        
    - part: p4-data-conclude.qmd
      chapters:
        - 12-iteration.qmd
        - 13-permutation-tests.qmd

    - part: p5-data-communicate.qmd
      chapters:
        - 14-version-control.qmd
        - 15-R-tip-of-the-day.qmd
        - 16-reprex.qmd

bibliography: 
  - book.bib
  - packages.bib

format:
  html:
    theme:
      - scss/colors.scss
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Quicksand" type="text/css"/>
    code-link: true
    mainfont: Quicksand
    monofont: Quicksand
    include-in-header: js/mathjax-popover.html
    author-meta: "Jo Hardin"
    lightbox: 
      match: auto
      loop: false 
    embed-resources: true

editor: source

execute:
  freeze: false
  fig-width: 9
  fig-show: hold
  fig-align: center
  echo: true
  cache: false
  warning: false 
  callout-icon: false


knitr:
  opts_chunk: 
    dev: "ragg_png"
    fig-asp: 0.618  # 1 / phi
