# Data communication {.unnumbered}

There really isn't any point to doing data science unless it is communicated broadly.
Communicating well takes practice, but it will always be well served with reproducible analyses (e.g., using Quarto) and version control (e.g., GitHub). 

Think of a data science project as a story that includes data acquisition, data exploration, data visualization, data conclusions, and data communication.
The more you can pull the observer into your story, the more effective the data science project will be. @sec-good-code describes how you can best communicate your story with other people, using language that is clear and consistent.

In @sec-reprex we describe how to create a minimal reproducible example that will benefit you when you are looking for help.
By parsing your task into the smallest components possible, you can isolate the task that you are trying to accomplish.
Reproducible examples are additionally helpful when collaborating on teams.

Finally, in @sec-fin we think about **who** does data science and what are the important take-away messages from the entire semester.

