project:
  type: book
  output-dir: Notes

book:
  title: "Computational Statistics"
  reader-mode: true
  page-footer:
    left: |
      Computational Statistics, by Jo Hardin.
    right: |
      Built with 💚 and <a href="https://quarto.org/">Quarto</a>.
  cover-image: figs/cluster_single_linkage_6_featured.jpg
  favicon: images/favicon.ico
  site-url: https://m154-comp-stats.netlify.app/
  repo-url: https://github.com/hardin47/m154-comp-stats
  repo-branch: main
  repo-actions: [issue]
  chapters:
    - index.qmd

    - part: p1-communicate.qmd
      chapters:
        - 01-intro.qmd
        - 02-viz.qmd
        - 03-wrangling.qmd

    - part: p2-inference.qmd
      chapters:
        - 04-simulating.qmd
        - 05-permutation.qmd
        - 06-bootstrap.qmd

    - part: p3-machinelearn.qmd
      chapters:
        - 07-ethics.qmd
        - 08-classification.qmd
        - 09-clustering.qmd
        - 10-misc.qmd
        - 11-compstats.qmd
        
bibliography: 
  - book.bib
  - packages.bib

format:
  html:
    theme:
      - scss/colors.scss
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Quicksand" type="text/css"/>
    code-link: true
    mainfont: Quicksand
    monofont: Quicksand
    include-in-header: js/mathjax-popover.html
    author-meta: "Jo Hardin"
    lightbox: 
      match: auto
      loop: false 
    embed-resources: true

editor: source

execute:
  freeze: false
  fig-width: 6
  fig-show: hold
  fig-dpi: 300
  fig-align: center
  echo: true
  cache: false
  warning: false 
  callout-icon: false


knitr:
  opts_chunk: 
    dev: "ragg_png"
    fig-asp: 0.618  # 1 / phi
