<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Chapter 7 Inference on Correlation &amp; Regression | Introduction to (Bio)Statistics</title>
<meta name="author" content="Jo Hardin">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.2"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/header-attrs-2.7.6/header-attrs.js"></script><script src="libs/jquery-3.5.1/jquery-3.5.1.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.5.3/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.5.3/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.2.4.9000/tabs.js"></script><script src="libs/bs3compat-0.2.4.9000/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script type="text/x-mathjax-config">
    const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
    for (let popover of popovers){
      const div = document.createElement('div');
      div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
      div.innerHTML = popover.getAttribute('data-content');
      
      // Will this work with TeX on its own line?
      var has_math = div.querySelector("span.math");
      if (has_math) {
        document.body.appendChild(div);
      	MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
      	MathJax.Hub.Queue(function(){
          popover.setAttribute('data-content', div.innerHTML);
      	})
      }
    }
    </script><script src="https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/mark.js@8.11.1/dist/mark.min.js"></script><!-- CSS --><link rel="stylesheet" href="style.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Introduction to (Bio)Statistics</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html">Class Information</a></li>
<li><a class="" href="rfunc.html"><span class="header-section-number">1</span> R functions</a></li>
<li><a class="" href="intro.html"><span class="header-section-number">2</span> Introduction</a></li>
<li><a class="" href="regdesc.html"><span class="header-section-number">3</span> Correlation &amp; Regression as Models</a></li>
<li><a class="" href="foundations-for-inference.html"><span class="header-section-number">4</span> Foundations for Inference</a></li>
<li><a class="" href="inference-for-categorical-data.html"><span class="header-section-number">5</span> Inference for categorical data</a></li>
<li><a class="" href="inference-for-numerical-data.html"><span class="header-section-number">6</span> Inference for numerical data</a></li>
<li><a class="active" href="reginf.html"><span class="header-section-number">7</span> Inference on Correlation &amp; Regression</a></li>
<li><a class="" href="interlude-in-spring-2020.html"><span class="header-section-number">8</span> Interlude in Spring 2020</a></li>
<li><a class="" href="references.html">References</a></li>
</ul>

        <div class="book-extra">
          <p><a id="book-repo" href="https://github.com/hardin47/website">View book source <i class="fab fa-github"></i></a></p>
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="reginf" class="section level1" number="7">
<h1>
<span class="header-section-number">7</span> Inference on Correlation &amp; Regression<a class="anchor" aria-label="anchor" href="#reginf"><i class="fas fa-link"></i></a>
</h1>
<!--
## 4/16/20 Agenda {#Apr16}
1. Definition of correlation (r)
2. Interpretation of correlation (r)  
3. (Probably not: Inference on $\rho$)
-->
<p>The last topic of the semester will focus on inference in the setting with two quantitative variables. That is, both the explanatory and the response variables are measured on a numeric scale, we model them using correlation and least square regression, and then we ask whether the lines could have come from a population with no relationship (i.e., the null hypothesis).</p>
<div id="inference-for-correlation" class="section level3" number="7.0.1">
<h3>
<span class="header-section-number">7.0.1</span> Inference for correlation<a class="anchor" aria-label="anchor" href="#inference-for-correlation"><i class="fas fa-link"></i></a>
</h3>
<p>Correlation measures the association between two numerical variables. [Note, that when describing how two categorical (or one numerical &amp; one categorical) variables vary together, they are said to be <em>associated</em> instead of <em>correlated</em>.]</p>
<blockquote>
<p>The <em>correlation coefficient</em> measures the strength and direction of the linear association between two numerical variables.</p>
</blockquote>
<p>Note: we won’t actually cover inference for correlation in class, but the notes on inference for correlation are included so that you can see that the process is very similar to all of the other statistics seen in the course to this point.</p>
<p>Parameter: <span class="math inline">\(\rho\)</span><br>
Statistic: <span class="math inline">\(r\)</span><br>
SE<span class="math inline">\(_r: \sqrt{\frac{1-r^2}{n-2}}\)</span><br><strong>BUT</strong>, <span class="math inline">\(r\)</span> is only normally distributed when <span class="math inline">\(\rho\)</span> = 0! Otherwise, the distribution of <span class="math inline">\(r\)</span> from sample to sample is skewed (think about the scenario when <span class="math inline">\(\rho = 0.9\)</span>).</p>
<div id="hypothesis-testing" class="section level4" number="7.0.1.1">
<h4>
<span class="header-section-number">7.0.1.1</span> Hypothesis Testing<a class="anchor" aria-label="anchor" href="#hypothesis-testing"><i class="fas fa-link"></i></a>
</h4>
<p><span class="math display">\[\begin{eqnarray*}
H_0:&amp;&amp; \rho = 0\\
H_A:&amp;&amp; \rho \ne 0\\
t^* &amp;=&amp; \frac{r}{SE_r} = \frac{r}{\sqrt{(1-r^2)/(n-2)}}\\
t^* &amp;\sim&amp; t_{n-2}  \mbox{ when } H_0 \mbox{ is true}
\end{eqnarray*}\]</span></p>
</div>
<div id="confidence-interval" class="section level4" number="7.0.1.2">
<h4>
<span class="header-section-number">7.0.1.2</span> Confidence Interval<a class="anchor" aria-label="anchor" href="#confidence-interval"><i class="fas fa-link"></i></a>
</h4>
<p>If <span class="math inline">\(\rho \ne 0\)</span>, then the SE might be okay, but the sampling distribution of <span class="math inline">\(r\)</span> will not be normal (and thus will not be a <span class="math inline">\(t\)</span> when we use the SE).</p>
<p>Let:</p>
<p><span class="math display">\[\begin{eqnarray*}
z &amp;=&amp; 0.5 \ln \bigg( \frac{1+r}{1-r} \bigg)\\
\xi &amp;=&amp; 0.5 \ln \bigg( \frac{1+\rho}{1-\rho} \bigg)\\
var(z) &amp;=&amp; \sqrt{\frac{1}{n-3}}\\
95\% \mbox{ CI for } \xi : &amp;&amp;\\
z &amp;\pm&amp; 1.96 \cdot \sqrt{\frac{1}{n-3}}\\
\mbox{we're 95% confident that } &amp;&amp; \\
&amp;&amp;z - 1.96 \cdot  \sqrt{\frac{1}{n-3}} \leq \xi \leq z + 1.96 \cdot \sqrt{\frac{1}{n-3}}\\
&amp;&amp; a \leq \xi \leq b\\
&amp;&amp; a \leq 0.5 \ln \bigg(\frac{1+\rho}{1-\rho} \bigg) \leq b\\
&amp;&amp; \frac{e^{2a} - 1}{e^{2a} + 1} \leq \rho \leq \frac{e^{2b} - 1}{e^{2b} + 1}
\end{eqnarray*}\]</span></p>
<p>See the Cat Jumping<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;span class="citation"&gt;&lt;a href="references.html#ref-iscam" role="doc-biblioref"&gt;Chance and Rossman&lt;/a&gt; (&lt;a href="references.html#ref-iscam" role="doc-biblioref"&gt;2018&lt;/a&gt;)&lt;/span&gt;, Inv 5.6 &amp;amp; 5.13&lt;/p&gt;'><sup>25</sup></a> example below in section <a href="reginf.html#ex:cat2">7.3.1</a>.</p>
<p><strong>HT:</strong><br><span class="math display">\[\begin{eqnarray*}
H_0:&amp;&amp; \rho = 0\\
H_a:&amp;&amp; \rho \ne 0\\
t^* &amp;=&amp; \frac{r}{\sqrt{(1-r^2)/(n-2)}} = \frac{-0.496}{\sqrt{(1-0.496^2) / (18-2)}}= -2.2849\\
p-value &amp;=&amp; 2 \cdot P(t_{18-2} \leq -2.2849) = 2\cdot(pt(-2.2849,16)) = 0.036 \mbox{  (borderline significant)}
\end{eqnarray*}\]</span></p>
<p><strong>CI:</strong><br><span class="math display">\[\begin{eqnarray*}
95\% \mbox{CI for } \xi :&amp;&amp; \\
z \pm 1.96 \cdot \sqrt{\frac{1}{n-3}}&amp;&amp; \\
\mbox{we're } 95\% \mbox{ confident that}&amp;&amp;\\
 0.5 \ln\bigg(\frac{1+r}{1-r}\bigg) - 1.96 \cdot  \sqrt{\frac{1}{n-3}} &amp;\leq \xi \leq&amp; 0.5 \ln\bigg(\frac{1+r}{1-r}\bigg) + 1.96 \cdot \sqrt{\frac{1}{n-3}}\\
 0.5 \ln\bigg(\frac{1 - 0.496}{1+0.496}\bigg) - 1.96 \cdot  \sqrt{\frac{1}{18-3}} &amp;\leq \xi \leq &amp;0.5 \ln\bigg(\frac{1-0.496}{1+0.496}\bigg) + 1.96 \cdot \sqrt{\frac{1}{18-3}}\\
 -1.05 &amp;\leq \xi \leq &amp;-0.04\\
 \frac{e^{2\cdot -1.05} - 1}{e^{2\cdot -1.05} + 1} &amp;\leq \rho \leq&amp; \frac{e^{2\cdot -0.04} - 1}{e^{2\cdot -0.04} + 1}\\
&amp;&amp; (-0.781, -0.04)
\end{eqnarray*}\]</span></p>
<!--
## 4/21/20 Agenda {#Apr21}
1. Least Squares estimation of the line
2. Distribution of the least squares line from sample to sample

## 4/23/20 Agenda {#Apr23}
1. Inferential technical conditions
2. Residual Plots
3. Transformations
4. Prediction Intervals
-->
</div>
</div>
<div id="simple-linear-regression-1" class="section level2" number="7.1">
<h2>
<span class="header-section-number">7.1</span> Simple Linear Regression<a class="anchor" aria-label="anchor" href="#simple-linear-regression-1"><i class="fas fa-link"></i></a>
</h2>
<p><em>Regression</em> is a method that predicts the value of one numerical variable from that of another. That is, as an extension to describing the degree of linearity of the relationship (correlation), the goal is now to create the best linear model – often for prediction. Note that many of the characteristics explored with correlation are applicable for regression. However, correlation treats <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> as interchangeable, whereas regression treats <span class="math inline">\(X\)</span> as fixed and known and <span class="math inline">\(Y\)</span> as random and unknown. As we have previously, we call <span class="math inline">\(X\)</span> the explanatory variable, and <span class="math inline">\(Y\)</span> the response variable. Again, we do not assume that there is any causal mechanism between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> even if they have a strong linear (or otherwise) relationship.</p>
<div id="population-model" class="section level4 unnumbered">
<h4>Population Model<a class="anchor" aria-label="anchor" href="#population-model"><i class="fas fa-link"></i></a>
</h4>
<p>Notice the Greek letters representing parameters:</p>
<p><span class="math display">\[\begin{eqnarray*}
E[y|x] &amp;=&amp; \beta_0 + \beta_1 x \\
y_i &amp;=&amp; \beta_0 + \beta_1 x_i + \epsilon_i\\
\epsilon_i &amp;=&amp; y_i -  (\beta_0 + \beta_1 x_i)\\
\end{eqnarray*}\]</span></p>
</div>
<div id="predicted-values-1" class="section level4 unnumbered">
<h4>Predicted Values<a class="anchor" aria-label="anchor" href="#predicted-values-1"><i class="fas fa-link"></i></a>
</h4>
<p>The predicted values of Y from a regression line estimate the <em>mean value</em> of <span class="math inline">\(Y\)</span> for all individuals that have a given value of <span class="math inline">\(X\)</span>. Notice the Roman letters (English letters) representing statistics:</p>
<p><span class="math display">\[\begin{eqnarray*}
\hat{y} &amp;=&amp; b_0 + b_1 x\\
\hat{y}_i &amp;=&amp; b_0 + b_1 x_i\\
y_i &amp;=&amp; b_0 + b_1 x_i + e_i\\
e_i &amp;=&amp; y_i - \hat{y}_i = y_i -  (b_0 + b_1 x_i)\\
\end{eqnarray*}\]</span></p>
<p>Notice, that we are predicting the <strong>mean</strong> value of the response variable at a given value of the explanatory variable!</p>
</div>
<div id="infbeta1" class="section level3" number="7.1.1">
<h3>
<span class="header-section-number">7.1.1</span> Inference on the slope, <span class="math inline">\(\beta_1\)</span><a class="anchor" aria-label="anchor" href="#infbeta1"><i class="fas fa-link"></i></a>
</h3>
<p>As in section <a href="regdesc.html#ls">3.2.1</a>, the slope is calculated by using least squares.</p>
<div id="se-of-the-slope" class="section level4 unnumbered">
<h4>SE of the slope<a class="anchor" aria-label="anchor" href="#se-of-the-slope"><i class="fas fa-link"></i></a>
</h4>
<p><span class="math display">\[\begin{eqnarray*}
SE(b_1) &amp;=&amp; \sqrt{\frac{MSE}{\sum_i (x_i - \overline{x})^2}} = \sqrt{\frac{MSE}{(n-1)s_x^2}} = = \sqrt{\frac{\frac{\sum_i (y_i - \hat{y}_i)^2}{n-2}}{(n-1)s_x^2}}\\
\end{eqnarray*}\]</span></p>
<p>Just like any other statistic, the value of <span class="math inline">\(b_1\)</span> can be calculated for every sample. The manner in which <span class="math inline">\(b_1\)</span> varies from sample to sample becomes the sampling distribution of the sample slope. The SE of the slope will be the standard deviation associated with the sampling distribution of the slope. The resulting inference theory is very similar to that which we saw with the mean. The CLT describes <span class="math inline">\(b_1\)</span> to have a normal distribution, and estimating the <span class="math inline">\(SE(b_1)\)</span> induces extra variability which leads to a t-score test statistic with a t-distribution with df = <span class="math inline">\(n-2\)</span>.</p>
<p><span class="math display">\[\begin{eqnarray*}
\mbox{t-score} = \frac{b_1 - \beta_1}{SE(b_1)} \sim t_{n-2}
\end{eqnarray*}\]</span></p>
</div>
<div id="ci-for-the-slope" class="section level4 unnumbered">
<h4>CI for the slope<a class="anchor" aria-label="anchor" href="#ci-for-the-slope"><i class="fas fa-link"></i></a>
</h4>
<p><span class="math display">\[\begin{eqnarray*}
b_1- t^*_{\alpha/2, n-2} SE(b_1) \leq \beta_1 \leq b_1 + t^*_{\alpha/2, n-2} SE(b_1)
\end{eqnarray*}\]</span></p>
<p>See the Housing Prices<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;span class="citation"&gt;&lt;a href="references.html#ref-iscam" role="doc-biblioref"&gt;Chance and Rossman&lt;/a&gt; (&lt;a href="references.html#ref-iscam" role="doc-biblioref"&gt;2018&lt;/a&gt;)&lt;/span&gt;, Inv 5.14&lt;/p&gt;'><sup>26</sup></a> example below in section <a href="reginf.html#ex:houses2">7.3.2</a>.</p>
<p><span class="math display">\[\begin{eqnarray*}
t_{\alpha/2,n-2} &amp;=&amp; qt(.975, 18-2) = 2.1199\\
SE(b_1) &amp;=&amp; 26.4\\
b_1 &amp;=&amp; 202\\
b_1 &amp;\pm&amp; t_{\alpha/2, n-2} SE(b_1): 202 \pm 2.1199 \cdot 26.4\\
&amp;&amp; (146.03, 257.97)\\
\end{eqnarray*}\]</span></p>
<p>That is, we are 95% confident that the true average change in price associated with an additional square foot of house is between $146.03 and $257.97.</p>
</div>
<div id="ht-for-the-slope" class="section level4 unnumbered">
<h4>HT for the slope<a class="anchor" aria-label="anchor" href="#ht-for-the-slope"><i class="fas fa-link"></i></a>
</h4>
<p>As mentioned previously,
<span class="math display">\[\begin{eqnarray*}
\mbox{t-score} = \frac{b_1 - \beta_1}{SE(b_1)} \sim t_{n-2}
\end{eqnarray*}\]</span></p>
<p>Typically, interested is in testing whether or not the slope is zero. The null hypothesis of <span class="math inline">\(H_0: \beta_1 = 0\)</span> addresses whether there is a non-zero linear relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>:</p>
<p><span class="math display">\[\begin{eqnarray*}
H_0:&amp;&amp; \mbox{ the slope of the regression line is zero}, \beta_1=0\\
H_A:&amp;&amp; \mbox{ the slope of the regression line is not zero}, \beta_1 \ne 0\\
\end{eqnarray*}\]</span></p>
<p>As with previous tests, the alternative can be one- or two-sided (depending on the research question).</p>
<p>Again, back to the housing data… (consider a two sided test)
<span class="math display">\[\begin{eqnarray*}
t^* &amp;=&amp; 7.67\\
p-value &amp;=&amp; 2 \cdot P(t_{16} \geq 7.67) = 2 \cdot (1-pt(7.67, 16)) \approx 0
\end{eqnarray*}\]</span></p>
</div>
</div>
<div id="lmtechcond" class="section level3" number="7.1.2">
<h3>
<span class="header-section-number">7.1.2</span> Regression Technical Conditions<a class="anchor" aria-label="anchor" href="#lmtechcond"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>
<strong>L:</strong> At each value of X, there is a population of possible Y-values whose mean lies on the “true” regression line (<strong>linearity</strong>)</li>
<li>
<strong>I:</strong> At each value of X, the Y-measurements represent a random sample from the population of possible Y-values (<strong>independence</strong>) [Consider this example of lack of independence. The researcher is trying to determine whether the number of pieces in a puzzle is linearly associated with the time to complete the puzzle. At first we choose 2 people and let them do 10 puzzles each. Then we let 20 independent people do the puzzles. The first experiment will create a slope which is particular to the two people sampled (it may or may not be close to the parameter). The second one will create a slope close to the 20 people sampled. Note that the effective variability of the first model is based on n=2, but we <em>think</em> it is based on n=20 (if we don’t notice the lack of independence). The second slope is based on n=20, and so it will have the correct associated variability.]</li>
<li>
<strong>N:</strong> At each value of X, the distribution of possible Y-values is normal (<strong>normality</strong>)</li>
<li>
<strong>E:</strong> The variance of Y-values is the same at all values of X (<strong>equal variance</strong>)</li>
</ul>
<div id="residual-plots" class="section level4 unnumbered">
<h4>Residual Plots<a class="anchor" aria-label="anchor" href="#residual-plots"><i class="fas fa-link"></i></a>
</h4>
<p>Within a residual plot, you should be looking for the same types of things you want in a scatter plot. [See the residual plots provided in section <a href="reginf.html#ex:cat2">7.3.1</a>.]</p>
<ul>
<li>a roughly symmetric cloud of points above and below the horizontal line at zero, with a higher density of points close to the line than far from the line,<br>
</li>
<li>little noticeable curvature as we move from left to right along the X-axis, and<br>
</li>
<li>approximately equal variance of points above and below the line at all values of X.</li>
</ul>
<!--
## 4/28/20 Agenda {#Apr28}
1. Multiple Linear Regression

## 4/30/20 Agenda {#Apr30}
1. Choosing model
2. Residual Plots
3. Prediction Intervals (harder to plot!)
-->
</div>
</div>
</div>
<div id="MLR" class="section level2" number="7.2">
<h2>
<span class="header-section-number">7.2</span> Multiple Linear Regression<a class="anchor" aria-label="anchor" href="#MLR"><i class="fas fa-link"></i></a>
</h2>
<p>As with simple linear regression, consider <span class="math inline">\(n\)</span> observations. The response variable for the <span class="math inline">\(i^{th}\)</span> individual is denoted by <span class="math inline">\(Y_i\)</span>, as before. The variation remaining in <span class="math inline">\(Y_i\)</span> that isn’t explained by our predictors will also remain the same, denoted by <span class="math inline">\(\epsilon_i\)</span> and called the random error. Since we now have more than one explanatory variable, we will need to add an additional subscript on <span class="math inline">\(X\)</span>, denoting the value of the <span class="math inline">\(k^{th}\)</span> predictor variable for the <span class="math inline">\(i^{th}\)</span> individual by <span class="math inline">\(X_{ik}\)</span>. Thus our model is now</p>
<p><span class="math display">\[\begin{eqnarray*}
Y_i&amp;=&amp;\beta_0+\beta_1X_{i1}+\beta_2X_{i2}+ \cdots + \beta_{p-1}X_{i,p-1} + \epsilon_i\\
E[Y]&amp;=&amp;\beta_0+\beta_1X_{1}+\beta_2X_{2}+ \cdots + \beta_{p-1}X_{p-1}\\
Y_i&amp;=&amp;b_0+b_1X_{i1}+b_2X_{i2}+ \cdots + b_{p-1}X_{i,p-1} + e_i\\
\widehat{Y}&amp;=&amp;b_0+b_1X_{1}+b_2X_{2}+ \cdots + b_{p-1}X_{p-1}\\
\end{eqnarray*}\]</span></p>
<div id="fitting-the-model" class="section level4 unnumbered">
<h4>Fitting the Model<a class="anchor" aria-label="anchor" href="#fitting-the-model"><i class="fas fa-link"></i></a>
</h4>
<p>To estimate the coefficients, use the same principle as before, that of least squares. That is, minimize
<span class="math display">\[\sum_{i=1}^n(Y_i-(b_0+b_1X_{i1}+b_2X_{i2} + \cdots + b_{p-1}X_{i,p-1}))^2\]</span>
We are interested in finding the least squares estimates (<span class="math inline">\(b_i\)</span>) of the parameters of the model <span class="math inline">\(\beta_i\)</span>.</p>
</div>
<div id="MLRmod" class="section level3" number="7.2.1">
<h3>
<span class="header-section-number">7.2.1</span> Model selection<a class="anchor" aria-label="anchor" href="#MLRmod"><i class="fas fa-link"></i></a>
</h3>
<p>While there are many aspects of a linear model to consider (we offer an entire course! Math 158: Linear models), here we will focus on interpreting and testing single coefficients in the model.</p>
<p>Consider the following model (based on R housing example below). We are predicting the price of a home (in <span class="math inline">\(\ln\)</span> units).</p>
<p><span class="math display">\[\widehat{Y} = 12.2 + 0.000468 \cdot \mbox{sqft} - 0.0603 \cdot \mbox{# bedrooms}\]</span></p>
<p>Now, let’s compare two houses. The two houses have the exact same square feet (note, it doesn’t matter what the square feet is!!). House 1 (H1) has 4 bedrooms, house 2 (H2) has 3 bedrooms.</p>
<p>The coefficient associated with the number of bedrooms indicates the change in price (in <span class="math inline">\(\ln\)</span> units) <strong>keeping all other variables constant</strong>. That is, if comparing the prediction of the average price of a home for two homes that have the same square feet but a one unit difference in bedrooms, the price of the home is predicted to be -0.0603 <span class="math inline">\(\ln\)</span> units less for the home with more bedrooms. (Does that seem to make sense? Same square feet, more bedrooms chop up the house and make it less desirable maybe?)</p>
<p><span class="math display">\[\begin{eqnarray*}
\widehat{Y}_{H1} &amp;=&amp; 12.2 + 0.000468 \cdot \mbox{sqft} - 0.0603 \cdot 4\\
\widehat{Y}_{H2} &amp;=&amp; 12.2 + 0.000468 \cdot \mbox{sqft} - 0.0603 \cdot 3\\
\widehat{Y}_{H1} - \widehat{Y}_{H2} &amp;=&amp; (-0.0603 \cdot 4) - (-0.0603 \cdot 3) =  -0.0603\\
\end{eqnarray*}\]</span></p>
<div class="sourceCode" id="cb190"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">house</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span><span class="op">(</span><span class="st">"http://www.rossmanchance.com/iscam2/data/housing.txt"</span>, 
                   header<span class="op">=</span><span class="cn">TRUE</span>, sep<span class="op">=</span><span class="st">"\t"</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span> <span class="op">~</span> <span class="va">sqft</span> <span class="op">+</span> <span class="va">bedrooms</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term         estimate std.error statistic  p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept) 12.2      0.174         70.1  1.39e-73
## 2 sqft         0.000468 0.0000660      7.09 4.73e-10
## 3 bedrooms    -0.0603   0.0572        -1.05 2.95e- 1</code></pre>
<div id="inference-about-regression-parameters" class="section level4 unnumbered">
<h4>Inference about Regression Parameters<a class="anchor" aria-label="anchor" href="#inference-about-regression-parameters"><i class="fas fa-link"></i></a>
</h4>
<p>However, the coefficient on <code>bedrooms</code> isn’t significant (that is, the associated p-value is larger than any reasonable level of significance, like <span class="math inline">\(\alpha = 0.05\)</span>). But wait, how is the p-value even calculated?</p>
<p>The least squares coefficient estimate and the SE create a test statistic that will have a t distribution when the null hypothesis is true (note that we are now estimating <span class="math inline">\(p\)</span> parameters, so our degrees of freedom is <span class="math inline">\(n-p\)</span>).</p>
<p><span class="math display">\[\begin{eqnarray*}
\frac{b_k - \beta_k}{SE(b_k)} \sim t_{(n-p)}
\end{eqnarray*}\]</span>
A <span class="math inline">\((1-\alpha)100\%\)</span> CI for <span class="math inline">\(\beta_k\)</span> is given by<span class="math display">\[b_k \pm t_{(1-\alpha/2, n-p)} SE(b_k)\]</span></p>
<p>The t-test is done separately for EACH <span class="math inline">\(\beta\)</span> coefficient. The test addresses the effect of removing only the variable at hand. Both testing and interpretation of the regression coefficients are done <strong>with all other variables in the model</strong>.</p>
<p>The coefficient on <code>bedrooms</code> is not significant <strong>given <code>sqft</code> is in the model</strong>. Note that if we don’t have <code>sqft</code>, then bedrooms acts as a surrogate for <code>sqft</code> and it <em>is</em> important (and significant!). In this case, however, <code>sqft</code> is a better predictor than <code>bedrooms</code>.</p>
<div class="sourceCode" id="cb192"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span> <span class="op">~</span>  <span class="va">bedrooms</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)   12.3      0.219      56.3  1.03e-66
## 2 bedrooms       0.178    0.0587      3.03 3.31e- 3</code></pre>
</div>
<div id="which-variables-to-choose" class="section level4 unnumbered">
<h4>Which variables to choose?<a class="anchor" aria-label="anchor" href="#which-variables-to-choose"><i class="fas fa-link"></i></a>
</h4>
<p>Again, there are numerous ways to build a model. Some important principles to keep in mind:</p>
<ul>
<li>ideally the variables in the model are significant (remove variables with high p-values)</li>
<li>the LINE model conditions should hold (you may need to transform the response or explanatory variables)</li>
<li>the variables should be consistent with the data context (be sure that your analysis is done with experts in the field)</li>
</ul>
</div>
</div>
<div id="checking-model-assumptions" class="section level3" number="7.2.2">
<h3>
<span class="header-section-number">7.2.2</span> Checking model assumptions<a class="anchor" aria-label="anchor" href="#checking-model-assumptions"><i class="fas fa-link"></i></a>
</h3>
<p>As before, the LINE model conditions are checked by using residual plots. Note that in the housing example, the residual plot after log transformation on the response variable is improved.</p>
<div class="sourceCode" id="cb194"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span>
<span class="va">house</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span><span class="op">(</span><span class="st">"http://www.rossmanchance.com/iscam2/data/housing.txt"</span>, 
                   header<span class="op">=</span><span class="cn">TRUE</span>, sep<span class="op">=</span><span class="st">"\t"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>ln_price <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">price</span> <span class="op">~</span>  <span class="va">sqft</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span>  <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span> <span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Residual plot for price as a function of sqft"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-3-1.png" width="480" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb195"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">ln_price</span> <span class="op">~</span>  <span class="va">sqft</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span>  <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span> <span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span><span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Residual plot for ln price as a function of sqft"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-4-1.png" width="480" style="display: block; margin: auto;"></div>
</div>
</div>
<div id="r-code-for-regression-1" class="section level2" number="7.3">
<h2>
<span class="header-section-number">7.3</span> R code for regression<a class="anchor" aria-label="anchor" href="#r-code-for-regression-1"><i class="fas fa-link"></i></a>
</h2>
<div id="ex:cat2" class="section level3" number="7.3.1">
<h3>
<span class="header-section-number">7.3.1</span> Example: Cat Jumping<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;span class="citation"&gt;&lt;a href="references.html#ref-iscam" role="doc-biblioref"&gt;Chance and Rossman&lt;/a&gt; (&lt;a href="references.html#ref-iscam" role="doc-biblioref"&gt;2018&lt;/a&gt;)&lt;/span&gt;, Inv 5.6 &amp;amp; 5.13&lt;/p&gt;'><sup>27</sup></a> (Correlation &amp; SLR)<a class="anchor" aria-label="anchor" href="#ex:cat2"><i class="fas fa-link"></i></a>
</h3>
<p>Consider the cat data given in Investigations 5.6 and 5.13. The idea is to understand cat jumping velocity as a function of body characteristics. Note that the correlation <span class="math inline">\(r=-0.496\)</span> between bodymass and velocity.</p>
<div class="sourceCode" id="cb196"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cats</span> <span class="op">&lt;-</span> <span class="fu">read_table2</span><span class="op">(</span><span class="st">"http://www.rossmanchance.com/iscam2/data/CatJumping.txt"</span><span class="op">)</span>

<span class="fu">ggplot</span><span class="op">(</span><span class="va">cats</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">bodymass</span>, y <span class="op">=</span> <span class="va">velocity</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_smooth</span><span class="op">(</span>method <span class="op">=</span> <span class="st">"lm"</span>, se<span class="op">=</span><span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-5-1.png" width="480" style="display: block; margin: auto;"></div>
<div id="correlation-1" class="section level4 unnumbered">
<h4>Correlation<a class="anchor" aria-label="anchor" href="#correlation-1"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb197"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cats</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">bodymass</span>, <span class="va">velocity</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://projectmosaic.github.io/mosaic/reference/aggregating.html">cor</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##            bodymass   velocity
## bodymass  1.0000000 -0.4964022
## velocity -0.4964022  1.0000000</code></pre>
</div>
<div id="simple-linear-regression-2" class="section level4 unnumbered">
<h4>Simple Linear Regression<a class="anchor" aria-label="anchor" href="#simple-linear-regression-2"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb199"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">velocity</span> <span class="op">~</span> <span class="va">bodymass</span>, data <span class="op">=</span> <span class="va">cats</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = velocity ~ bodymass, data = cats)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -48.069 -16.729  -8.524  10.546  84.625 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 394.473238  23.441939  16.828 1.35e-11 ***
## bodymass     -0.012196   0.005332  -2.287   0.0361 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 29.6 on 16 degrees of freedom
## Multiple R-squared:  0.2464, Adjusted R-squared:  0.1993 
## F-statistic: 5.232 on 1 and 16 DF,  p-value: 0.03613</code></pre>
<p>An alternative way to work with the output is in specific pieces (instead of the entire summary output).</p>
<div class="sourceCode" id="cb201"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://broom.tidymodels.org/">broom</a></span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">velocity</span> <span class="op">~</span> <span class="va">bodymass</span>, data <span class="op">=</span> <span class="va">cats</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span>conf.int <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 7
##   term        estimate std.error statistic  p.value conf.low  conf.high
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;
## 1 (Intercept) 394.      23.4         16.8  1.35e-11 345.     444.      
## 2 bodymass     -0.0122   0.00533     -2.29 3.61e- 2  -0.0235  -0.000893</code></pre>
</div>
<div id="residual-plot-1" class="section level4 unnumbered">
<h4>Residual Plot<a class="anchor" aria-label="anchor" href="#residual-plot-1"><i class="fas fa-link"></i></a>
</h4>
<p>And to work with the residuals, use <code><a href="https://generics.r-lib.org/reference/augment.html">augment()</a></code>.</p>
<div class="sourceCode" id="cb203"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">velocity</span> <span class="op">~</span> <span class="va">bodymass</span>, data <span class="op">=</span> <span class="va">cats</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 18 x 8
##    velocity bodymass .fitted .resid .std.resid   .hat .sigma   .cooksd
##       &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
##  1     334.     3640    350. -15.6     -0.545  0.0656   30.3 0.0104   
##  2     387.     2670    362.  25.4      0.920  0.131    29.7 0.0640   
##  3     411.     5600    326.  84.6      3.05   0.119    19.8 0.629    
##  4     319.     4130    344. -25.5     -0.887  0.0557   29.8 0.0232   
##  5     369.     3020    358.  11.1      0.394  0.101    30.4 0.00867  
##  6     359.     2660    362.  -3.23    -0.117  0.132    30.6 0.00105  
##  7     345.     3240    355. -10.4     -0.366  0.0853   30.4 0.00624  
##  8     325.     5140    332.  -7.19    -0.254  0.0844   30.5 0.00297  
##  9     301.     3690    349. -48.1     -1.68   0.0639   27.7 0.0962   
## 10     332.     3620    350. -18.5     -0.648  0.0664   30.2 0.0149   
## 11     313.     5310    330. -17.1     -0.608  0.0957   30.2 0.0196   
## 12     317.     5560    327.  -9.86    -0.354  0.116    30.4 0.00823  
## 13     376.     3970    346.  29.5      1.03   0.0572   29.5 0.0321   
## 14     372.     3770    348.  23.9      0.834  0.0615   29.9 0.0228   
## 15     314.     5100    332. -18.0     -0.634  0.0820   30.2 0.0179   
## 16     368.     2950    358.   9.01     0.322  0.106    30.5 0.00614  
## 17     286.     7930    298. -11.5     -0.552  0.508    30.3 0.157    
## 18     352.     3550    351.   1.32     0.0463 0.0692   30.6 0.0000797</code></pre>
<div class="sourceCode" id="cb205"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">velocity</span> <span class="op">~</span> <span class="va">bodymass</span>, data <span class="op">=</span> <span class="va">cats</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-9-1.png" width="480" style="display: block; margin: auto;"></div>
</div>
<div id="confidence-prediction-intervals" class="section level4 unnumbered">
<h4>Confidence &amp; Prediction Intervals<a class="anchor" aria-label="anchor" href="#confidence-prediction-intervals"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb206"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">m_cats</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">velocity</span> <span class="op">~</span> <span class="va">bodymass</span>, data <span class="op">=</span> <span class="va">cats</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">m_cats</span>, newdata<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>bodymass<span class="op">=</span><span class="fl">4700</span><span class="op">)</span>, interval<span class="op">=</span><span class="st">"confidence"</span><span class="op">)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 337.1514 321.3081 352.9947</code></pre>
<div class="sourceCode" id="cb208"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">m_cats</span>, newdata<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>bodymass<span class="op">=</span><span class="fl">4700</span><span class="op">)</span>, interval<span class="op">=</span><span class="st">"prediction"</span><span class="op">)</span></code></pre></div>
<pre><code>##        fit      lwr     upr
## 1 337.1514 272.4378 401.865</code></pre>
<div id="plotting-1" class="section level5 unnumbered">
<h5>Plotting!<a class="anchor" aria-label="anchor" href="#plotting-1"><i class="fas fa-link"></i></a>
</h5>
<div class="sourceCode" id="cb210"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">catConf</span> <span class="op">&lt;-</span> <span class="va">m_cats</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">m_cats</span>, interval<span class="op">=</span><span class="st">"confidence"</span><span class="op">)</span> <span class="op">)</span>  <span class="co"># cbind binds the columns together</span>

<span class="va">catConf</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   velocity bodymass  .fitted     .resid .std.resid       .hat   .sigma
## 1    334.5     3640 350.0793 -15.579293 -0.5445423 0.06563257 30.28374
## 2    387.3     2670 361.9095  25.390452  0.9203785 0.13125270 29.74812
## 3    410.8     5600 326.1749  84.625139  3.0468951 0.11941906 19.80527
## 4    318.6     4130 344.1032 -25.503185 -0.8867122 0.05570221 29.80778
## 5    368.7     3020 357.6409  11.059101  0.3939761 0.10053270 30.41969
## 6    358.8     2660 362.0315  -3.231509 -0.1172061 0.13224725 30.55520
##       .cooksd      fit      lwr      upr
## 1 0.010414418 350.0793 334.0049 366.1536
## 2 0.063990821 361.9095 339.1781 384.6410
## 3 0.629490813 326.1749 304.4923 347.8574
## 4 0.023189898 344.1032 329.2947 358.9116
## 5 0.008674247 357.6409 337.7467 377.5351
## 6 0.001046793 362.0315 339.2141 384.8490</code></pre>
<div class="sourceCode" id="cb212"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">catConf</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">bodymass</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y<span class="op">=</span><span class="va">velocity</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y<span class="op">=</span><span class="va">.fitted</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_ribbon</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>ymin<span class="op">=</span><span class="va">lwr</span>, ymax<span class="op">=</span><span class="va">upr</span><span class="op">)</span>, fill<span class="op">=</span><span class="st">"blue"</span>, alpha<span class="op">=</span><span class="fl">0.2</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-11-1.png" width="480" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb213"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">catPred</span> <span class="op">&lt;-</span> <span class="va">m_cats</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">m_cats</span>, interval<span class="op">=</span><span class="st">"prediction"</span><span class="op">)</span> <span class="op">)</span>  <span class="co"># cbind binds the columns together</span>

<span class="va">catPred</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   velocity bodymass  .fitted     .resid .std.resid       .hat   .sigma
## 1    334.5     3640 350.0793 -15.579293 -0.5445423 0.06563257 30.28374
## 2    387.3     2670 361.9095  25.390452  0.9203785 0.13125270 29.74812
## 3    410.8     5600 326.1749  84.625139  3.0468951 0.11941906 19.80527
## 4    318.6     4130 344.1032 -25.503185 -0.8867122 0.05570221 29.80778
## 5    368.7     3020 357.6409  11.059101  0.3939761 0.10053270 30.41969
## 6    358.8     2660 362.0315  -3.231509 -0.1172061 0.13224725 30.55520
##       .cooksd      fit      lwr      upr
## 1 0.010414418 350.0793 285.3088 414.8498
## 2 0.063990821 361.9095 295.1746 428.6445
## 3 0.629490813 326.1749 259.7898 392.5599
## 4 0.023189898 344.1032 279.6352 408.5712
## 5 0.008674247 357.6409 291.8183 423.4635
## 6 0.001046793 362.0315 295.2672 428.7958</code></pre>
<div class="sourceCode" id="cb215"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">catPred</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">bodymass</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y<span class="op">=</span><span class="va">velocity</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y<span class="op">=</span><span class="va">.fitted</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_ribbon</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>ymin<span class="op">=</span><span class="va">lwr</span>, ymax<span class="op">=</span><span class="va">upr</span><span class="op">)</span>, fill<span class="op">=</span><span class="st">"blue"</span>, alpha<span class="op">=</span><span class="fl">0.2</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-12-1.png" width="480" style="display: block; margin: auto;"></div>
</div>
</div>
</div>
<div id="ex:houses2" class="section level3" number="7.3.2">
<h3>
<span class="header-section-number">7.3.2</span> Example: Housing Prices<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content='&lt;p&gt;&lt;span class="citation"&gt;&lt;a href="references.html#ref-iscam" role="doc-biblioref"&gt;Chance and Rossman&lt;/a&gt; (&lt;a href="references.html#ref-iscam" role="doc-biblioref"&gt;2018&lt;/a&gt;)&lt;/span&gt;, Inv 5.14&lt;/p&gt;'><sup>28</sup></a> (SLR &amp; MLR &amp; Prediction)<a class="anchor" aria-label="anchor" href="#ex:houses2"><i class="fas fa-link"></i></a>
</h3>
<div class="sourceCode" id="cb216"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggobi.github.io/ggally">GGally</a></span><span class="op">)</span>
<span class="va">house</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.table</a></span><span class="op">(</span><span class="st">"http://www.rossmanchance.com/iscam2/data/housing.txt"</span>, 
                   header<span class="op">=</span><span class="cn">TRUE</span>, sep<span class="op">=</span><span class="st">"\t"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>ln_price <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">house</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "sqft"     "price"    "City"     "bedrooms" "baths"    "ln_price"</code></pre>
<div id="descriptive-statistics-1" class="section level4 unnumbered">
<h4>Descriptive Statistics<a class="anchor" aria-label="anchor" href="#descriptive-statistics-1"><i class="fas fa-link"></i></a>
</h4>
<p>A good first step is to investigate how all the variables relate to one another. The <code>ggpairs</code> function come from the R package <code>GGally</code>.</p>
<div class="sourceCode" id="cb218"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://ggobi.github.io/ggally/reference/ggpairs.html">ggpairs</a></span><span class="op">(</span><span class="va">house</span>, columns <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span>,<span class="fl">4</span>,<span class="fl">5</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-14-1.png" width="480" style="display: block; margin: auto;"></div>
</div>
<div id="simple-linear-regression-3" class="section level4 unnumbered">
<h4>Simple Linear Regression<a class="anchor" aria-label="anchor" href="#simple-linear-regression-3"><i class="fas fa-link"></i></a>
</h4>
<div class="sourceCode" id="cb219"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod.sqft</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">price</span><span class="op">~</span><span class="va">sqft</span>, data <span class="op">=</span> <span class="va">house</span><span class="op">)</span>
<span class="va">mod.sqft</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   term        estimate std.error statistic  p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)   65930.   60994.       1.08 2.83e- 1
## 2 sqft            202.      26.4      7.67 3.35e-11</code></pre>
<div class="sourceCode" id="cb221"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod.bed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">price</span> <span class="op">~</span> <span class="va">bedrooms</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span>
<span class="va">mod.bed</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   term        estimate std.error statistic p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;
## 1 (Intercept)  220612.   107208.      2.06 0.0428 
## 2 bedrooms      76865.    28802.      2.67 0.00919</code></pre>
<p>The p-values for both explanatory variables (sqft and bedrooms) are significant. Sqft seems more significant, and indeed, the first model has a higher <span class="math inline">\(R^2\)</span> - that is, a higher proportion of the variability in price is explained by sqft (42.07%) than by number of bedrooms (8.08%).</p>
<div class="sourceCode" id="cb223"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod.sqft</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   r.squared adj.r.squared  sigma statistic  p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.421         0.414 2.22e5      58.8 3.35e-11     1 -1139. 2283. 2290.
## # … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb225"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod.bed</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   r.squared adj.r.squared  sigma statistic p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1    0.0808        0.0695 2.80e5      7.12 0.00919     1 -1158. 2321. 2329.
## # … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<p>However, it is important for us to ask whether either of the relationships actually fit the technical conditions of the linear regression model. We can see from the pairs plots that the relationships look <strong>L</strong>inear, we’ll assume the variables were collected <strong>I</strong>ndependently, but the <strong>N</strong>ormality and the <strong>E</strong>quality of the error structure we can check using residual plots.</p>
<div class="sourceCode" id="cb227"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod.sqft</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span> <span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span><span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Residual plot for price as a function of sqft"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-17-1.png" width="480" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb228"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod.bed</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span> <span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span><span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Residual plot for price as a function of bedrooms"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-17-2.png" width="480" style="display: block; margin: auto;"></div>
<p>For both of the plots, it seems like the residuals have higher variability for positive residuals. Additionally, it seems that the variability of the residuals increases for larger fitted observations.</p>
<p>A natural log transformation should fix both of these problems.</p>
<div class="sourceCode" id="cb229"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod.lnsqft</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">ln_price</span> <span class="op">~</span> <span class="va">sqft</span>, data <span class="op">=</span> <span class="va">house</span><span class="op">)</span>
<span class="va">mod.lnbed</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">ln_price</span> <span class="op">~</span> <span class="va">bedrooms</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb230"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod.lnsqft</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span> <span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span><span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Residual plot for ln(price) as a function of sqft"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-19-1.png" width="480" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb231"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">mod.lnbed</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span> <span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span><span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept<span class="op">=</span><span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"Residual plot for ln(price) as a function of bedrooms"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-19-2.png" width="480" style="display: block; margin: auto;"></div>
<p>Though no residual plot will ever look perfect, these residual plots seem to fit the technical conditions of the model better than the untransformed data.</p>
</div>
<div id="multiple-linear-regression" class="section level4 unnumbered">
<h4>Multiple Linear Regression<a class="anchor" aria-label="anchor" href="#multiple-linear-regression"><i class="fas fa-link"></i></a>
</h4>
<p>Because the price variable had a large skew (and the <code>ln()</code> transformation helped the residuals), the following models will all use <code>ln(price)</code> as the response variable. What happens when we try to predict <code>price</code> (actually <code>ln(price)</code>, here) using BOTH <code>sqft</code> and <code>bedrooms</code>?</p>
<p>Note: the natural log function in R is <code><a href="https://rdrr.io/r/base/Log.html">log()</a></code>.</p>
<div class="sourceCode" id="cb232"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span> <span class="op">~</span> <span class="va">sqft</span> <span class="op">+</span> <span class="va">bedrooms</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term         estimate std.error statistic  p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept) 12.2      0.174         70.1  1.39e-73
## 2 sqft         0.000468 0.0000660      7.09 4.73e-10
## 3 bedrooms    -0.0603   0.0572        -1.05 2.95e- 1</code></pre>
<div class="sourceCode" id="cb234"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span> <span class="op">~</span> <span class="va">sqft</span> <span class="op">+</span> <span class="va">bedrooms</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.448         0.435 0.450      32.5 4.62e-11     2  -50.0  108.  118.
## # … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb236"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span> <span class="op">~</span> <span class="va">sqft</span> <span class="op">+</span> <span class="va">baths</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term         estimate std.error statistic  p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept) 12.1      0.151        80.0   4.07e-78
## 2 sqft         0.000450 0.0000705     6.39  1.02e- 8
## 3 baths       -0.0377   0.0746       -0.505 6.15e- 1</code></pre>
<div class="sourceCode" id="cb238"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span> <span class="op">~</span> <span class="va">sqft</span> <span class="op">+</span> <span class="va">baths</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.443         0.429 0.452      31.8 7.07e-11     2  -50.4  109.  118.
## # … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<div class="sourceCode" id="cb240"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span> <span class="op">~</span> <span class="va">sqft</span> <span class="op">+</span> <span class="va">bedrooms</span> <span class="op">+</span> <span class="va">baths</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 4 x 5
##   term         estimate std.error statistic  p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept) 12.2      0.175        69.5   1.38e-72
## 2 sqft         0.000463 0.0000719     6.45  8.32e- 9
## 3 bedrooms    -0.0683   0.0730       -0.935 3.53e- 1
## 4 baths        0.0168   0.0947        0.177 8.60e- 1</code></pre>
<div class="sourceCode" id="cb242"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span> <span class="op">~</span> <span class="va">sqft</span> <span class="op">+</span> <span class="va">bedrooms</span> <span class="op">+</span> <span class="va">baths</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/glance.html">glance</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 12
##   r.squared adj.r.squared sigma statistic  p.value    df logLik   AIC   BIC
##       &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1     0.449         0.428 0.453      21.4 2.98e-10     3  -49.9  110.  122.
## # … with 3 more variables: deviance &lt;dbl&gt;, df.residual &lt;int&gt;, nobs &lt;int&gt;</code></pre>
<p><strong>Sqft &amp; bedrooms</strong></p>
<p>Although the <span class="math inline">\(R^2\)</span> value went up (44.84% of variability in log price is explained by sqft and bedrooms), the p-value on bedrooms isn’t significant. The p-value here can be interpreted as a hypothesis test on the slope coefficient given the other variables in the model.</p>
<p>0.353 = P(a slope of -.06827 or more extreme <em>if sqft is in the model</em> and there is no relationship between bedrooms and price)</p>
<p>Our output says that once we have sqft in the model, we don’t actually need to know anything about the number of bedrooms (even though bedrooms was a significant predictor on its own).</p>
<p><strong>Sqft &amp; bathrooms</strong></p>
<p>Seems like we <em>really</em> don’t need bathrooms! The information about <code>sqft</code> is sufficient for predicting the price, and information about bathrooms doesn’t help much at all.</p>
<p><strong>Final model</strong></p>
<p>The final model will be run on log(price) using only sqft. Note that the coefficients and the <span class="math inline">\(R^2\)</span> values change slightly (from the original analysis) because the response variable is logged.</p>
<div class="sourceCode" id="cb244"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mod.lnsqft</span><span class="op">)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = log(price) ~ sqft, data = house)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.08988 -0.29591 -0.05899  0.28717  1.20206 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1.204e+01  1.236e-01   97.36  &lt; 2e-16 ***
## sqft        4.274e-04  5.349e-05    7.99 7.87e-12 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.4502 on 81 degrees of freedom
## Multiple R-squared:  0.4407, Adjusted R-squared:  0.4338 
## F-statistic: 63.83 on 1 and 81 DF,  p-value: 7.874e-12</code></pre>
</div>
<div id="prediction" class="section level4 unnumbered">
<h4>Prediction<a class="anchor" aria-label="anchor" href="#prediction"><i class="fas fa-link"></i></a>
</h4>
<p>As with the prediction intervals we had when we had a single sample, we can now create intervals for either an average (a confidence interval) of an individual (a prediction interval).</p>
<div id="confidence-interval-1" class="section level5 unnumbered">
<h5>Confidence interval:<a class="anchor" aria-label="anchor" href="#confidence-interval-1"><i class="fas fa-link"></i></a>
</h5>
<div class="sourceCode" id="cb246"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mod.lnsqft</span>, newdata<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>sqft<span class="op">=</span><span class="fl">2000</span><span class="op">)</span>, interval<span class="op">=</span><span class="st">"confidence"</span><span class="op">)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 12.89125 12.79211 12.99038</code></pre>
<p>I am 95% confident that the true average log price for a 2000 sqft home is between 12.79 ln$ and 12.99 ln$. (The predicted value is in natural-log-dollars … which is hard to interpret , but back-transforming can be a little tricky and beyond the scope of this semester).</p>
</div>
<div id="prediction-interval" class="section level5 unnumbered">
<h5>Prediction interval:<a class="anchor" aria-label="anchor" href="#prediction-interval"><i class="fas fa-link"></i></a>
</h5>
<div class="sourceCode" id="cb248"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mod.lnsqft</span>, newdata<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>sqft<span class="op">=</span><span class="fl">2000</span><span class="op">)</span>, interval<span class="op">=</span><span class="st">"prediction"</span><span class="op">)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 12.89125 11.98994 13.79255</code></pre>
<p>I am 95% of homes with 2000 sqft are between 11.99 ln$ and 13.79 ln$. Now back-transforming is easy (because there are no averages), so 95% of homes with 2000 sqft are between $161,126 and $977,301 (which are just <span class="math inline">\(e^{11.98994}\)</span> and <span class="math inline">\(e^{13.79255}\)</span>).</p>
</div>
<div id="plotting-confidence-bounds" class="section level5 unnumbered">
<h5>Plotting confidence bounds:<a class="anchor" aria-label="anchor" href="#plotting-confidence-bounds"><i class="fas fa-link"></i></a>
</h5>
<p>A <strong>confidence</strong> interval around the line gives bounds on the parameter represented by the line. So we are 95% confident that the true population line lies within the bounds. Note that the interval is wider at the endpoints (because the variability is higher at the ends).</p>
<div class="sourceCode" id="cb250"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">houseConf</span> <span class="op">&lt;-</span> <span class="va">mod.lnsqft</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mod.lnsqft</span>, interval<span class="op">=</span><span class="st">"confidence"</span><span class="op">)</span> <span class="op">)</span>  <span class="co"># cbind binds the columns together</span>

<span class="va">houseConf</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   log(price) sqft  .fitted       .hat    .sigma      .cooksd  .std.resid
## 1   12.73376 3392 13.48618 0.03494894 0.4448768 5.240194e-02 -1.70116646
## 2   13.71004 4100 13.78878 0.06748451 0.4529518 1.186788e-03 -0.18110383
## 3   13.01398 3200 13.40412 0.02856505 0.4508768 1.136429e-02 -0.87917543
## 4   12.38839 1436 12.65019 0.01862011 0.4520790 3.268479e-03 -0.58696923
## 5   12.84133 1944 12.86731 0.01247712 0.4530341 2.130978e-05 -0.05807924
## 6   12.61120 1500 12.67755 0.01744506 0.4529817 1.961713e-04 -0.14865344
##        fit      lwr      upr
## 1 13.48618 13.31871 13.65366
## 2 13.78878 13.55606 14.02150
## 3 13.40412 13.25272 13.55553
## 4 12.65019 12.52795 12.77244
## 5 12.86731 12.76725 12.96738
## 6 12.67755 12.55923 12.79587</code></pre>
<div class="sourceCode" id="cb252"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">houseConf</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">sqft</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y<span class="op">=</span><span class="va">`log(price)`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y<span class="op">=</span><span class="va">.fitted</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_ribbon</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>ymin<span class="op">=</span><span class="va">lwr</span>, ymax<span class="op">=</span><span class="va">upr</span><span class="op">)</span>, fill<span class="op">=</span><span class="st">"blue"</span>, alpha<span class="op">=</span><span class="fl">0.2</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-26-1.png" width="480" style="display: block; margin: auto;"></div>
<p>A <strong>prediction</strong> interval around the line bounds the individual points. That is, 95% of the observations are captured inside the interval. As with the confidence interval, the prediction interval is also wider at the ends, but it is harder to see in prediction intervals than confidence intervals</p>
<div class="sourceCode" id="cb253"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">housePred</span> <span class="op">&lt;-</span> <span class="va">mod.lnsqft</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">mod.lnsqft</span>, interval<span class="op">=</span><span class="st">"prediction"</span><span class="op">)</span> <span class="op">)</span>  <span class="co"># cbind binds the columns together</span>

<span class="va">housePred</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>##   log(price) sqft  .fitted       .hat    .sigma      .cooksd  .std.resid
## 1   12.73376 3392 13.48618 0.03494894 0.4448768 5.240194e-02 -1.70116646
## 2   13.71004 4100 13.78878 0.06748451 0.4529518 1.186788e-03 -0.18110383
## 3   13.01398 3200 13.40412 0.02856505 0.4508768 1.136429e-02 -0.87917543
## 4   12.38839 1436 12.65019 0.01862011 0.4520790 3.268479e-03 -0.58696923
## 5   12.84133 1944 12.86731 0.01247712 0.4530341 2.130978e-05 -0.05807924
## 6   12.61120 1500 12.67755 0.01744506 0.4529817 1.961713e-04 -0.14865344
##        fit      lwr      upr
## 1 13.48618 12.57483 14.39754
## 2 13.78878 12.86321 14.71435
## 3 13.40412 12.49558 14.31266
## 4 12.65019 11.74606 13.55433
## 5 12.86731 11.96591 13.76872
## 6 12.67755 11.77393 13.58116</code></pre>
<div class="sourceCode" id="cb255"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="va">housePred</span>, <span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">sqft</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y<span class="op">=</span><span class="va">`log(price)`</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_line</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>y<span class="op">=</span><span class="va">.fitted</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_ribbon</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>ymin<span class="op">=</span><span class="va">lwr</span>, ymax<span class="op">=</span><span class="va">upr</span><span class="op">)</span>, fill<span class="op">=</span><span class="st">"blue"</span>, alpha<span class="op">=</span><span class="fl">0.2</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-27-1.png" width="480" style="display: block; margin: auto;"></div>
</div>
<div id="predicting-with-more-than-one-explanatory-variable" class="section level5 unnumbered">
<h5>Predicting with more than one explanatory variable:<a class="anchor" aria-label="anchor" href="#predicting-with-more-than-one-explanatory-variable"><i class="fas fa-link"></i></a>
</h5>
<p>The predict function still works to give estimates of the average value and the predicted individual values, but the plot is now much harder to draw because with three explanatory variables, we would need a 4-d plot to visualize the model and the predictions.</p>
<div class="sourceCode" id="cb256"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">sqftbedbathlm</span> <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">price</span><span class="op">)</span><span class="op">~</span><span class="va">sqft</span> <span class="op">+</span> <span class="va">bedrooms</span> <span class="op">+</span> <span class="va">baths</span>, data<span class="op">=</span><span class="va">house</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">sqftbedbathlm</span>, 
        newdata<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>sqft<span class="op">=</span><span class="fl">2000</span>, bedrooms<span class="op">=</span><span class="fl">3</span>, baths<span class="op">=</span><span class="fl">2</span><span class="op">)</span>, 
        interval<span class="op">=</span><span class="st">"confidence"</span>, level<span class="op">=</span><span class="fl">.95</span><span class="op">)</span></code></pre></div>
<pre><code>##        fit      lwr      upr
## 1 12.91816 12.80085 13.03548</code></pre>
<div class="sourceCode" id="cb258"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span><span class="op">(</span><span class="va">sqftbedbathlm</span>, 
        newdata<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>sqft<span class="op">=</span><span class="fl">2000</span>, bedrooms<span class="op">=</span><span class="fl">3</span>, baths<span class="op">=</span><span class="fl">2</span><span class="op">)</span>, 
        interval<span class="op">=</span><span class="st">"prediction"</span>, level<span class="op">=</span><span class="fl">.95</span><span class="op">)</span></code></pre></div>
<pre><code>##        fit      lwr     upr
## 1 12.91816 12.00953 13.8268</code></pre>
<p>Again, it is hard to back-transform the prediction for the <strong>average</strong> (we end up thinking about it as a median), but we can back-transform the interval of individual prices. 95% of homes with 2000sqft, 3 bedrooms, and 2 baths cost between $164,312 and $1,011,356.</p>
</div>
</div>
</div>
<div id="ex:1819flu" class="section level3" number="7.3.3">
<h3>
<span class="header-section-number">7.3.3</span> Example: 1918-19 Flu and Excess Deaths<a class="footnote-ref" tabindex="0" data-toggle="popover" data-content="&lt;p&gt;thanks to Laura Ring Kapitula at Grand Valley State University&lt;/p&gt;"><sup>29</sup></a><a class="anchor" aria-label="anchor" href="#ex:1819flu"><i class="fas fa-link"></i></a>
</h3>
<p>As we are coming to know, measuring the impact of COVID-19 is difficult. A recent NYTimes article compares total deaths in 2020 as compared with 2015-2019 for 8 different regions.</p>
<div class="figure" style="text-align: center">
<span id="fig:unnamed-chunk-29"></span>
<img src="figs/covid_excess.png" alt="US Death Toll 2020, NY Times, April 28, 2020, https://www.nytimes.com/interactive/2020/04/28/us/coronavirus-death-toll-total.html" width="630"><p class="caption">
Figure 7.1: US Death Toll 2020, NY Times, April 28, 2020, <a href="https://www.nytimes.com/interactive/2020/04/28/us/coronavirus-death-toll-total.html" class="uri">https://www.nytimes.com/interactive/2020/04/28/us/coronavirus-death-toll-total.html</a>
</p>
</div>
<p>While it is still too early to model COVID-19 well, we do have information from the 1918-19 Flu pandemic that was similar in many ways to the current COVID-19 pandemic. In 2007, Markel et al. published research in the <em>Journal of the American Medical Association</em> detailing the results from different social distancing practices across the US, “Nonpharmaceutical Interventions Implemented by US Cities During the 1918-1919 Influenza Pandemic” [JAMA, Aug 8, 2007, Vol 298, No 6].</p>
<div class="figure" style="text-align: center">
<span id="fig:unnamed-chunk-30"></span>
<img src="figs/jama_covid.png" alt="Nonpharmaceutical Interventions Implemented by US Cities During the 1918-1919 Influenza Pandemic, https://jamanetwork.com/journals/jama/fullarticle/208354" width="772"><p class="caption">
Figure 7.2: Nonpharmaceutical Interventions Implemented by US Cities During the 1918-1919 Influenza Pandemic, <a href="https://jamanetwork.com/journals/jama/fullarticle/208354" class="uri">https://jamanetwork.com/journals/jama/fullarticle/208354</a>
</p>
</div>
<p>Their conclusions are worth restating:</p>
<blockquote>
<p><strong>Conclusions</strong> These findings demonstrate a strong association between early, sustained, and layered application of nonpharmaceutical interventions and mitigating the consequences of the 1918-1919 influenza pandemic in the United States. In planning for future severe influenza pandemics, nonpharmaceutical interventions should be considered for inclusion as companion measures to developing effective vaccines and medications for prophylaxis and treatment.</p>
</blockquote>
<p>While the entire paper is fascinating and does a great job describing different interventions and related outcomes, we will focus on the regression analysis done to model the excess death rate. The data used below come directly from page 647 of the manuscript.</p>
<div class="figure" style="text-align: center">
<span id="fig:unnamed-chunk-31"></span>
<img src="figs/jama_scatterplot.png" alt="Note that figure 1b seems to have the y-axis mis-labelled (it should be magnitude of first mortality peak).  Table 4 uses a test other than linear regression (Wilcoxon rank sum test -- a two sample test of means done on ranked data rather than raw data) to compare the outcome variables broken into two groups:  below the median response time and above the median response time." width="794"><p class="caption">
Figure 7.3: Note that figure 1b seems to have the y-axis mis-labelled (it should be magnitude of first mortality peak). Table 4 uses a test other than linear regression (Wilcoxon rank sum test – a two sample test of means done on ranked data rather than raw data) to compare the outcome variables broken into two groups: below the median response time and above the median response time.
</p>
</div>
<div class="sourceCode" id="cb260"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">flu_1819</span> <span class="op">&lt;-</span> <span class="fu">read_csv</span><span class="op">(</span><span class="st">"1918_1919flu.csv"</span>, 
                     col_types <span class="op">=</span> <span class="fu">cols</span><span class="op">(</span>`Date of peak Excess death rate` <span class="op">=</span> <span class="fu">col_date</span><span class="op">(</span>format <span class="op">=</span> <span class="st">"%m/%d/%y"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">flu_1819</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"place"</span>, <span class="st">"responseTime"</span>, <span class="st">"daysNonpharm"</span>, <span class="st">"datePeak"</span>, 
                     <span class="st">"timePeak"</span>, <span class="st">"magPeak"</span>, <span class="st">"excessDeaths"</span><span class="op">)</span>

<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">flu_1819</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 6 x 7
##   place       responseTime daysNonpharm datePeak   timePeak magPeak excessDeaths
##   &lt;chr&gt;              &lt;dbl&gt;        &lt;dbl&gt; &lt;date&gt;        &lt;dbl&gt;   &lt;dbl&gt;        &lt;dbl&gt;
## 1 Albany, NY             3           47 2018-10-24       15   162.          553.
## 2 Baltimore,…           10           43 2018-10-18        9   182.          559.
## 3 Birmingham…            9           48 2018-10-22       13    70.9         592.
## 4 Boston, MA            13           50 2018-10-03        8   160.          710 
## 5 Buffalo, NY           12           49 2018-10-22       12   141.          530.
## 6 Cambridge,…           14           49 2018-10-03        8   126.          541</code></pre>
<div id="correlation-between-variables" class="section level4 unnumbered">
<h4>Correlation between variables<a class="anchor" aria-label="anchor" href="#correlation-between-variables"><i class="fas fa-link"></i></a>
</h4>
<p>To be consistent with the manuscript, Spearman correlation is used instead of Pearson. Spearman is the Pearson correlation applied to the ranks of the observations (instead of the raw values of the observations). Calculating Spearman has the impact of lessening the influence of outlying observations.</p>
<p>The correlations calculated below match the values in the manuscript, but we repeat the analysis without St Paul, MN and Grand Rapids, MI to see their impact on the analysis. I would not remove the two cities without a justifiable reason (something that makes them fundamentally different from the other cities, worth not including in the model); however, it is worth re-calculations just to investigate the impact of individual observations. Here it seems that there is some impact (e.g., excessDeaths and responseTime) but possibly the impact is only moderate.</p>
<div class="sourceCode" id="cb262"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">excessDeaths</span>, <span class="va">magPeak</span>, <span class="va">responseTime</span>, <span class="va">daysNonpharm</span>, <span class="va">timePeak</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://projectmosaic.github.io/mosaic/reference/aggregating.html">cor</a></span><span class="op">(</span>method<span class="op">=</span><span class="st">"spearman"</span><span class="op">)</span></code></pre></div>
<pre><code>##              excessDeaths    magPeak responseTime daysNonpharm   timePeak
## excessDeaths    1.0000000  0.7639686    0.3658238   -0.3925996 -0.1619664
## magPeak         0.7639686  1.0000000    0.3090137   -0.5739853 -0.2541940
## responseTime    0.3658238  0.3090137    1.0000000   -0.6808529 -0.7346764
## daysNonpharm   -0.3925996 -0.5739853   -0.6808529    1.0000000  0.6135956
## timePeak       -0.1619664 -0.2541940   -0.7346764    0.6135956  1.0000000</code></pre>
<div class="sourceCode" id="cb264"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">place</span> <span class="op">!=</span> <span class="st">"St Paul, MN"</span> <span class="op">&amp;</span> <span class="va">place</span> <span class="op">!=</span>  <span class="st">"Grand Rapids, MI"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">select</span><span class="op">(</span><span class="va">excessDeaths</span>, <span class="va">magPeak</span>, <span class="va">responseTime</span>, <span class="va">daysNonpharm</span>, <span class="va">timePeak</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://projectmosaic.github.io/mosaic/reference/aggregating.html">cor</a></span><span class="op">(</span>method<span class="op">=</span><span class="st">"spearman"</span><span class="op">)</span></code></pre></div>
<pre><code>##              excessDeaths    magPeak responseTime daysNonpharm   timePeak
## excessDeaths    1.0000000  0.7402439    0.5093635   -0.4663501 -0.2989616
## magPeak         0.7402439  1.0000000    0.4603040   -0.6752625 -0.4170257
## responseTime    0.5093635  0.4603040    1.0000000   -0.6638306 -0.6969834
## daysNonpharm   -0.4663501 -0.6752625   -0.6638306    1.0000000  0.6007545
## timePeak       -0.2989616 -0.4170257   -0.6969834    0.6007545  1.0000000</code></pre>
</div>
<div id="model-building" class="section level4 unnumbered">
<h4>Model building<a class="anchor" aria-label="anchor" href="#model-building"><i class="fas fa-link"></i></a>
</h4>
<p>Below, both St Paul and Grand Rapids have been removed from the model. Again, in reporting the analysis (as the JAMA authors did correctly), the two cities would not be removed without a justifiable reason (something that makes them fundamentally different from the other cities, worth not including in the model); however, it is worth re-calculations just to investigate the impact of individual observations.</p>
<p>Note that in predicting both <code>excessDeaths</code> and <code>magPeak</code> the most significant variable is <code>daysNonpharm</code>. No other variable adds significantly to the model</p>
<div class="sourceCode" id="cb266"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># excessDeaths as the response variable:</span>
<span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">place</span> <span class="op">!=</span> <span class="st">"St Paul, MN"</span> <span class="op">&amp;</span> <span class="va">place</span> <span class="op">!=</span> <span class="st">"Grand Rapids, MI"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">excessDeaths</span> <span class="op">~</span> <span class="va">responseTime</span> <span class="op">+</span> <span class="va">daysNonpharm</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term         estimate std.error statistic  p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)   552.       67.0        8.24 5.50e-10
## 2 responseTime    5.57      3.90       1.43 1.62e- 1
## 3 daysNonpharm   -0.828     0.503     -1.65 1.08e- 1</code></pre>
<div class="sourceCode" id="cb268"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">place</span> <span class="op">!=</span> <span class="st">"St Paul, MN"</span> <span class="op">&amp;</span> <span class="va">place</span> <span class="op">!=</span> <span class="st">"Grand Rapids, MI"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">excessDeaths</span> <span class="op">~</span>  <span class="va">daysNonpharm</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   term         estimate std.error statistic  p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)    628.      41.7       15.0  7.92e-18
## 2 daysNonpharm    -1.25     0.412     -3.03 4.28e- 3</code></pre>
<div class="sourceCode" id="cb270"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">place</span> <span class="op">!=</span> <span class="st">"St Paul, MN"</span> <span class="op">&amp;</span> <span class="va">place</span> <span class="op">!=</span> <span class="st">"Grand Rapids, MI"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">excessDeaths</span> <span class="op">~</span>  <span class="va">responseTime</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 2 x 5
##   term         estimate std.error statistic  p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)    452.       28.8      15.7  1.90e-18
## 2 responseTime     9.35      3.23      2.90 6.14e- 3</code></pre>
<div class="sourceCode" id="cb272"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># magPeak as the response variable:</span>
<span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">place</span> <span class="op">!=</span> <span class="st">"St Paul, MN"</span> <span class="op">&amp;</span> <span class="va">place</span> <span class="op">!=</span> <span class="st">"Grand Rapids, MI"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">magPeak</span> <span class="op">~</span> <span class="va">responseTime</span> <span class="op">+</span> <span class="va">daysNonpharm</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term         estimate std.error statistic       p.value
##   &lt;chr&gt;           &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;         &lt;dbl&gt;
## 1 (Intercept)  167.        21.0      7.95   0.00000000132
## 2 responseTime  -0.0555     1.22    -0.0455 0.964        
## 3 daysNonpharm  -0.715      0.157   -4.55   0.0000541</code></pre>
<div class="sourceCode" id="cb274"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">place</span> <span class="op">!=</span> <span class="st">"St Paul, MN"</span> <span class="op">&amp;</span> <span class="va">place</span> <span class="op">!=</span> <span class="st">"Grand Rapids, MI"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">magPeak</span><span class="op">)</span> <span class="op">~</span> <span class="va">responseTime</span> <span class="op">+</span> <span class="va">daysNonpharm</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://generics.r-lib.org/reference/tidy.html">tidy</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## # A tibble: 3 x 5
##   term          estimate std.error statistic  p.value
##   &lt;chr&gt;            &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept)   5.20       0.211     24.6    5.69e-25
## 2 responseTime -0.000741   0.0123    -0.0603 9.52e- 1
## 3 daysNonpharm -0.00769    0.00158   -4.86   2.05e- 5</code></pre>
</div>
<div id="checking-residuals" class="section level4 unnumbered">
<h4>Checking Residuals<a class="anchor" aria-label="anchor" href="#checking-residuals"><i class="fas fa-link"></i></a>
</h4>
<p>Turns out the residuals for these models aren’t great (maybe that is why the authors used ranked based methods like Spearman correlation and Wilcoxon rank sum test??? – those tests have different technical conditions, not based in normal theory!)</p>
<div class="sourceCode" id="cb276"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># excessDeaths as the response variable:</span>
<span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">place</span> <span class="op">!=</span> <span class="st">"St Paul, MN"</span> <span class="op">&amp;</span> <span class="va">place</span> <span class="op">!=</span> <span class="st">"Grand Rapids, MI"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">excessDeaths</span> <span class="op">~</span>  <span class="va">daysNonpharm</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"St Paul &amp; Grand Rapids removed, excessDeath vs days Nonparm"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-35-1.png" width="480" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb277"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">excessDeaths</span> <span class="op">~</span>  <span class="va">daysNonpharm</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"St Paul &amp; Grand Rapids NOT removed, excessDeath vs days Nonparm"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-35-2.png" width="480" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb278"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># magPeak as the response variable:</span>
<span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">place</span> <span class="op">!=</span> <span class="st">"St Paul, MN"</span> <span class="op">&amp;</span> <span class="va">place</span> <span class="op">!=</span> <span class="st">"Grand Rapids, MI"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">magPeak</span> <span class="op">~</span> <span class="va">responseTime</span> <span class="op">+</span> <span class="va">daysNonpharm</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"St Paul &amp; Grand Rapids removed, magPeak vs days responseTime"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-35-3.png" width="480" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb279"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">magPeak</span> <span class="op">~</span> <span class="va">responseTime</span> <span class="op">+</span> <span class="va">daysNonpharm</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"St Paul &amp; Grand Rapids NOT removed, magPeak vs days responseTime"</span><span class="op">)</span></code></pre></div>
<div class="inline-figure"><img src="06-CorRegInf_files/figure-html/unnamed-chunk-35-4.png" width="480" style="display: block; margin: auto;"></div>
<div class="sourceCode" id="cb280"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">flu_1819</span> <span class="op">%&gt;%</span>
  <span class="fu">mutate</span><span class="op">(</span>ln_magPeak <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Log.html">log</a></span><span class="op">(</span><span class="va">magPeak</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/filter.html">filter</a></span><span class="op">(</span><span class="va">place</span> <span class="op">!=</span> <span class="st">"St Paul, MN"</span> <span class="op">&amp;</span> <span class="va">place</span> <span class="op">!=</span> <span class="st">"Grand Rapids, MI"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">ln_magPeak</span> <span class="op">~</span> <span class="va">responseTime</span> <span class="op">+</span> <span class="va">daysNonpharm</span>, data <span class="op">=</span> <span class="va">.</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://generics.r-lib.org/reference/augment.html">augment</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_point</span><span class="op">(</span><span class="fu">aes</span><span class="op">(</span>x<span class="op">=</span><span class="va">.fitted</span>, y <span class="op">=</span> <span class="va">.resid</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_hline</span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">ggtitle</span><span class="op">(</span><span class="st">"St Paul &amp; Grand Rapids removed, log(magPeak) vs days responseTime"</span><span class="op">)</span></code></pre></div>
</div>
<div id="what-else-do-we-know-about-covid-19-right-now" class="section level4 unnumbered">
<h4>What else do we know about COVID-19 right now?<a class="anchor" aria-label="anchor" href="#what-else-do-we-know-about-covid-19-right-now"><i class="fas fa-link"></i></a>
</h4>
<p>Clinical trials are starting to show up assessing know anti-viral pharmaceutical interventions on patients with COVID-19.</p>
<div id="study-1" class="section level5 unnumbered">
<h5>Study 1:<a class="anchor" aria-label="anchor" href="#study-1"><i class="fas fa-link"></i></a>
</h5>
<div class="figure" style="text-align: center">
<span id="fig:unnamed-chunk-37"></span>
<img src="figs/lancet_remdesivir.png" alt="Remdesivir in adults with severe COVID-19: a randomised, double-blind, placebo-controlled, multicentre trial, https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31022-9/fulltext" width="752"><p class="caption">
Figure 7.4: Remdesivir in adults with severe COVID-19: a randomised, double-blind, placebo-controlled, multicentre trial, <a href="https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31022-9/fulltext" class="uri">https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31022-9/fulltext</a>
</p>
</div>
<blockquote>
<p><strong>Findings</strong> Between Feb 6, 2020, and March 12, 2020, 237 patients were enrolled and randomly assigned to a treatment group (158 to remdesivir and 79 to placebo); one patient in the placebo group who withdrew after randomisation was not included in the ITT population. Remdesivir use was not associated with a difference in time to clinical improvement (hazard ratio 1·23 [95% CI 0·87–1·75]). Although not statistically significant, patients receiving remdesivir had a numerically faster time to clinical improvement than those receiving placebo among patients with symptom duration of 10 days or less (hazard ratio 1·52 [0·95–2·43]). Adverse events were reported in 102 (66%) of 155 remdesivir recipients versus 50 (64%) of 78 placebo recipients. Remdesivir was stopped early because of adverse events in 18 (12%) patients versus four (5%) patients who stopped placebo early.</p>
</blockquote>
<ul>
<li>animal studies have shown remdesivir inhibits SARS-CoV-2 replication</li>
<li>study was randomized, double-blind, placebo-controlled, multi-center</li>
<li>adults with laboratory-confirmed SARS-CoV-2 infection, low oxygen, pneumonia</li>
<li>randomly assigned in a 2:1 ratio to remdesivir vs placebo</li>
<li>
<strong>not statistically significant</strong> !</li>
<li>patients on remdesivir had a numerically faster time to clinical improvement</li>
<li>trial was stopped before enrolling the expected number of patients because the outbreak of COVID-19 was brought under control</li>
</ul>
</div>
<div id="study-2" class="section level5 unnumbered">
<h5>Study 2:<a class="anchor" aria-label="anchor" href="#study-2"><i class="fas fa-link"></i></a>
</h5>
<p>Gilead, a large pharmaceutical company, issued a press release describing results from a clinical trial involving remdesivir. They were mostly seeking to understand how long the treatment should continue and what are the adverse effects of the drug.</p>
<div class="figure" style="text-align: center">
<span id="fig:unnamed-chunk-38"></span>
<img src="figs/gilead_remdesivir.png" alt="Gilead press release (no peer reviewed publication yet), https://www.gilead.com/news-and-press/press-room/press-releases/2020/4/gilead-announces-results-from-phase-3-trial-of-investigational-antiviral-remdesivir-in-patients-with-severe-covid-19https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31022-9/fulltext" width="879"><p class="caption">
Figure 7.5: Gilead press release (no peer reviewed publication yet), <a href="https://www.gilead.com/news-and-press/press-room/press-releases/2020/4/gilead-announces-results-from-phase-3-trial-of-investigational-antiviral-remdesivir-in-patients-with-severe-covid-19https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31022-9/fulltext" class="uri">https://www.gilead.com/news-and-press/press-room/press-releases/2020/4/gilead-announces-results-from-phase-3-trial-of-investigational-antiviral-remdesivir-in-patients-with-severe-covid-19https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(20)31022-9/fulltext</a>
</p>
</div>
<blockquote>
<p>In this study, the time to clinical improvement for 50 percent of patients was 10 days in the 5-day treatment group and 11 days in the 10-day treatment group. More than half of patients in both treatment groups were discharged from the hospital by Day 14 (5-day: 60.0%, n=120/200 vs.10-day: 52.3% n=103/197; p=0.14). At Day 14, 64.5 percent (n=129/200) of patients in the 5-day treatment group and 53.8 percent (n=106/197) of patients in the 10-day treatment group achieved clinical recovery.</p>
</blockquote>
<ul>
<li>two patient groups are 5-day and 10-day treatment courses (no placebo), randomized</li>
<li>patients on ventilators were not enrolled</li>
</ul>
<p><em>The NY Times</em> covered the Gilead announement. Indeed, the outcome of the trials have important political ramifications as well.</p>
<div class="figure" style="text-align: center">
<span id="fig:unnamed-chunk-39"></span>
<img src="figs/nyt_remdesivir.png" alt="Gilead remdesivir trial covered in the NYT, https://www.nytimes.com/2020/04/29/health/gilead-remdesivir-coronavirus.html" width="653"><p class="caption">
Figure 7.6: Gilead remdesivir trial covered in the NYT, <a href="https://www.nytimes.com/2020/04/29/health/gilead-remdesivir-coronavirus.html" class="uri">https://www.nytimes.com/2020/04/29/health/gilead-remdesivir-coronavirus.html</a>
</p>
</div>
</div>
</div>
</div>
</div>
<div id="reflection-questions-5" class="section level2" number="7.4">
<h2>
<span class="header-section-number">7.4</span> Reflection Questions<a class="anchor" aria-label="anchor" href="#reflection-questions-5"><i class="fas fa-link"></i></a>
</h2>
<div id="correlation-simple-linear-regression-ims-sections-8.1-8.2" class="section level3" number="7.4.1">
<h3>
<span class="header-section-number">7.4.1</span> Correlation &amp; Simple Linear Regression: IMS Sections 8.1 &amp; 8.2<a class="anchor" aria-label="anchor" href="#correlation-simple-linear-regression-ims-sections-8.1-8.2"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>Describe the linear model with multiple variables.</li>
<li>Describe the error / residual term and how it is calculated with multiple variables.</li>
<li>What are the (three-ish) statistics of interest in this chapter? What are the parameters of interest?</li>
<li>What does correlation measure?</li>
<li>How do we find the values of <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span> for estimating the least squares line?</li>
<li>Why is it dangerous to extrapolate?</li>
<li>How do we interpret <span class="math inline">\(R^2\)</span>? Why is that?</li>
<li>What does it mean to say that <span class="math inline">\(b_1\)</span> has a sampling distribution? Why is it that we would never talk about the sampling distribution of <span class="math inline">\(\beta_1\)</span>?</li>
<li>Why do we need the LINE technical conditions for the inference parts of the analysis but not for the estimation parts of the analysis?</li>
<li>Is linear regression always appropriate when comparing two continuous variables?</li>
<li>What are the LINE technical conditions? How are the conditions assessed?</li>
<li>What are the three factors that influence the <span class="math inline">\(SE(b_1)\)</span>? (Note: when something influences <span class="math inline">\(SE(b_1)\)</span>, that means the inference is also effected. If you have a huge <span class="math inline">\(SE(b_1)\)</span>, it will be hard to tell if the slope is significant because the t value will be small.)</li>
<li>What does it mean to do a randomization test for the slope? That is, explain the process of doing a randomization test here. (See shuffle options in the Analyzing Two Quantitative Variables applet.)</li>
<li>Why would someone transform either of the variables?</li>
<li>What is the difference between a confidence interval and a prediction interval? Which is bigger? Why does that make sense? How do the centers of the intervals differ? (They don’t. Why not?)</li>
</ul>
</div>
<div id="multiple-linear-regression-ims-chapter-4-section-8.4" class="section level3" number="7.4.2">
<h3>
<span class="header-section-number">7.4.2</span> Multiple Linear Regression: IMS Chapter 4 &amp; Section 8.4<a class="anchor" aria-label="anchor" href="#multiple-linear-regression-ims-chapter-4-section-8.4"><i class="fas fa-link"></i></a>
</h3>
<ul>
<li>Describe the linear model with multiple variables.</li>
<li>Describe the error / residual term and how it is calculated with multiple variables.</li>
<li>How does the model change when multiple variables are included?</li>
<li>How are p-values interpreted now that there are multiple variables?</li>
<li>How is <span class="math inline">\(R^2\)</span> interpreted? What is the difference between <span class="math inline">\(R^2\)</span> and <span class="math inline">\(R^2_{adj}\)</span>?</li>
<li>How are variables chosen for the final model?</li>
<li>How are the model conditions assessed?</li>
</ul>
</div>
</div>
</div>

  <div class="chapter-nav">
<div class="prev"><a href="inference-for-numerical-data.html"><span class="header-section-number">6</span> Inference for numerical data</a></div>
<div class="next"><a href="interlude-in-spring-2020.html"><span class="header-section-number">8</span> Interlude in Spring 2020</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li>
<a class="nav-link" href="#reginf"><span class="header-section-number">7</span> Inference on Correlation &amp; Regression</a><ul class="nav navbar-nav"><li><a class="nav-link" href="#inference-for-correlation"><span class="header-section-number">7.0.1</span> Inference for correlation</a></li></ul>
</li>
<li>
<a class="nav-link" href="#simple-linear-regression-1"><span class="header-section-number">7.1</span> Simple Linear Regression</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#infbeta1"><span class="header-section-number">7.1.1</span> Inference on the slope, \(\beta_1\)</a></li>
<li><a class="nav-link" href="#lmtechcond"><span class="header-section-number">7.1.2</span> Regression Technical Conditions</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#MLR"><span class="header-section-number">7.2</span> Multiple Linear Regression</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#MLRmod"><span class="header-section-number">7.2.1</span> Model selection</a></li>
<li><a class="nav-link" href="#checking-model-assumptions"><span class="header-section-number">7.2.2</span> Checking model assumptions</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#r-code-for-regression-1"><span class="header-section-number">7.3</span> R code for regression</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#ex:cat2"><span class="header-section-number">7.3.1</span> Example: Cat Jumping27 (Correlation &amp; SLR)</a></li>
<li><a class="nav-link" href="#ex:houses2"><span class="header-section-number">7.3.2</span> Example: Housing Prices28 (SLR &amp; MLR &amp; Prediction)</a></li>
<li><a class="nav-link" href="#ex:1819flu"><span class="header-section-number">7.3.3</span> Example: 1918-19 Flu and Excess Deaths29</a></li>
</ul>
</li>
<li>
<a class="nav-link" href="#reflection-questions-5"><span class="header-section-number">7.4</span> Reflection Questions</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#correlation-simple-linear-regression-ims-sections-8.1-8.2"><span class="header-section-number">7.4.1</span> Correlation &amp; Simple Linear Regression: IMS Sections 8.1 &amp; 8.2</a></li>
<li><a class="nav-link" href="#multiple-linear-regression-ims-chapter-4-section-8.4"><span class="header-section-number">7.4.2</span> Multiple Linear Regression: IMS Chapter 4 &amp; Section 8.4</a></li>
</ul>
</li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
<li><a id="book-source" href="https://github.com/hardin47/website/blob/master/06-CorRegInf.Rmd">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="https://github.com/hardin47/website/edit/master/06-CorRegInf.Rmd">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Introduction to (Bio)Statistics</strong>" was written by Jo Hardin. It was last built on 2021-04-19.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>
</html>
